#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        AttoDRY.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.1000
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      christoph.murer$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["AttoDRY", "AttoDRYClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(AttoDRY.additionnal_import) ENABLED START -----#
import socket
from AttoDRYThread import*
from AttoDRYCheck import*
#----- PROTECTED REGION END -----#	//	AttoDRY.additionnal_import

# Device States Description
# No states for this device


class AttoDRY (PyTango.Device_4Impl):
    """Server connecting to the AttoDRY2100. Uses an SSH connection to send and receive commands."""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(AttoDRY.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	AttoDRY.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        AttoDRY.init_device(self)
        #----- PROTECTED REGION ID(AttoDRY.__init__) ENABLED START -----#
        self.set_state(PyTango.DevState.STANDBY)
        self.Connect()
        #----- PROTECTED REGION END -----#	//	AttoDRY.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(AttoDRY.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	AttoDRY.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_MagneticField_read = 0.0
        self.attr_Temperature_read = 1.6
        self.attr_toggleMagneticFieldControl_read = False
        self.attr_toggleFulltemperatureControl_read = False
        self.attr_togglePersistentMode_read = False
        #----- PROTECTED REGION ID(AttoDRY.init_device) ENABLED START -----#
        self.setField = 0.0
        self.setTemp = 1.6
        self.datastring = 'ReadA0B0C0D0.0E0.0F'
        self.res1 = re.search('A(.*)B',self.datastring).group(1)
        self.res2 = re.search('B(.*)C',self.datastring).group(1)
        self.res3 = re.search('C(.*)D',self.datastring).group(1)
        self.res4 = re.search('D(.*)E',self.datastring).group(1)
        self.res5 = re.search('E(.*)F',self.datastring).group(1)     
        #----- PROTECTED REGION END -----#	//	AttoDRY.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(AttoDRY.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	AttoDRY.always_executed_hook

    # -------------------------------------------------------------------------
    #    AttoDRY read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_MagneticField(self, attr):
        self.debug_stream("In read_MagneticField()")
        #----- PROTECTED REGION ID(AttoDRY.MagneticField_read) ENABLED START -----#
        # just put the datastring that is read here...
        # always run the script when reading values...
        self.Start()
        self.attr_MagneticField_read = float(self.res4)
        attr.set_value(self.attr_MagneticField_read)
        #----- PROTECTED REGION END -----#	//	AttoDRY.MagneticField_read
        
    def write_MagneticField(self, attr):
        self.debug_stream("In write_MagneticField()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.MagneticField_write) ENABLED START -----#
        self.setField = data
        B = 'W001:'+str(data)
        self.s.sendto(B.encode('utf-8'), self.server)
        self.thread = AttoDRYCheck(self)
        self.thread.start()        
        #----- PROTECTED REGION END -----#	//	AttoDRY.MagneticField_write
        
    def read_Temperature(self, attr):
        self.debug_stream("In read_Temperature()")
        #----- PROTECTED REGION ID(AttoDRY.Temperature_read) ENABLED START -----#
        self.attr_Temperature_read = float(self.res5)
        attr.set_value(self.attr_Temperature_read)
        #----- PROTECTED REGION END -----#	//	AttoDRY.Temperature_read
        
    def write_Temperature(self, attr):
        self.debug_stream("In write_Temperature()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.Temperature_write) ENABLED START -----#
        self.setTemp = data
        T = 'W002:'+str(data)
        self.s.sendto(T.encode('utf-8'), self.server)
        self.thread = AttoDRYCheck(self)
        self.thread.start()  
        #----- PROTECTED REGION END -----#	//	AttoDRY.Temperature_write
        
    def read_toggleMagneticFieldControl(self, attr):
        self.debug_stream("In read_toggleMagneticFieldControl()")
        #----- PROTECTED REGION ID(AttoDRY.toggleMagneticFieldControl_read) ENABLED START -----#
        self.attr_toggleMagneticFieldControl_read = bool(int(self.res1))
        attr.set_value(self.attr_toggleMagneticFieldControl_read)
        
        #----- PROTECTED REGION END -----#	//	AttoDRY.toggleMagneticFieldControl_read
        
    def write_toggleMagneticFieldControl(self, attr):
        self.debug_stream("In write_toggleMagneticFieldControl()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.toggleMagneticFieldControl_write) ENABLED START -----#
        self.s.sendto('W003'.encode('utf-8'), self.server)
        #----- PROTECTED REGION END -----#	//	AttoDRY.toggleMagneticFieldControl_write
        
    def read_toggleFulltemperatureControl(self, attr):
        self.debug_stream("In read_toggleFulltemperatureControl()")
        #----- PROTECTED REGION ID(AttoDRY.toggleFulltemperatureControl_read) ENABLED START -----#
        self.attr_toggleFulltemperatureControl_read = bool(int(self.res2))
        attr.set_value(self.attr_toggleFulltemperatureControl_read)
        #----- PROTECTED REGION END -----#	//	AttoDRY.toggleFulltemperatureControl_read
        
    def write_toggleFulltemperatureControl(self, attr):
        self.debug_stream("In write_toggleFulltemperatureControl()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.toggleFulltemperatureControl_write) ENABLED START -----#
        self.s.sendto('W004'.encode('utf-8'), self.server)
        #----- PROTECTED REGION END -----#	//	AttoDRY.toggleFulltemperatureControl_write
        
    def read_togglePersistentMode(self, attr):
        self.debug_stream("In read_togglePersistentMode()")
        #----- PROTECTED REGION ID(AttoDRY.togglePersistentMode_read) ENABLED START -----#
        self.attr_togglePersistentMode_read = bool(int(self.res3))
        attr.set_value(self.attr_togglePersistentMode_read)
        #----- PROTECTED REGION END -----#	//	AttoDRY.togglePersistentMode_read
        
    def write_togglePersistentMode(self, attr):
        self.debug_stream("In write_togglePersistentMode()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.togglePersistentMode_write) ENABLED START -----#
        self.s.sendto('W005'.encode('utf-8'), self.server)
        #----- PROTECTED REGION END -----#	//	AttoDRY.togglePersistentMode_write
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(AttoDRY.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	AttoDRY.read_attr_hardware


    # -------------------------------------------------------------------------
    #    AttoDRY command methods
    # -------------------------------------------------------------------------
    
    def Connect(self):
        """ Connects to the AttoDRY system sending both the begin() and Connect() commands.
        """
        self.debug_stream("In Connect()")
        #----- PROTECTED REGION ID(AttoDRY.Connect) ENABLED START -----#
        self.host = '192.168.1.7'
        self.port = 11005
        
        self.server = (self.AttoIP,self.AttoPort)
        self.s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.s.bind((self.host,self.port))
        
        # send message to check if server is ok:
        self.s.sendto('start'.encode('utf-8'), self.server)
        self.s.sendto('ON'.encode('utf-8'), self.server)
        data, addr = self.s.recvfrom(1024)
        data = data.decode('utf-8')
        if data == 'ON':
            self.set_state(PyTango.DevState.ON)
        else:
            self.info_stream('Could not connect to the Windows computer...')
            print('Could not connect to the Windows computer...')
            self.set_state(PyTango.DevState.OFF)
     
            
        #----- PROTECTED REGION END -----#	//	AttoDRY.Connect
        
    def Disconnect(self):
        """ Disconnects the AttoDRY system sending the Disconnect() and end() commands.
        """
        self.debug_stream("In Disconnect()")
        #----- PROTECTED REGION ID(AttoDRY.Disconnect) ENABLED START -----#
        if self.thread.is_alive() == True:
            self.thread.stop()
            self.set_state(PyTango.DevState.STANDBY)
        self.s.sendto('OFF'.encode('utf-8'), self.server)   
        self.set_state(PyTango.DevState.OFF)
        self.info_stream('Disconnected from Windows computer...')
        self.s.close()
        #----- PROTECTED REGION END -----#	//	AttoDRY.Disconnect
        
    def Start(self):
        """ 
        """
        self.debug_stream("In Start()")
        #----- PROTECTED REGION ID(AttoDRY.Start) ENABLED START -----#
        if self.get_state() == PyTango.DevState.MOVING or self.get_state() == PyTango.DevState.ON:
            self.thread = AttoDRYThread(self)
            self.thread.start()

    #----- PROTECTED REGION ID(AttoDRY.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	AttoDRY.programmer_methods

class AttoDRYClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(AttoDRY.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	AttoDRY.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'AttoIP':
            [PyTango.DevString, 
             '',
            ["192.168.1.8"] ],
        'AttoPort':
            [PyTango.DevDouble, 
             '',
            [11000]],
        }


    #    Command definitions
    cmd_list = {
        'Connect':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Disconnect':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Start':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'MagneticField':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'Temperature':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'toggleMagneticFieldControl':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'toggleFulltemperatureControl':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'togglePersistentMode':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(AttoDRYClass, AttoDRY, 'AttoDRY')
        #----- PROTECTED REGION ID(AttoDRY.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	AttoDRY.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
