#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        AttoDRY.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.1000
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      christoph.murer.$
#
#  $Revision :    Niklas Kercher$
#
#  $Date :        03.05.2025 $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["AttoDRY", "AttoDRYClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
import re
# Add additional import
#----- PROTECTED REGION ID(AttoDRY.additionnal_import) ENABLED START -----#
import socket
from AttoDRYThread2 import *
from AttoDRYCheck import *
#----- PROTECTED REGION END -----#    //    AttoDRY.additionnal_import

# Device States Description
# No states for this device


class AttoDRY(PyTango.Device_4Impl):
    """Server connecting to the AttoDRY2100. Uses an SSH connection to send and receive commands."""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(AttoDRY.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#    //    AttoDRY.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self, cl, name)
        self.debug_stream("In __init__()")
        AttoDRY.init_device(self)
        #----- PROTECTED REGION ID(AttoDRY.__init__) ENABLED START -----#
        self.set_state(PyTango.DevState.STANDBY)
        self.Connect()
        #----- PROTECTED REGION END -----#    //    AttoDRY.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(AttoDRY.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#    //    AttoDRY.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_MagneticField_read        = 0.0        
        self.attr_Temperature_read          = 1.6
        ######## Niklas 03.06.2025
        self.attr_CryostatInPressure_read   = 0.0
        self.attr_CryostatOutPressure_read  = 0.0
        self.attr_MagnetTemperature_read    = 0.0
        self.attr_ReservoirTemperature_read = 0.0
        self.attr_VtiTemperature_read       = 0.0
        self.attr_SampleHeaterPower_read    = 0.0
        self.attr_ReservoirHeaterPower_read = 0.0
        self.attr_VtiHeaterPower_read       = 0.0        
        ######## End New
        self.attr_toggleMagneticFieldControl_read = False
        self.attr_toggleFulltemperatureControl_read = False
        self.attr_togglePersistentMode_read       = False
        self.attr_GoingToBaseTemperature_read     = False
        #----- PROTECTED REGION ID(AttoDRY.init_device) ENABLED START -----#
        self.setField = 0.0
        self.setTemp  = 1.6
        ######## Niklas 03.06.2025 ########
        #self.datastring = 'ReadA0B0C0D0.0E0.0F0.0G0.0H0.0I0.0J0.0K0.0L0.0M0.0N'
        self.is_controlling_field        = 0 #re.search(r'A(.*)B', self.datastring).group(1)
        self.is_controlling_temperature  = 0 # re.search(r'B(.*)C', self.datastring).group(1)
        self.is_persistent_mode_set      = 0 # re.search(r'C(.*)D', self.datastring).group(1)
        self.current_magnetic_field      = 0 # re.search(r'D(.*)E', self.datastring).group(1)
        self.sample_temperature          = 0 # re.search(r'E(.*)F', self.datastring).group(1)
        self.vti_temperature             = 0 # re.search(r'F(.*)G', self.datastring).group(1)
        self.magnet_temperature          = 0 # re.search(r'G(.*)H', self.datastring).group(1)
        self.reservoir_temperature       = 0 # re.search(r'H(.*)I', self.datastring).group(1)
        self.cryostat_out_pressure       = 0 # re.search(r'I(.*)J', self.datastring).group(1)
        self.cryostat_in_pressure        = 0 # re.search(r'J(.*)K', self.datastring).group(1)
        self.reservoir_heater_power      = 0 # re.search(r'K(.*)L', self.datastring).group(1)
        self.vti_heater_power            = 0 # re.search(r'L(.*)M', self.datastring).group(1)
        self.sample_heater_power         = 0 # re.search(r'M(.*)N', self.datastring).group(1)
        # self.attr_GoingToBaseTemperature = re.search(r'N(.*)O', self.datastring).group(1)
        ######## ----------------- ########
        #----- PROTECTED REGION END -----#    //    AttoDRY.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(AttoDRY.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#    //    AttoDRY.always_executed_hook

    # -------------------------------------------------------------------------
    #    AttoDRY read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_MagneticField(self, attr):
        self.debug_stream("In read_MagneticField()")
        #----- PROTECTED REGION ID(AttoDRY.MagneticField_read) ENABLED START -----#
        self.Start()
        self.attr_MagneticField_read = float(self.current_magnetic_field)
        attr.set_value(self.attr_MagneticField_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.MagneticField_read  
        
    def write_MagneticField(self, attr):
        self.debug_stream("In write_MagneticField()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.MagneticField_write) ENABLED START -----#
        self.setField = data
        B = 'W001:' + str(data)
        self.s.sendto(B.encode('utf-8'), self.server)
        self.thread = AttoDRYCheck(self)
        self.thread.start()        
        #----- PROTECTED REGION END -----#    //    AttoDRY.MagneticField_write
        
    def read_Temperature(self, attr):
        self.debug_stream("In read_Temperature()")
        #----- PROTECTED REGION ID(AttoDRY.Temperature_read) ENABLED START -----#
        self.attr_Temperature_read = float(self.sample_temperature)
        attr.set_value(self.attr_Temperature_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.Temperature_read
        
    def write_Temperature(self, attr):
        self.debug_stream("In write_Temperature()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.Temperature_write) ENABLED START -----#
        self.setTemp = data
        T = 'W002:' + str(data)
        self.s.sendto(T.encode('utf-8'), self.server)
        self.thread = AttoDRYCheck(self)
        self.thread.start()  
        #----- PROTECTED REGION END -----#    //    AttoDRY.Temperature_write
        
    def read_toggleMagneticFieldControl(self, attr):
        self.debug_stream("In read_toggleMagneticFieldControl()")
        #----- PROTECTED REGION ID(AttoDRY.toggleMagneticFieldControl_read) ENABLED START -----#
        self.attr_toggleMagneticFieldControl_read = bool(int(self.is_controlling_field))
        attr.set_value(self.attr_toggleMagneticFieldControl_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.toggleMagneticFieldControl_read
        
    def write_toggleMagneticFieldControl(self, attr):
        self.debug_stream("In write_toggleMagneticFieldControl()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.toggleMagneticFieldControl_write) ENABLED START -----#
        self.s.sendto('W003'.encode('utf-8'), self.server)
        #----- PROTECTED REGION END -----#    //    AttoDRY.toggleMagneticFieldControl_write
        
    def read_toggleFulltemperatureControl(self, attr):
        self.debug_stream("In read_toggleFulltemperatureControl()")
        #----- PROTECTED REGION ID(AttoDRY.toggleFulltemperatureControl_read) ENABLED START -----#
        self.attr_toggleFulltemperatureControl_read = bool(int(self.is_controlling_temperature))
        attr.set_value(self.attr_toggleFulltemperatureControl_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.toggleFulltemperatureControl_read
        
    def write_toggleFulltemperatureControl(self, attr):
        self.debug_stream("In write_toggleFulltemperatureControl()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.toggleFulltemperatureControl_write) ENABLED START -----#
        self.s.sendto('W004'.encode('utf-8'), self.server)
        #----- PROTECTED REGION END -----#    //    AttoDRY.toggleFulltemperatureControl_write
        
    def read_togglePersistentMode(self, attr):
        self.debug_stream("In read_togglePersistentMode()")
        #----- PROTECTED REGION ID(AttoDRY.togglePersistentMode_read) ENABLED START -----#
        self.attr_togglePersistentMode_read = bool(int(self.is_persistent_mode_set))
        attr.set_value(self.attr_togglePersistentMode_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.togglePersistentMode_read
        
    def write_togglePersistentMode(self, attr):
        self.debug_stream("In write_togglePersistentMode()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(AttoDRY.togglePersistentMode_write) ENABLED START -----#
        self.s.sendto('W005'.encode('utf-8'), self.server)
        #----- PROTECTED REGION END -----#    //    AttoDRY.togglePersistentMode_write
    
    ######## Niklas 2025
    
    def read_VtiTemperature(self, attr):
        self.debug_stream("In read_VtiTemperature()")
        #----- PROTECTED REGION ID(AttoDRY.read_VtiTemperature) ENABLED START -----#
        self.Start()
        self.attr_VtiTemperature_read = float(self.vti_temperature)
        attr.set_value(self.attr_VtiTemperature_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_VtiTemperature

    def read_MagnetTemperature(self, attr):
        self.debug_stream("In read_MagnetTemperature()")
        #----- PROTECTED REGION ID(AttoDRY.read_MagnetTemperature) ENABLED START -----#
        self.Start()
        self.attr_MagnetTemperature_read = float(self.magnet_temperature)
        attr.set_value(self.attr_MagnetTemperature_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_MagnetTemperature

    def read_ReservoirTemperature(self, attr):
        self.debug_stream("In read_ReservoirTemperature()")
        #----- PROTECTED REGION ID(AttoDRY.read_ReservoirTemperature) ENABLED START -----#
        self.Start()
        self.attr_ReservoirTemperature_read = float(self.reservoir_temperature)
        attr.set_value(self.attr_ReservoirTemperature_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_ReservoirTemperature

    def read_CryostatOutPressure(self, attr):
        self.debug_stream("In read_CryostatOutPressure()")
        #----- PROTECTED REGION ID(AttoDRY.read_CryostatOutPressure) ENABLED START -----#
        self.Start()
        self.attr_CryostatOutPressure_read = float(self.cryostat_out_pressure)
        attr.set_value(self.attr_CryostatOutPressure_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_CryostatOutPressure

    def read_CryostatInPressure(self, attr):
        self.debug_stream("In read_CryostatInPressure()")
        #----- PROTECTED REGION ID(AttoDRY.read_CryostatInPressure) ENABLED START -----#
        self.Start()
        self.attr_CryostatInPressure_read = float(self.cryostat_in_pressure)
        attr.set_value(self.attr_CryostatInPressure_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_CryostatInPressure

    def read_ReservoirHeaterPower(self, attr):
        self.debug_stream("In read_ReservoirHeaterPower()")
        #----- PROTECTED REGION ID(AttoDRY.read_ReservoirHeaterPower) ENABLED START -----#
        self.Start()
        self.attr_ReservoirHeaterPower_read = float(self.reservoir_heater_power)
        attr.set_value(self.attr_ReservoirHeaterPower_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_ReservoirHeaterPower

    def read_VtiHeaterPower(self, attr):
        self.debug_stream("In read_VtiHeaterPower()")
        #----- PROTECTED REGION ID(AttoDRY.read_VtiHeaterPower) ENABLED START -----#
        self.Start()
        self.attr_VtiHeaterPower_read = float(self.vti_heater_power)
        attr.set_value(self.attr_VtiHeaterPower_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_VtiHeaterPower

    def read_SampleHeaterPower(self, attr):
        self.debug_stream("In read_SampleHeaterPower()")
        #----- PROTECTED REGION ID(AttoDRY.read_SampleHeaterPower) ENABLED START -----#
        self.Start()
        self.attr_SampleHeaterPower_read = float(self.sample_heater_power)
        attr.set_value(self.attr_SampleHeaterPower_read)
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_SampleHeaterPower
    
    # def read_toggleGoingToBaseTemperature(self, attr):
        # self.debug_stream("In read_toggleGoToBaseTemperature()")
        # #----- PROTECTED REGION ID(AttoDRY.togglePersistentMode_read) ENABLED START -----#
        # self.attr_GoingToBaseTemperature_read = bool(int(self.attr_GoingToBaseTemperature))
        # attr.set_value(self.attr_togglePersistentMode_read)
        # #----- PROTECTED REGION END -----#    //    AttoDRY.read_toggleGoToBaseTemperature
    
    # def write_toggleGoingToBaseTemperature(self, attr):
        # self.debug_stream("In write_toggleGoingToBaseTemperature()")
        # data = attr.get_write_value()
        # #----- PROTECTED REGION ID(AttoDRY.togglePersistentMode_write) ENABLED START -----#
        # self.s.sendto('W006'.encode('utf-8'), self.server)
        # #----- PROTECTED REGION END -----#    //    AttoDRY.write_toggleGoingToBaseTemperature
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(AttoDRY.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#    //    AttoDRY.read_attr_hardware


    # -------------------------------------------------------------------------
    #    AttoDRY command methods
    # -------------------------------------------------------------------------
    
    def Connect(self):
        """ Connects to the AttoDRY system sending both the begin() and Connect() commands.
        """
        self.debug_stream("In Connect()")
        #----- PROTECTED REGION ID(AttoDRY.Connect) ENABLED START -----#
        self.host = '192.168.1.7'
        self.port = 11005
        
        # ensure AttoPort is int
        self.server = (self.AttoIP, int(self.AttoPort))
        self.s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.s.bind((self.host, self.port))
        
        # send message to check if server is ok:
        self.s.sendto('start'.encode('utf-8'), self.server)
        self.s.sendto('ON'.encode('utf-8'), self.server)
        data, addr = self.s.recvfrom(1024)
        data = data.decode('utf-8')
        if data == 'ON':
            self.set_state(PyTango.DevState.ON)
        else:
            self.info_stream('Could not connect to the Windows computer...')
            print('Could not connect to the Windows computer...')
            self.set_state(PyTango.DevState.OFF)
        #----- PROTECTED REGION END -----#    //    AttoDRY.Connect
        
    def Disconnect(self):
        """ Disconnects the AttoDRY system sending the Disconnect() and end() commands.
        """
        self.debug_stream("In Disconnect()")
        #----- PROTECTED REGION ID(AttoDRY.Disconnect) ENABLED START -----#
        if hasattr(self, "thread") and self.thread.is_alive():
            self.thread.stop()
            self.set_state(PyTango.DevState.STANDBY)
        self.s.sendto('OFF'.encode('utf-8'), self.server)   
        self.set_state(PyTango.DevState.OFF)
        self.info_stream('Disconnected from Windows computer...')
        self.s.close()
        #----- PROTECTED REGION END -----#    //    AttoDRY.Disconnect
        
    def Start(self):
        """ 
        """
        self.debug_stream("In Start()")
        #----- PROTECTED REGION ID(AttoDRY.Start) ENABLED START -----#
        if self.get_state() in (PyTango.DevState.MOVING, PyTango.DevState.ON):
            self.thread = AttoDRYThread2(self)
            self.thread.start()
        #----- PROTECTED REGION END -----#    //    AttoDRY.Start

    #----- PROTECTED REGION ID(AttoDRY.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#    //    AttoDRY.programmer_methods


class AttoDRYClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(AttoDRY.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#    //    AttoDRY.global_class_variables


    #    Class Properties
    class_property_list = {
        }

    #    Device Properties
    device_property_list = {
        'AttoIP':
            [PyTango.DevString, 
             '',
            ["192.168.1.8"]],
        'AttoPort':
            [PyTango.DevDouble, 
             '',
            [11000]],
        }

    #    Command definitions
    cmd_list = {
        'Connect':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Disconnect':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Start':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        }

    #    Attribute definitions
    attr_list = {
        'MagneticField':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'Temperature':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'toggleMagneticFieldControl':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'toggleFulltemperatureControl':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'togglePersistentMode':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'VtiTemperature':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'MagnetTemperature':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'ReservoirTemperature':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CryostatOutPressure':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'CryostatInPressure':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'ReservoirHeaterPower':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'VtiHeaterPower':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'SampleHeaterPower':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        # 'toggleGoingToBaseTemperature':
            # [[PyTango.DevBoolean,
            # PyTango.SCALAR,
            # PyTango.READ_WRITE]],
    }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(AttoDRYClass, AttoDRY, 'AttoDRY')
        #----- PROTECTED REGION ID(AttoDRY.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#    //    AttoDRY.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print('-------> An unforeseen exception occured....', e)


if __name__ == '__main__':
    main()
