/*----- PROTECTED REGION ID(Magnet.h) ENABLED START -----*/
//=============================================================================
//
// file :        Magnet.h
//
// description : Include file for the Magnet class
//
// project :     Magnet
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef Magnet_H
#define Magnet_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	Magnet.h

/**
 *  Magnet class description:
 *    Controls the magnet power supply via Beckhoff DAC
 */

namespace Magnet_ns
{
/*----- PROTECTED REGION ID(Magnet::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	Magnet::Additional Class Declarations

class Magnet : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(Magnet::Data Members) ENABLED START -----*/

//	Add your own data members
Tango::DeviceProxy *adsPtr;


/*----- PROTECTED REGION END -----*/	//	Magnet::Data Members

//	Device property data members
public:
	//	AmperePerVolt_polar:	Power Supply output current for 1 V programming voltage for polar magnet
	Tango::DevDouble	amperePerVolt_polar;
	//	AmperePerVolt_longitudinal:	Power Supply output current for 1 V programming voltage for longitudinal magnet
	Tango::DevDouble	amperePerVolt_longitudinal;
	//	AdsBridge:	Tango path to the ads bridge,e.g. 
	//  hpp-n42/beckhoff/adsBridge
	string	adsBridge;
	//	BeckhoffVariable_polar:	Variable name of the Beckhoff array that specifies the DAC to control the power supply for polar field
	string	beckhoffVariable_polar;
	//	BeckhoffVariable_longitudinal:	Variable name of the Beckhoff array that specifies the DAC to control the power supply fof longitudinal field
	string	beckhoffVariable_longitudinal;
	//	BeckhoffVariable_polarfield:	Variable name of the Beckhoff input channel of the polar Hall probe
	string	beckhoffVariable_polarfield;
	//	BeckhoffVariable_longitudinalfield:	Variable name of the Beckhoff input channel of the longitudinal Hall probe
	string	beckhoffVariable_longitudinalfield;
	//	HallSensitivity_polar:	Sensitivity of polar Hall probe, in Volt/Tesla
	Tango::DevDouble	hallSensitivity_polar;
	//	HallSensitivity_longitudinal:	Sensitivity of longitudinal Hall probe, in Volt/Tesla
	Tango::DevDouble	hallSensitivity_longitudinal;

//	Attribute data members
public:
	Tango::DevDouble	*attr_current_polar_read;
	Tango::DevDouble	*attr_current_longitudinal_read;
	Tango::DevDouble	*attr_field_polar_read;
	Tango::DevDouble	*attr_field_longitudinal_read;
	Tango::DevDouble	*attr_field_polar_corr_read;
	Tango::DevDouble	*attr_field_longitudinal_corr_read;
	Tango::DevDouble	*attr_corr_polar_read;
	Tango::DevDouble	*attr_corr_longitudinal_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Magnet(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	Magnet(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	Magnet(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~Magnet() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : Magnet::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : Magnet::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute current_polar related methods
 *	Description: Current in Ampere through polar coil
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_current_polar(Tango::Attribute &attr);
	virtual void write_current_polar(Tango::WAttribute &attr);
	virtual bool is_current_polar_allowed(Tango::AttReqType type);
/**
 *	Attribute current_longitudinal related methods
 *	Description: Current in Ampere through longitudinal coil
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_current_longitudinal(Tango::Attribute &attr);
	virtual void write_current_longitudinal(Tango::WAttribute &attr);
	virtual bool is_current_longitudinal_allowed(Tango::AttReqType type);
/**
 *	Attribute field_polar related methods
 *	Description: Magnetic field measured by Hall probe in polar geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_field_polar(Tango::Attribute &attr);
	virtual bool is_field_polar_allowed(Tango::AttReqType type);
/**
 *	Attribute field_longitudinal related methods
 *	Description: Magnetic field measured by Hall probe in longitudinal geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_field_longitudinal(Tango::Attribute &attr);
	virtual bool is_field_longitudinal_allowed(Tango::AttReqType type);
/**
 *	Attribute field_polar_corr related methods
 *	Description: Magnetic field measured by Hall probe in polar geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_field_polar_corr(Tango::Attribute &attr);
	virtual bool is_field_polar_corr_allowed(Tango::AttReqType type);
/**
 *	Attribute field_longitudinal_corr related methods
 *	Description: Magnetic field measured by Hall probe in longitudinal geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_field_longitudinal_corr(Tango::Attribute &attr);
	virtual bool is_field_longitudinal_corr_allowed(Tango::AttReqType type);
/**
 *	Attribute corr_polar related methods
 *	Description: Multiplies the measured field with a scaling factor corr_polar
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_corr_polar(Tango::Attribute &attr);
	virtual void write_corr_polar(Tango::WAttribute &attr);
	virtual bool is_corr_polar_allowed(Tango::AttReqType type);
/**
 *	Attribute corr_longitudinal related methods
 *	Description: Multiplies the measured field with a correction factor corr_longitudinal
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_corr_longitudinal(Tango::Attribute &attr);
	virtual void write_corr_longitudinal(Tango::WAttribute &attr);
	virtual bool is_corr_longitudinal_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : Magnet::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command SetZero_polar related method
	 *	Description: Set polar field to zero
	 *
	 */
	virtual void set_zero_polar();
	virtual bool is_SetZero_polar_allowed(const CORBA::Any &any);
	/**
	 *	Command SetZero_longitudinal related method
	 *	Description: Set longitudinal field to zero
	 *
	 */
	virtual void set_zero_longitudinal();
	virtual bool is_SetZero_longitudinal_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : Magnet::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(Magnet::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	Magnet::Additional Method prototypes
};

/*----- PROTECTED REGION ID(Magnet::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	Magnet::Additional Classes Definitions

}	//	End of namespace

#endif   //	Magnet_H
