/*----- PROTECTED REGION ID(MagnetClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        MagnetClass.cpp
//
// description : C++ source for the MagnetClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Magnet once per process.
//
// project :     Magnet
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <MagnetClass.h>

/*----- PROTECTED REGION END -----*/	//	MagnetClass.cpp

//-------------------------------------------------------------------
/**
 *	Create MagnetClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Magnet_class(const char *name) {
		return Magnet_ns::MagnetClass::init(name);
	}
}

namespace Magnet_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
MagnetClass *MagnetClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		MagnetClass::MagnetClass(string &s)
 * description : 	constructor for the MagnetClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
MagnetClass::MagnetClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering MagnetClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(MagnetClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::constructor

	cout2 << "Leaving MagnetClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		MagnetClass::~MagnetClass()
 * description : 	destructor for the MagnetClass
 */
//--------------------------------------------------------
MagnetClass::~MagnetClass()
{
	/*----- PROTECTED REGION ID(MagnetClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		MagnetClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
MagnetClass *MagnetClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new MagnetClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		MagnetClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
MagnetClass *MagnetClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		SetZero_polarClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetZero_polarClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetZero_polarClass::execute(): arrived" << endl;
	((static_cast<Magnet *>(device))->set_zero_polar());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetZero_longitudinalClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetZero_longitudinalClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetZero_longitudinalClass::execute(): arrived" << endl;
	((static_cast<Magnet *>(device))->set_zero_longitudinal());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : MagnetClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum MagnetClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : MagnetClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum MagnetClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : MagnetClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum MagnetClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : MagnetClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void MagnetClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "AmperePerVolt_polar";
	prop_desc = "Power Supply output current for 1 V programming voltage for polar magnet";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AmperePerVolt_longitudinal";
	prop_desc = "Power Supply output current for 1 V programming voltage for longitudinal magnet";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AdsBridge";
	prop_desc = "Tango path to the ads bridge,e.g. \nhpp-n42/beckhoff/adsBridge";
	prop_def  = "hpp-n42/beckhoff/adsBridge";
	vect_data.clear();
	vect_data.push_back("hpp-n42/beckhoff/adsBridge");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffVariable_polar";
	prop_desc = "Variable name of the Beckhoff array that specifies the DAC to control the power supply for polar field";
	prop_def  = "MAIN.AnalogOut2";
	vect_data.clear();
	vect_data.push_back("MAIN.AnalogOut2");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffVariable_longitudinal";
	prop_desc = "Variable name of the Beckhoff array that specifies the DAC to control the power supply fof longitudinal field";
	prop_def  = "MAIN.AnalogOut1";
	vect_data.clear();
	vect_data.push_back("MAIN.AnalogOut1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffVariable_polarfield";
	prop_desc = "Variable name of the Beckhoff input channel of the polar Hall probe";
	prop_def  = "MAIN.AnalogIn6";
	vect_data.clear();
	vect_data.push_back("MAIN.AnalogIn6");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffVariable_longitudinalfield";
	prop_desc = "Variable name of the Beckhoff input channel of the longitudinal Hall probe";
	prop_def  = "MAIN.AnalogIn5";
	vect_data.clear();
	vect_data.push_back("MAIN.AnalogIn5");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "HallSensitivity_polar";
	prop_desc = "Sensitivity of polar Hall probe, in Volt/Tesla";
	prop_def  = "5.0";
	vect_data.clear();
	vect_data.push_back("5.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "HallSensitivity_longitudinal";
	prop_desc = "Sensitivity of longitudinal Hall probe, in Volt/Tesla";
	prop_def  = "5.0";
	vect_data.clear();
	vect_data.push_back("5.0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : MagnetClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void MagnetClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Magnet");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Controls the magnet power supply via Beckhoff DAC");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("Magnet");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : MagnetClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void MagnetClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(MagnetClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Magnet(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Magnet *dev = static_cast<Magnet *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(MagnetClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MagnetClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void MagnetClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(MagnetClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::attribute_factory_before
	//	Attribute : current_polar
	current_polarAttrib	*current_polar = new current_polarAttrib();
	Tango::UserDefaultAttrProp	current_polar_prop;
	current_polar_prop.set_description("Current in Ampere through polar coil");
	current_polar_prop.set_label("Current (polar)");
	current_polar_prop.set_unit("A");
	//	standard_unit	not set for current_polar
	//	display_unit	not set for current_polar
	//	format	not set for current_polar
	//	max_value	not set for current_polar
	//	min_value	not set for current_polar
	//	max_alarm	not set for current_polar
	//	min_alarm	not set for current_polar
	//	max_warning	not set for current_polar
	//	min_warning	not set for current_polar
	//	delta_t	not set for current_polar
	//	delta_val	not set for current_polar
	
	current_polar->set_default_properties(current_polar_prop);
	//	Not Polled
	current_polar->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(current_polar);

	//	Attribute : current_longitudinal
	current_longitudinalAttrib	*current_longitudinal = new current_longitudinalAttrib();
	Tango::UserDefaultAttrProp	current_longitudinal_prop;
	current_longitudinal_prop.set_description("Current in Ampere through longitudinal coil");
	current_longitudinal_prop.set_label("Current (longitudinal)");
	current_longitudinal_prop.set_unit("A");
	//	standard_unit	not set for current_longitudinal
	//	display_unit	not set for current_longitudinal
	//	format	not set for current_longitudinal
	//	max_value	not set for current_longitudinal
	//	min_value	not set for current_longitudinal
	//	max_alarm	not set for current_longitudinal
	//	min_alarm	not set for current_longitudinal
	//	max_warning	not set for current_longitudinal
	//	min_warning	not set for current_longitudinal
	//	delta_t	not set for current_longitudinal
	//	delta_val	not set for current_longitudinal
	
	current_longitudinal->set_default_properties(current_longitudinal_prop);
	//	Not Polled
	current_longitudinal->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(current_longitudinal);

	//	Attribute : field_polar
	field_polarAttrib	*field_polar = new field_polarAttrib();
	Tango::UserDefaultAttrProp	field_polar_prop;
	field_polar_prop.set_description("Magnetic field measured by Hall probe in polar geometry");
	field_polar_prop.set_label("Polar field");
	field_polar_prop.set_unit("mT");
	//	standard_unit	not set for field_polar
	//	display_unit	not set for field_polar
	//	format	not set for field_polar
	//	max_value	not set for field_polar
	//	min_value	not set for field_polar
	//	max_alarm	not set for field_polar
	//	min_alarm	not set for field_polar
	//	max_warning	not set for field_polar
	//	min_warning	not set for field_polar
	//	delta_t	not set for field_polar
	//	delta_val	not set for field_polar
	
	field_polar->set_default_properties(field_polar_prop);
	//	Not Polled
	field_polar->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(field_polar);

	//	Attribute : field_longitudinal
	field_longitudinalAttrib	*field_longitudinal = new field_longitudinalAttrib();
	Tango::UserDefaultAttrProp	field_longitudinal_prop;
	field_longitudinal_prop.set_description("Magnetic field measured by Hall probe in longitudinal geometry");
	field_longitudinal_prop.set_label("Longitudinal field");
	field_longitudinal_prop.set_unit("mT");
	//	standard_unit	not set for field_longitudinal
	//	display_unit	not set for field_longitudinal
	//	format	not set for field_longitudinal
	//	max_value	not set for field_longitudinal
	//	min_value	not set for field_longitudinal
	//	max_alarm	not set for field_longitudinal
	//	min_alarm	not set for field_longitudinal
	//	max_warning	not set for field_longitudinal
	//	min_warning	not set for field_longitudinal
	//	delta_t	not set for field_longitudinal
	//	delta_val	not set for field_longitudinal
	
	field_longitudinal->set_default_properties(field_longitudinal_prop);
	//	Not Polled
	field_longitudinal->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(field_longitudinal);

	//	Attribute : field_polar_corr
	field_polar_corrAttrib	*field_polar_corr = new field_polar_corrAttrib();
	Tango::UserDefaultAttrProp	field_polar_corr_prop;
	field_polar_corr_prop.set_description("Magnetic field measured by Hall probe in polar geometry");
	field_polar_corr_prop.set_label("Polar field (corrected)");
	field_polar_corr_prop.set_unit("mT");
	//	standard_unit	not set for field_polar_corr
	//	display_unit	not set for field_polar_corr
	//	format	not set for field_polar_corr
	//	max_value	not set for field_polar_corr
	//	min_value	not set for field_polar_corr
	//	max_alarm	not set for field_polar_corr
	//	min_alarm	not set for field_polar_corr
	//	max_warning	not set for field_polar_corr
	//	min_warning	not set for field_polar_corr
	//	delta_t	not set for field_polar_corr
	//	delta_val	not set for field_polar_corr
	
	field_polar_corr->set_default_properties(field_polar_corr_prop);
	//	Not Polled
	field_polar_corr->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(field_polar_corr);

	//	Attribute : field_longitudinal_corr
	field_longitudinal_corrAttrib	*field_longitudinal_corr = new field_longitudinal_corrAttrib();
	Tango::UserDefaultAttrProp	field_longitudinal_corr_prop;
	field_longitudinal_corr_prop.set_description("Magnetic field measured by Hall probe in longitudinal geometry");
	field_longitudinal_corr_prop.set_label("Longitudinal field (corrected)");
	field_longitudinal_corr_prop.set_unit("mT");
	//	standard_unit	not set for field_longitudinal_corr
	//	display_unit	not set for field_longitudinal_corr
	//	format	not set for field_longitudinal_corr
	//	max_value	not set for field_longitudinal_corr
	//	min_value	not set for field_longitudinal_corr
	//	max_alarm	not set for field_longitudinal_corr
	//	min_alarm	not set for field_longitudinal_corr
	//	max_warning	not set for field_longitudinal_corr
	//	min_warning	not set for field_longitudinal_corr
	//	delta_t	not set for field_longitudinal_corr
	//	delta_val	not set for field_longitudinal_corr
	
	field_longitudinal_corr->set_default_properties(field_longitudinal_corr_prop);
	//	Not Polled
	field_longitudinal_corr->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(field_longitudinal_corr);

	//	Attribute : corr_polar
	corr_polarAttrib	*corr_polar = new corr_polarAttrib();
	Tango::UserDefaultAttrProp	corr_polar_prop;
	corr_polar_prop.set_description("Multiplies the measured field with a scaling factor corr_polar");
	corr_polar_prop.set_label("polar correction factor");
	//	unit	not set for corr_polar
	//	standard_unit	not set for corr_polar
	//	display_unit	not set for corr_polar
	//	format	not set for corr_polar
	//	max_value	not set for corr_polar
	//	min_value	not set for corr_polar
	//	max_alarm	not set for corr_polar
	//	min_alarm	not set for corr_polar
	//	max_warning	not set for corr_polar
	//	min_warning	not set for corr_polar
	//	delta_t	not set for corr_polar
	//	delta_val	not set for corr_polar
	
	corr_polar->set_default_properties(corr_polar_prop);
	//	Not Polled
	corr_polar->set_disp_level(Tango::OPERATOR);
	corr_polar->set_memorized();
	corr_polar->set_memorized_init(true);
	att_list.push_back(corr_polar);

	//	Attribute : corr_longitudinal
	corr_longitudinalAttrib	*corr_longitudinal = new corr_longitudinalAttrib();
	Tango::UserDefaultAttrProp	corr_longitudinal_prop;
	corr_longitudinal_prop.set_description("Multiplies the measured field with a correction factor corr_longitudinal");
	corr_longitudinal_prop.set_label("longitudinal correction factor");
	//	unit	not set for corr_longitudinal
	//	standard_unit	not set for corr_longitudinal
	//	display_unit	not set for corr_longitudinal
	//	format	not set for corr_longitudinal
	//	max_value	not set for corr_longitudinal
	//	min_value	not set for corr_longitudinal
	//	max_alarm	not set for corr_longitudinal
	//	min_alarm	not set for corr_longitudinal
	//	max_warning	not set for corr_longitudinal
	//	min_warning	not set for corr_longitudinal
	//	delta_t	not set for corr_longitudinal
	//	delta_val	not set for corr_longitudinal
	
	corr_longitudinal->set_default_properties(corr_longitudinal_prop);
	//	Not Polled
	corr_longitudinal->set_disp_level(Tango::OPERATOR);
	corr_longitudinal->set_memorized();
	corr_longitudinal->set_memorized_init(true);
	att_list.push_back(corr_longitudinal);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(MagnetClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : MagnetClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void MagnetClass::command_factory()
{
	/*----- PROTECTED REGION ID(MagnetClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::command_factory_before


	//	Command SetZero_polar
	SetZero_polarClass	*pSetZero_polarCmd =
		new SetZero_polarClass("SetZero_polar",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetZero_polarCmd);

	//	Command SetZero_longitudinal
	SetZero_longitudinalClass	*pSetZero_longitudinalCmd =
		new SetZero_longitudinalClass("SetZero_longitudinal",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetZero_longitudinalCmd);

	/*----- PROTECTED REGION ID(MagnetClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		MagnetClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void MagnetClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(MagnetClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		MagnetClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void MagnetClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Magnet *dev = static_cast<Magnet *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(MagnetClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	MagnetClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : MagnetClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *MagnetClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(MagnetClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	MagnetClass::Additional Methods
} //	namespace
