/*----- PROTECTED REGION ID(Magnet.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Magnet.cpp
//
// description : C++ source for the Magnet class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               Magnet are implemented in this file.
//
// project :     Magnet
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <Magnet.h>
#include <MagnetClass.h>

/*----- PROTECTED REGION END -----*/	//	Magnet.cpp

/**
 *  Magnet class description:
 *    Controls the magnet power supply via Beckhoff DAC
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name          |  Method name
//================================================================
//  State                 |  Inherited (no method)
//  Status                |  Inherited (no method)
//  SetZero_polar         |  set_zero_polar
//  SetZero_longitudinal  |  set_zero_longitudinal
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  current_polar            |  Tango::DevDouble	Scalar
//  current_longitudinal     |  Tango::DevDouble	Scalar
//  field_polar              |  Tango::DevDouble	Scalar
//  field_longitudinal       |  Tango::DevDouble	Scalar
//  field_polar_corr         |  Tango::DevDouble	Scalar
//  field_longitudinal_corr  |  Tango::DevDouble	Scalar
//  corr_polar               |  Tango::DevDouble	Scalar
//  corr_longitudinal        |  Tango::DevDouble	Scalar
//================================================================

namespace Magnet_ns
{
/*----- PROTECTED REGION ID(Magnet::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	Magnet::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : Magnet::Magnet()
 *	Description : Constructors for a Tango device
 *                implementing the classMagnet
 */
//--------------------------------------------------------
Magnet::Magnet(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(Magnet::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::constructor_1
}
//--------------------------------------------------------
Magnet::Magnet(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(Magnet::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::constructor_2
}
//--------------------------------------------------------
Magnet::Magnet(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(Magnet::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : Magnet::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void Magnet::delete_device()
{
	DEBUG_STREAM << "Magnet::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(Magnet::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	delete[] adsPtr;

	/*----- PROTECTED REGION END -----*/	//	Magnet::delete_device
	delete[] attr_current_polar_read;
	delete[] attr_current_longitudinal_read;
	delete[] attr_field_polar_read;
	delete[] attr_field_longitudinal_read;
	delete[] attr_field_polar_corr_read;
	delete[] attr_field_longitudinal_corr_read;
	delete[] attr_corr_polar_read;
	delete[] attr_corr_longitudinal_read;
}

//--------------------------------------------------------
/**
 *	Method      : Magnet::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void Magnet::init_device()
{
	DEBUG_STREAM << "Magnet::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(Magnet::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_current_polar_read = new Tango::DevDouble[1];
	attr_current_longitudinal_read = new Tango::DevDouble[1];
	attr_field_polar_read = new Tango::DevDouble[1];
	attr_field_longitudinal_read = new Tango::DevDouble[1];
	attr_field_polar_corr_read = new Tango::DevDouble[1];
	attr_field_longitudinal_corr_read = new Tango::DevDouble[1];
	attr_corr_polar_read = new Tango::DevDouble[1];
	attr_corr_longitudinal_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(Magnet::init_device) ENABLED START -----*/
	
	//	Initialize device

	// see declaration in header file: 
	// Tango::DeviceProxy *adsPtr;	
	adsPtr = new Tango::DeviceProxy(adsBridge);
	
	INFO_STREAM << "Magnet::init_device() through Proxy " + adsBridge << endl;

	set_state(Tango::ON);
	set_status("Ready to apply magnet current through Proxy " + adsBridge);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::init_device
}

//--------------------------------------------------------
/**
 *	Method      : Magnet::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void Magnet::get_device_property()
{
	/*----- PROTECTED REGION ID(Magnet::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("AmperePerVolt_polar"));
	dev_prop.push_back(Tango::DbDatum("AmperePerVolt_longitudinal"));
	dev_prop.push_back(Tango::DbDatum("AdsBridge"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffVariable_polar"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffVariable_longitudinal"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffVariable_polarfield"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffVariable_longitudinalfield"));
	dev_prop.push_back(Tango::DbDatum("HallSensitivity_polar"));
	dev_prop.push_back(Tango::DbDatum("HallSensitivity_longitudinal"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on MagnetClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		MagnetClass	*ds_class =
			(static_cast<MagnetClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize AmperePerVolt_polar from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  amperePerVolt_polar;
		else {
			//	Try to initialize AmperePerVolt_polar from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  amperePerVolt_polar;
		}
		//	And try to extract AmperePerVolt_polar value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  amperePerVolt_polar;

		//	Try to initialize AmperePerVolt_longitudinal from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  amperePerVolt_longitudinal;
		else {
			//	Try to initialize AmperePerVolt_longitudinal from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  amperePerVolt_longitudinal;
		}
		//	And try to extract AmperePerVolt_longitudinal value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  amperePerVolt_longitudinal;

		//	Try to initialize AdsBridge from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  adsBridge;
		else {
			//	Try to initialize AdsBridge from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  adsBridge;
		}
		//	And try to extract AdsBridge value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  adsBridge;

		//	Try to initialize BeckhoffVariable_polar from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffVariable_polar;
		else {
			//	Try to initialize BeckhoffVariable_polar from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffVariable_polar;
		}
		//	And try to extract BeckhoffVariable_polar value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffVariable_polar;

		//	Try to initialize BeckhoffVariable_longitudinal from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffVariable_longitudinal;
		else {
			//	Try to initialize BeckhoffVariable_longitudinal from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffVariable_longitudinal;
		}
		//	And try to extract BeckhoffVariable_longitudinal value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffVariable_longitudinal;

		//	Try to initialize BeckhoffVariable_polarfield from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffVariable_polarfield;
		else {
			//	Try to initialize BeckhoffVariable_polarfield from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffVariable_polarfield;
		}
		//	And try to extract BeckhoffVariable_polarfield value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffVariable_polarfield;

		//	Try to initialize BeckhoffVariable_longitudinalfield from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffVariable_longitudinalfield;
		else {
			//	Try to initialize BeckhoffVariable_longitudinalfield from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffVariable_longitudinalfield;
		}
		//	And try to extract BeckhoffVariable_longitudinalfield value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffVariable_longitudinalfield;

		//	Try to initialize HallSensitivity_polar from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  hallSensitivity_polar;
		else {
			//	Try to initialize HallSensitivity_polar from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  hallSensitivity_polar;
		}
		//	And try to extract HallSensitivity_polar value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  hallSensitivity_polar;

		//	Try to initialize HallSensitivity_longitudinal from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  hallSensitivity_longitudinal;
		else {
			//	Try to initialize HallSensitivity_longitudinal from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  hallSensitivity_longitudinal;
		}
		//	And try to extract HallSensitivity_longitudinal value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  hallSensitivity_longitudinal;

	}

	/*----- PROTECTED REGION ID(Magnet::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method      : Magnet::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void Magnet::always_executed_hook()
{
	INFO_STREAM << "Magnet::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(Magnet::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : Magnet::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void Magnet::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Magnet::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : Magnet::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void Magnet::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "Magnet::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute current_polar related method
 *	Description: Current in Ampere through polar coil
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_current_polar(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_current_polar(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_current_polar) ENABLED START -----*/
	
	// readout DAC state
	Tango::DeviceData dev_value;
	string dev_command("ReadReal");
	string dev_argument(beckhoffVariable_polar);
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	dev_result = adsPtr->command_inout(dev_command, dev_value);

	//	Set the attribute value
	dev_result >> attr_current_polar_read[0];
	attr_current_polar_read[0] *= amperePerVolt_polar;
	attr.set_value(attr_current_polar_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_current_polar
}
//--------------------------------------------------------
/**
 *	Write attribute current_polar related method
 *	Description: Current in Ampere through polar coil
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::write_current_polar(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Magnet::write_current_polar(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Magnet::write_current_polar) ENABLED START -----*/

	//attr_current_polar_read[0] = w_val;
	
	w_val = w_val/amperePerVolt_polar;

	Tango::DeviceData dev_value;
	string dev_argument(beckhoffVariable_polar+"="+to_string(w_val)); // to_string should give 6 decimal digits
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	string dev_command("WriteReal");
	
	dev_result = adsPtr->command_inout(dev_command,dev_value);



	
	/*----- PROTECTED REGION END -----*/	//	Magnet::write_current_polar
}
//--------------------------------------------------------
/**
 *	Read attribute current_longitudinal related method
 *	Description: Current in Ampere through longitudinal coil
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_current_longitudinal(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_current_longitudinal(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_current_longitudinal) ENABLED START -----*/

	// readout DAC state
	Tango::DeviceData dev_value;
	string dev_command("ReadReal");
	string dev_argument(beckhoffVariable_longitudinal);
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	dev_result = adsPtr->command_inout(dev_command, dev_value);

	//	Set the attribute value
	dev_result >> attr_current_longitudinal_read[0];
	attr_current_longitudinal_read[0] *= amperePerVolt_longitudinal;
	attr.set_value(attr_current_longitudinal_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_current_longitudinal
}
//--------------------------------------------------------
/**
 *	Write attribute current_longitudinal related method
 *	Description: Current in Ampere through longitudinal coil
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::write_current_longitudinal(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Magnet::write_current_longitudinal(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Magnet::write_current_longitudinal) ENABLED START -----*/

	//attr_current_longitudinal_read[0] = w_val;
	
	w_val = w_val/amperePerVolt_longitudinal;

	Tango::DeviceData dev_value;
	string dev_argument(beckhoffVariable_longitudinal+"="+to_string(w_val)); // to_string should give 6 decimal digits
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	string dev_command("WriteReal");
	
	dev_result = adsPtr->command_inout(dev_command,dev_value);

	/*----- PROTECTED REGION END -----*/	//	Magnet::write_current_longitudinal
}
//--------------------------------------------------------
/**
 *	Read attribute field_polar related method
 *	Description: Magnetic field measured by Hall probe in polar geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_field_polar(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_field_polar(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_field_polar) ENABLED START -----*/
	
	Tango::DeviceData dev_value;
	string dev_command("ReadReal");
	string dev_argument(beckhoffVariable_polarfield);
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	dev_result = adsPtr->command_inout(dev_command, dev_value);

	dev_result >> attr_field_polar_read[0];
	//TODO include offset of probe
	attr_field_polar_read[0] /= hallSensitivity_polar;
	attr_field_polar_read[0] *= 1000;  // for mTesla
	
	attr.set_value(attr_field_polar_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_field_polar
}
//--------------------------------------------------------
/**
 *	Read attribute field_longitudinal related method
 *	Description: Magnetic field measured by Hall probe in longitudinal geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_field_longitudinal(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_field_longitudinal(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_field_longitudinal) ENABLED START -----*/
	
	Tango::DeviceData dev_value;
	string dev_command("ReadReal");
	string dev_argument(beckhoffVariable_longitudinalfield);
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	dev_result = adsPtr->command_inout(dev_command, dev_value);

	dev_result >> attr_field_longitudinal_read[0];
	//TODO include offset of probe
	attr_field_longitudinal_read[0] /= hallSensitivity_longitudinal;
	attr_field_longitudinal_read[0] *= 1000;  // for mTesla
	
	attr.set_value(attr_field_longitudinal_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_field_longitudinal
}
//--------------------------------------------------------
/**
 *	Read attribute field_polar_corr related method
 *	Description: Magnetic field measured by Hall probe in polar geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_field_polar_corr(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_field_polar_corr(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_field_polar_corr) ENABLED START -----*/
	
    attr_field_polar_corr_read[0] = attr_field_polar_read[0] * attr_corr_polar_read[0];
	attr.set_value(attr_field_polar_corr_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_field_polar_corr
}
//--------------------------------------------------------
/**
 *	Read attribute field_longitudinal_corr related method
 *	Description: Magnetic field measured by Hall probe in longitudinal geometry
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_field_longitudinal_corr(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_field_longitudinal_corr(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_field_longitudinal_corr) ENABLED START -----*/
	
	attr_field_longitudinal_corr_read[0] = attr_field_longitudinal_read[0] * attr_corr_longitudinal_read[0];
	attr.set_value(attr_field_longitudinal_corr_read);

	/*----- PROTECTED REGION END -----*/	//	Magnet::read_field_longitudinal_corr
}
//--------------------------------------------------------
/**
 *	Read attribute corr_polar related method
 *	Description: Multiplies the measured field with a scaling factor corr_polar
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_corr_polar(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_corr_polar(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_corr_polar) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_corr_polar_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_corr_polar
}
//--------------------------------------------------------
/**
 *	Write attribute corr_polar related method
 *	Description: Multiplies the measured field with a scaling factor corr_polar
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::write_corr_polar(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Magnet::write_corr_polar(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Magnet::write_corr_polar) ENABLED START -----*/
	attr_corr_polar_read[0] = w_val;
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::write_corr_polar
}
//--------------------------------------------------------
/**
 *	Read attribute corr_longitudinal related method
 *	Description: Multiplies the measured field with a correction factor corr_longitudinal
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::read_corr_longitudinal(Tango::Attribute &attr)
{
	DEBUG_STREAM << "Magnet::read_corr_longitudinal(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(Magnet::read_corr_longitudinal) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_corr_longitudinal_read);
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::read_corr_longitudinal
}
//--------------------------------------------------------
/**
 *	Write attribute corr_longitudinal related method
 *	Description: Multiplies the measured field with a correction factor corr_longitudinal
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void Magnet::write_corr_longitudinal(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "Magnet::write_corr_longitudinal(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(Magnet::write_corr_longitudinal) ENABLED START -----*/
	attr_corr_longitudinal_read[0] = w_val;
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::write_corr_longitudinal
}

//--------------------------------------------------------
/**
 *	Method      : Magnet::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void Magnet::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(Magnet::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command SetZero_polar related method
 *	Description: Set polar field to zero
 *
 */
//--------------------------------------------------------
void Magnet::set_zero_polar()
{
	DEBUG_STREAM << "Magnet::SetZero_polar()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Magnet::set_zero_polar) ENABLED START -----*/
	
	Tango::DeviceData dev_value;
	string dev_argument(beckhoffVariable_polar+"=0.0"); 
	dev_value << dev_argument; 
	Tango::DeviceData dev_result;
	string dev_command("WriteReal");
	
	dev_result = adsPtr->command_inout(dev_command,dev_value);
	attr_current_polar_read[0] = 0.0;
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::set_zero_polar
}
//--------------------------------------------------------
/**
 *	Command SetZero_longitudinal related method
 *	Description: Set longitudinal field to zero
 *
 */
//--------------------------------------------------------
void Magnet::set_zero_longitudinal()
{
	DEBUG_STREAM << "Magnet::SetZero_longitudinal()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(Magnet::set_zero_longitudinal) ENABLED START -----*/
	
	Tango::DeviceData dev_value;
	string dev_argument(beckhoffVariable_longitudinal+"=0.0"); 
	dev_value << dev_argument;
	Tango::DeviceData dev_result;
	string dev_command("WriteReal");
	 	
	dev_result = adsPtr->command_inout(dev_command,dev_value);
	attr_current_longitudinal_read[0] = 0.0;
	
	/*----- PROTECTED REGION END -----*/	//	Magnet::set_zero_longitudinal
}

/*----- PROTECTED REGION ID(Magnet::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	Magnet::namespace_ending
} //	namespace
