/*----- PROTECTED REGION ID(SmaractClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        SmaractClass.cpp
//
// description : C++ source for the SmaractClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the Smaract once per process.
//
// project :     Smaract Piezo Motor
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SmaractClass.h>

/*----- PROTECTED REGION END -----*/	//	SmaractClass.cpp

//-------------------------------------------------------------------
/**
 *	Create SmaractClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_Smaract_class(const char *name) {
		return Smaract_ns::SmaractClass::init(name);
	}
}

namespace Smaract_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
SmaractClass *SmaractClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		SmaractClass::SmaractClass(string &s)
 * description : 	constructor for the SmaractClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
SmaractClass::SmaractClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering SmaractClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(SmaractClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::constructor

	cout2 << "Leaving SmaractClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		SmaractClass::~SmaractClass()
 * description : 	destructor for the SmaractClass
 */
//--------------------------------------------------------
SmaractClass::~SmaractClass()
{
	/*----- PROTECTED REGION ID(SmaractClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		SmaractClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
SmaractClass *SmaractClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new SmaractClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		SmaractClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
SmaractClass *SmaractClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		OpenSmaractClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OpenSmaractClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OpenSmaractClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->open_smaract());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		CloseSmaractClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CloseSmaractClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "CloseSmaractClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->close_smaract());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		FindReferenceMarkClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *FindReferenceMarkClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "FindReferenceMarkClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->find_reference_mark());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AbortClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AbortClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "AbortClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->abort());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AutoTilt_onClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AutoTilt_onClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "AutoTilt_onClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->auto_tilt_on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AutoTilt_offClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AutoTilt_offClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "AutoTilt_offClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->auto_tilt_off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AutoTilt_SetOriginClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AutoTilt_SetOriginClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "AutoTilt_SetOriginClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->auto_tilt__set_origin());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AutoTilt_SetHorizontalSlopeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AutoTilt_SetHorizontalSlopeClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "AutoTilt_SetHorizontalSlopeClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->auto_tilt__set_horizontal_slope());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AutoTilt_SetVerticalSlopeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AutoTilt_SetVerticalSlopeClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "AutoTilt_SetVerticalSlopeClass::execute(): arrived" << endl;
	((static_cast<Smaract *>(device))->auto_tilt__set_vertical_slope());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : SmaractClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum SmaractClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SmaractClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum SmaractClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SmaractClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum SmaractClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SmaractClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void SmaractClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "SmaractIdentifier";
	prop_desc = "Identifier string for the Smaract controller on the network. The default reflects the factory setting.";
	prop_def  = "network:192.168.1.200:5000";
	vect_data.clear();
	vect_data.push_back("network:192.168.1.200:5000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "SmaractOpenCommand";
	prop_desc = "Command to pass to the Smaract MCS controller during opening";
	prop_def  = "sync,open-timeout 2000";
	vect_data.clear();
	vect_data.push_back("sync,open-timeout 2000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "HoldTime";
	prop_desc = "Stage hold time in ms, range 0-60000. A 0 deactivates this feature, a value of 60000 is infinite.";
	prop_def  = "0";
	vect_data.clear();
	vect_data.push_back("0");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AutotiltMaxCorrection";
	prop_desc = "Maximum correction in microns of focus position for Autotilt";
	prop_def  = "100";
	vect_data.clear();
	vect_data.push_back("100");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : SmaractClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void SmaractClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Smaract Piezo Motor");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Driver for a Smaract Piezo using the MCS controller connected via Ethernet");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : SmaractClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void SmaractClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(SmaractClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new Smaract(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		Smaract *dev = static_cast<Smaract *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(SmaractClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SmaractClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void SmaractClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(SmaractClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::attribute_factory_before
	//	Attribute : position0
	position0Attrib	*position0 = new position0Attrib();
	Tango::UserDefaultAttrProp	position0_prop;
	position0_prop.set_description("Position 0 (microscope axis) in micrometer");
	position0_prop.set_label("Position 0");
	position0_prop.set_unit("um");
	//	standard_unit	not set for position0
	//	display_unit	not set for position0
	//	format	not set for position0
	position0_prop.set_max_value("7000");
	position0_prop.set_min_value("-7000");
	//	max_alarm	not set for position0
	//	min_alarm	not set for position0
	//	max_warning	not set for position0
	//	min_warning	not set for position0
	//	delta_t	not set for position0
	//	delta_val	not set for position0
	
	position0->set_default_properties(position0_prop);
	//	Not Polled
	position0->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(position0);

	//	Attribute : position1
	position1Attrib	*position1 = new position1Attrib();
	Tango::UserDefaultAttrProp	position1_prop;
	position1_prop.set_description("Position 1 (left-right) in micrometer");
	position1_prop.set_label("Position 1");
	position1_prop.set_unit("um");
	//	standard_unit	not set for position1
	//	display_unit	not set for position1
	//	format	not set for position1
	position1_prop.set_max_value("7000");
	position1_prop.set_min_value("-7000");
	//	max_alarm	not set for position1
	//	min_alarm	not set for position1
	//	max_warning	not set for position1
	//	min_warning	not set for position1
	//	delta_t	not set for position1
	//	delta_val	not set for position1
	
	position1->set_default_properties(position1_prop);
	//	Not Polled
	position1->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(position1);

	//	Attribute : position2
	position2Attrib	*position2 = new position2Attrib();
	Tango::UserDefaultAttrProp	position2_prop;
	position2_prop.set_description("Position 2 (up-down) in micrometer");
	position2_prop.set_label("Position 2");
	position2_prop.set_unit("um");
	//	standard_unit	not set for position2
	//	display_unit	not set for position2
	//	format	not set for position2
	position2_prop.set_max_value("7000");
	position2_prop.set_min_value("-7000");
	//	max_alarm	not set for position2
	//	min_alarm	not set for position2
	//	max_warning	not set for position2
	//	min_warning	not set for position2
	//	delta_t	not set for position2
	//	delta_val	not set for position2
	
	position2->set_default_properties(position2_prop);
	//	Not Polled
	position2->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(position2);

	//	Attribute : autotilt_slope_h
	autotilt_slope_hAttrib	*autotilt_slope_h = new autotilt_slope_hAttrib();
	Tango::UserDefaultAttrProp	autotilt_slope_h_prop;
	//	description	not set for autotilt_slope_h
	//	label	not set for autotilt_slope_h
	//	unit	not set for autotilt_slope_h
	//	standard_unit	not set for autotilt_slope_h
	//	display_unit	not set for autotilt_slope_h
	//	format	not set for autotilt_slope_h
	//	max_value	not set for autotilt_slope_h
	//	min_value	not set for autotilt_slope_h
	//	max_alarm	not set for autotilt_slope_h
	//	min_alarm	not set for autotilt_slope_h
	//	max_warning	not set for autotilt_slope_h
	//	min_warning	not set for autotilt_slope_h
	//	delta_t	not set for autotilt_slope_h
	//	delta_val	not set for autotilt_slope_h
	
	autotilt_slope_h->set_default_properties(autotilt_slope_h_prop);
	//	Not Polled
	autotilt_slope_h->set_disp_level(Tango::OPERATOR);
	autotilt_slope_h->set_memorized();
	autotilt_slope_h->set_memorized_init(true);
	att_list.push_back(autotilt_slope_h);

	//	Attribute : autotilt_slope_v
	autotilt_slope_vAttrib	*autotilt_slope_v = new autotilt_slope_vAttrib();
	Tango::UserDefaultAttrProp	autotilt_slope_v_prop;
	//	description	not set for autotilt_slope_v
	//	label	not set for autotilt_slope_v
	//	unit	not set for autotilt_slope_v
	//	standard_unit	not set for autotilt_slope_v
	//	display_unit	not set for autotilt_slope_v
	//	format	not set for autotilt_slope_v
	//	max_value	not set for autotilt_slope_v
	//	min_value	not set for autotilt_slope_v
	//	max_alarm	not set for autotilt_slope_v
	//	min_alarm	not set for autotilt_slope_v
	//	max_warning	not set for autotilt_slope_v
	//	min_warning	not set for autotilt_slope_v
	//	delta_t	not set for autotilt_slope_v
	//	delta_val	not set for autotilt_slope_v
	
	autotilt_slope_v->set_default_properties(autotilt_slope_v_prop);
	//	Not Polled
	autotilt_slope_v->set_disp_level(Tango::OPERATOR);
	autotilt_slope_v->set_memorized();
	autotilt_slope_v->set_memorized_init(true);
	att_list.push_back(autotilt_slope_v);

	//	Attribute : autotilt
	autotiltAttrib	*autotilt = new autotiltAttrib();
	Tango::UserDefaultAttrProp	autotilt_prop;
	//	description	not set for autotilt
	//	label	not set for autotilt
	//	unit	not set for autotilt
	//	standard_unit	not set for autotilt
	//	display_unit	not set for autotilt
	//	format	not set for autotilt
	//	max_value	not set for autotilt
	//	min_value	not set for autotilt
	//	max_alarm	not set for autotilt
	//	min_alarm	not set for autotilt
	//	max_warning	not set for autotilt
	//	min_warning	not set for autotilt
	//	delta_t	not set for autotilt
	//	delta_val	not set for autotilt
	
	autotilt->set_default_properties(autotilt_prop);
	//	Not Polled
	autotilt->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(autotilt);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(SmaractClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SmaractClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void SmaractClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(SmaractClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::pipe_factory_before
	/*----- PROTECTED REGION ID(SmaractClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SmaractClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void SmaractClass::command_factory()
{
	/*----- PROTECTED REGION ID(SmaractClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::command_factory_before


	//	Command OpenSmaract
	OpenSmaractClass	*pOpenSmaractCmd =
		new OpenSmaractClass("OpenSmaract",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOpenSmaractCmd);

	//	Command CloseSmaract
	CloseSmaractClass	*pCloseSmaractCmd =
		new CloseSmaractClass("CloseSmaract",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pCloseSmaractCmd);

	//	Command FindReferenceMark
	FindReferenceMarkClass	*pFindReferenceMarkCmd =
		new FindReferenceMarkClass("FindReferenceMark",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pFindReferenceMarkCmd);

	//	Command Abort
	AbortClass	*pAbortCmd =
		new AbortClass("Abort",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAbortCmd);

	//	Command AutoTilt_on
	AutoTilt_onClass	*pAutoTilt_onCmd =
		new AutoTilt_onClass("AutoTilt_on",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAutoTilt_onCmd);

	//	Command AutoTilt_off
	AutoTilt_offClass	*pAutoTilt_offCmd =
		new AutoTilt_offClass("AutoTilt_off",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAutoTilt_offCmd);

	//	Command AutoTilt_SetOrigin
	AutoTilt_SetOriginClass	*pAutoTilt_SetOriginCmd =
		new AutoTilt_SetOriginClass("AutoTilt_SetOrigin",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAutoTilt_SetOriginCmd);

	//	Command AutoTilt_SetHorizontalSlope
	AutoTilt_SetHorizontalSlopeClass	*pAutoTilt_SetHorizontalSlopeCmd =
		new AutoTilt_SetHorizontalSlopeClass("AutoTilt_SetHorizontalSlope",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAutoTilt_SetHorizontalSlopeCmd);

	//	Command AutoTilt_SetVerticalSlope
	AutoTilt_SetVerticalSlopeClass	*pAutoTilt_SetVerticalSlopeCmd =
		new AutoTilt_SetVerticalSlopeClass("AutoTilt_SetVerticalSlope",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAutoTilt_SetVerticalSlopeCmd);

	/*----- PROTECTED REGION ID(SmaractClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		SmaractClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void SmaractClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(SmaractClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		SmaractClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void SmaractClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		Smaract *dev = static_cast<Smaract *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(SmaractClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmaractClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : SmaractClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *SmaractClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(SmaractClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	SmaractClass::Additional Methods
} //	namespace
