/*----- PROTECTED REGION ID(Socket::ClassFactory.cpp) ENABLED START -----*/
static const char *RcsId = "$Header: /cvsroot-fuse/tango-ds/Communication/Socket/ClassFactory.cpp,v 1.1.1.1 2007/01/12 10:07:43 pascal_verdier Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: pascal_verdier $
//
// $Revision: 1.1.1.1 $
//
// $Log: ClassFactory.cpp,v $
// Revision 1.1.1.1  2007/01/12 10:07:43  pascal_verdier
// Initial Revision
//
// Revision 1.1.1.1  2005/07/12 06:59:46  peru
// Imported using TkCVS
//
// Revision 1.1.1.1  2005/07/12 06:16:03  peru
// Imported using TkCVS
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================


#include <tango.h>
#include <SocketClass.h>

/**
 *	Create SocketClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{

	add_class(Socket_ns::SocketClass::init("Socket"));

}
/*----- PROTECTED REGION END -----*/	//	Socket::ClassFactory.cpp
