/*----- PROTECTED REGION ID(SocketStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SocketStateMachine.cpp
//
// description : C++ source for the «name» and its alowed
//               methods for commands and attributes
//
// project :     Socket.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================



#include <Socket.h>
#include <SocketClass.h>

/*----- PROTECTED REGION END -----*/	//	Socket::SocketStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  Normal state when everything is OK.
//  OFF     |  Disconnected from socket (or not yet connected to).


namespace Socket_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Socket::is_Write_allowed()
 *	Description : Execution allowed for Write attribute
 */
//--------------------------------------------------------
bool Socket::is_Write_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Write command.
	/*----- PROTECTED REGION ID(Socket::WriteStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::WriteStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_Read_allowed()
 *	Description : Execution allowed for Read attribute
 */
//--------------------------------------------------------
bool Socket::is_Read_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(Socket::ReadStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::ReadStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_Reconnect_allowed()
 *	Description : Execution allowed for Reconnect attribute
 */
//--------------------------------------------------------
bool Socket::is_Reconnect_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::ON)
	{
	/*----- PROTECTED REGION ID(Socket::ReconnectStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::ReconnectStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_WriteAndRead_allowed()
 *	Description : Execution allowed for WriteAndRead attribute
 */
//--------------------------------------------------------
bool Socket::is_WriteAndRead_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(Socket::WriteAndReadStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::WriteAndReadStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_Readln_allowed()
 *	Description : Execution allowed for Readln attribute
 */
//--------------------------------------------------------
bool Socket::is_Readln_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(Socket::ReadlnStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::ReadlnStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_ReadUntil_allowed()
 *	Description : Execution allowed for ReadUntil attribute
 */
//--------------------------------------------------------
bool Socket::is_ReadUntil_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(Socket::ReadUntilStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::ReadUntilStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_WriteReadUntil_allowed()
 *	Description : Execution allowed for WriteReadUntil attribute
 */
//--------------------------------------------------------
bool Socket::is_WriteReadUntil_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(Socket::WriteReadUntilStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::WriteReadUntilStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_WriteLine_allowed()
 *	Description : Execution allowed for WriteLine attribute
 */
//--------------------------------------------------------
bool Socket::is_WriteLine_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for WriteLine command.
	/*----- PROTECTED REGION ID(Socket::WriteLineStateAllowed) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	Socket::WriteLineStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_WriteRead_allowed()
 *	Description : Execution allowed for WriteRead attribute
 */
//--------------------------------------------------------
bool Socket::is_WriteRead_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for WriteRead command.
	/*----- PROTECTED REGION ID(Socket::WriteReadStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Socket::WriteReadStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_WriteReadZero_allowed()
 *	Description : Execution allowed for WriteReadZero attribute
 */
//--------------------------------------------------------
bool Socket::is_WriteReadZero_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for WriteReadZero command.
	/*----- PROTECTED REGION ID(Socket::WriteReadZeroStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Socket::WriteReadZeroStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Socket::is_ReadChar_allowed()
 *	Description : Execution allowed for ReadChar attribute
 */
//--------------------------------------------------------
bool Socket::is_ReadChar_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(Socket::ReadCharStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Socket::ReadCharStateAllowed
		return false;
	}
	return true;
}

}	//	End of namespace
