#!/usr/bin/env python
# -*- coding:utf-8 -*- 


##############################################################################
## license :
##============================================================================
##
## File :        PyHysteresis.py
## 
## Project :     PyHysteresis
##
## This file is part of Tango device class.
## 
## Tango is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
## 
## Tango is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with Tango.  If not, see <http://www.gnu.org/licenses/>.
## 
##
## $Author :      christian.stamm$
##
## $Revision :    $
##
## $Date :        $
##
## $HeadUrl :     $
##============================================================================
##            This file is generated by POGO
##    (Program Obviously used to Generate tango Object)
##
##        (c) - Software Engineering Group - ESRF
##############################################################################

""""""

__all__ = ["PyHysteresis", "PyHysteresisClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(PyHysteresis.additionnal_import) ENABLED START -----#
from HysteresisThread import*

#----- PROTECTED REGION END -----#	//	PyHysteresis.additionnal_import

## Device States Description
## No states for this device

class PyHysteresis (PyTango.Device_4Impl):

    #--------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PyHysteresis.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyHysteresis.global_variables

    def __init__(self,cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PyHysteresis.init_device(self)
        #----- PROTECTED REGION ID(PyHysteresis.__init__) ENABLED START -----#
        
        self.set_state(PyTango.DevState.INIT)        
        # define ads bridge proxy
        self.ads = PyTango.DeviceProxy(self.AdsBridge)
        self.info_stream("Opened ADS bridge "+self.AdsBridge)
        print("PyHysteresis: opened ADS bridge proxy "+self.AdsBridge)
        self.set_state(PyTango.DevState.ON)        
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PyHysteresis.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_IntegrationTime_read = 0.0
        self.attr_NumberOfPoints_read = 0
        self.attr_MagneticField_read = 0.0
        self.attr_Cycles_read = 0
        self.attr_CycleReadback_read = 0
        self.attr_Hc_read = 0.0
        self.attr_Hshift_read = 0.0
        self.attr_Ms_read = 0.0
        self.attr_Mr_read = 0.0
        self.attr_fieldCorrectionFactor_read = 0.0
        self.attr_result1_read = [0.0]
        self.attr_result2_read = [0.0]
        self.attr_result3_read = [0.0]
        self.attr_result4_read = [0.0]
        self.attr_result5_read = [0.0]
        self.attr_result6_read = [0.0]
        self.attr_field_read = [0.0]
        #----- PROTECTED REGION ID(PyHysteresis.init_device) ENABLED START -----#
        #self.ads0 = PyTango.DeviceProxy(self.AdsBridge)      
        # initialize also with previously used values from Beckhoff system (not working, 
        self.attr_IntegrationTime_read = 2 #self.ads0.ReadReal(self.BeckhoffHystIntegrationTime)
        self.attr_NumberOfPoints_read = 100 #self.ads0.ReadInt(self.BeckhoffHystArrayLength)
        self.attr_MagneticField_read = 1
        self.attr_Cycles_read = 1
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PyHysteresis.always_executed_hook) ENABLED START -----#
                
        #----- PROTECTED REGION END -----#	//	PyHysteresis.always_executed_hook

    #-----------------------------------------------------------------------------
    #    PyHysteresis read/write attribute methods
    #-----------------------------------------------------------------------------
    
    def read_IntegrationTime(self, attr):
        self.debug_stream("In read_IntegrationTime()")
        #----- PROTECTED REGION ID(PyHysteresis.IntegrationTime_read) ENABLED START -----#
        # time*2 for up&down loop
        attr.set_value(self.ads.ReadReal(self.BeckhoffHystIntegrationTime)*2)
        #----- PROTECTED REGION END -----#	//	PyHysteresis.IntegrationTime_read
        
    def write_IntegrationTime(self, attr):
        self.debug_stream("In write_IntegrationTime()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(PyHysteresis.IntegrationTime_write) ENABLED START -----#
        if data<=0:
            data=0.01 # no negative times are allowed
        self.attr_IntegrationTime_read = data
        self.ads.WriteReal(self.BeckhoffHystIntegrationTime+"={:6f}".format(data/2))
        #----- PROTECTED REGION END -----#	//	PyHysteresis.IntegrationTime_write
        
    def read_NumberOfPoints(self, attr):
        self.debug_stream("In read_NumberOfPoints()")
        #----- PROTECTED REGION ID(PyHysteresis.NumberOfPoints_read) ENABLED START -----#
        attr.set_value(self.ads.ReadInt(self.BeckhoffHystArrayLength))
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.NumberOfPoints_read
        
    def write_NumberOfPoints(self, attr):
        self.debug_stream("In write_NumberOfPoints()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(PyHysteresis.NumberOfPoints_write) ENABLED START -----#
        # integer number format
        if data <= 0:
            data = 1
        if data > 350: # current limitation of ads read array function
            data = 350 
        self.attr_NumberOfPoints_read = data
        self.ads.WriteInt(self.BeckhoffHystArrayLength+"={:d}".format(data)) 
        #----- PROTECTED REGION END -----#	//	PyHysteresis.NumberOfPoints_write
        
    def read_MagneticField(self, attr):
        self.debug_stream("In read_MagneticField()")
        #----- PROTECTED REGION ID(PyHysteresis.MagneticField_read) ENABLED START -----#
        attr.set_value(self.attr_MagneticField_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.MagneticField_read
        
    def write_MagneticField(self, attr):
        self.debug_stream("In write_MagneticField()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(PyHysteresis.MagneticField_write) ENABLED START -----#
        # only set field at start
        #self.ads.WriteReal(self.BeckhoffHystField+"={:6f}".format(data))
        self.attr_MagneticField_read = data
        #----- PROTECTED REGION END -----#	//	PyHysteresis.MagneticField_write
        
    def read_Cycles(self, attr):
        self.debug_stream("In read_Cycles()")
        #----- PROTECTED REGION ID(PyHysteresis.Cycles_read) ENABLED START -----#
        attr.set_value(self.attr_Cycles_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Cycles_read
        
    def write_Cycles(self, attr):
        self.debug_stream("In write_Cycles()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(PyHysteresis.Cycles_write) ENABLED START -----#
        if data <= 0:
            data = 1
        self.attr_Cycles_read = data  
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Cycles_write
        
    def read_CycleReadback(self, attr):
        self.debug_stream("In read_CycleReadback()")
        #----- PROTECTED REGION ID(PyHysteresis.CycleReadback_read) ENABLED START -----#
        attr.set_value(self.attr_CycleReadback_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.CycleReadback_read
        
    def read_Hc(self, attr):
        self.debug_stream("In read_Hc()")
        #----- PROTECTED REGION ID(PyHysteresis.Hc_read) ENABLED START -----#
        attr.set_value(self.attr_Hc_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Hc_read
        
    def read_Hshift(self, attr):
        self.debug_stream("In read_Hshift()")
        #----- PROTECTED REGION ID(PyHysteresis.Hshift_read) ENABLED START -----#
        attr.set_value(self.attr_Hshift_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Hshift_read
        
    def read_Ms(self, attr):
        self.debug_stream("In read_Ms()")
        #----- PROTECTED REGION ID(PyHysteresis.Ms_read) ENABLED START -----#
        attr.set_value(self.attr_Ms_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Ms_read
        
    def read_Mr(self, attr):
        self.debug_stream("In read_Mr()")
        #----- PROTECTED REGION ID(PyHysteresis.Mr_read) ENABLED START -----#
        attr.set_value(self.attr_Mr_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Mr_read
        
    def read_fieldCorrectionFactor(self, attr):
        self.debug_stream("In read_fieldCorrectionFactor()")
        #----- PROTECTED REGION ID(PyHysteresis.fieldCorrectionFactor_read) ENABLED START -----#
        attr.set_value(self.attr_fieldCorrectionFactor_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.fieldCorrectionFactor_read
        
    def write_fieldCorrectionFactor(self, attr):
        self.debug_stream("In write_fieldCorrectionFactor()")
        data=attr.get_write_value()
        #----- PROTECTED REGION ID(PyHysteresis.fieldCorrectionFactor_write) ENABLED START -----#
        self.attr_fieldCorrectionFactor_read = data
        #----- PROTECTED REGION END -----#	//	PyHysteresis.fieldCorrectionFactor_write
        
    def read_result1(self, attr):
        self.debug_stream("In read_result1()")
        #----- PROTECTED REGION ID(PyHysteresis.result1_read) ENABLED START -----#
        attr.set_value(self.attr_result1_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.result1_read
        
    def read_result2(self, attr):
        self.debug_stream("In read_result2()")
        #----- PROTECTED REGION ID(PyHysteresis.result2_read) ENABLED START -----#
        attr.set_value(self.attr_result2_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.result2_read
        
    def read_result3(self, attr):
        self.debug_stream("In read_result3()")
        #----- PROTECTED REGION ID(PyHysteresis.result3_read) ENABLED START -----#
        attr.set_value(self.attr_result3_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.result3_read
        
    def read_result4(self, attr):
        self.debug_stream("In read_result4()")
        #----- PROTECTED REGION ID(PyHysteresis.result4_read) ENABLED START -----#
        attr.set_value(self.attr_result4_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.result4_read
        
    def read_result5(self, attr):
        self.debug_stream("In read_result5()")
        #----- PROTECTED REGION ID(PyHysteresis.result5_read) ENABLED START -----#
        attr.set_value(self.attr_result5_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.result5_read
        
    def read_result6(self, attr):
        self.debug_stream("In read_result6()")
        #----- PROTECTED REGION ID(PyHysteresis.result6_read) ENABLED START -----#
        attr.set_value(self.attr_result6_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.result6_read
        
    def read_field(self, attr):
        self.debug_stream("In read_field()")
        #----- PROTECTED REGION ID(PyHysteresis.field_read) ENABLED START -----#
        attr.set_value(self.attr_field_read)
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.field_read
        
    
    
        #----- PROTECTED REGION ID(PyHysteresis.initialize_dynamic_attributes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.initialize_dynamic_attributes
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PyHysteresis.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.read_attr_hardware


    #-----------------------------------------------------------------------------
    #    PyHysteresis command methods
    #-----------------------------------------------------------------------------
    
    def Start(self):
        """ 
        
        :param : 
        :type: PyTango.DevVoid
        :return: 
        :rtype: PyTango.DevVoid """
        self.debug_stream("In Start()")
        #----- PROTECTED REGION ID(PyHysteresis.Start) ENABLED START -----#
        # set state to running done in thread # self.set_state(PyTango.DevState.RUNNING)
        # clear old results
        self.attr_result1_read = [0.0]
        self.attr_result2_read = [0.0]
        self.attr_result3_read = [0.0]
        self.attr_result4_read = [0.0]
        self.attr_result5_read = [0.0]
        self.attr_result6_read = [0.0]
        self.attr_Hc_read = 0.0
        self.attr_Hshift_read = 0.0
        self.attr_Ms_read = 0.0
        self.attr_Mr_read = 0.0
        
        # initialize Beckhoff system
        # integration time (half value for each half loop)
        self.ads.WriteReal(self.BeckhoffHystIntegrationTime+"={:6f}".format(self.attr_IntegrationTime_read/2))
        # number of points
        self.ads.WriteInt(self.BeckhoffHystArrayLength+"={:d}".format(self.attr_NumberOfPoints_read))
        # DAC channel: 1=long, 2=polar
        self.ads.WriteInt(self.BeckhoffHystOutputChannel+"={:d}".format(self.BeckhoffHystChannelValue))
               
        # call hysteresis thread
        if self.get_state() == PyTango.DevState.ON:
            self.thread = HysteresisThread(self)
            self.info_stream("Starting hysteresis measurement")
            self.thread.start()
        else:
            print "Thread is already running."
            
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Start
        
    def Abort(self):
        """ 
        
        :param : 
        :type: PyTango.DevVoid
        :return: 
        :rtype: PyTango.DevVoid """
        self.debug_stream("In Abort()")
        #----- PROTECTED REGION ID(PyHysteresis.Abort) ENABLED START -----#
        if self.thread.is_alive() == True:
            self.thread.stop()
            
        self.set_state(PyTango.DevState.ON)
        #----- PROTECTED REGION END -----#	//	PyHysteresis.Abort
        

    #----- PROTECTED REGION ID(PyHysteresis.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyHysteresis.programmer_methods

class PyHysteresisClass(PyTango.DeviceClass):
    #--------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PyHysteresis.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyHysteresis.global_class_variables

    def dyn_attr(self, dev_list):
        """Invoked to create dynamic attributes for the given devices.
        Default implementation calls
        :meth:`PyHysteresis.initialize_dynamic_attributes` for each device
    
        :param dev_list: list of devices
        :type dev_list: :class:`PyTango.DeviceImpl`"""
    
        for dev in dev_list:
            try:
                dev.initialize_dynamic_attributes()
            except:
                import traceback
                dev.warn_stream("Failed to initialize dynamic attributes")
                dev.debug_stream("Details: " + traceback.format_exc())
        #----- PROTECTED REGION ID(PyHysteresis.dyn_attr) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.dyn_attr

    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'AdsBridge':
            [PyTango.DevString,
            "Tango device name of ads bridge",
            ["hpp-n42/beckhoff/adsBridge"] ],
        'BeckhoffResult1Name':
            [PyTango.DevString,
            "Beckhoff variable name of the in1 array",
            ["MAIN.HystResult1"] ],
        'BeckhoffResult2Name':
            [PyTango.DevString,
            "Beckhoff variable name of the in2 array",
            ["MAIN.HystResult2"] ],
        'BeckhoffResult3Name':
            [PyTango.DevString,
            "Beckhoff variable name of the in3 array",
            ["MAIN.HystResult3"] ],
        'BeckhoffResult4Name':
            [PyTango.DevString,
            "Beckhoff variable name of the in4 array",
            ["MAIN.HystResult4"] ],
        'BeckhoffResult5Name':
            [PyTango.DevString,
            "Beckhoff variable name of the in5 array",
            ["MAIN.HystResult5"] ],
        'BeckhoffResult6Name':
            [PyTango.DevString,
            "Beckhoff variable name of the in6 array",
            ["MAIN.HystResult6"] ],
        'BeckhoffHystStart':
            [PyTango.DevString,
            "Variable name on Beckhoff used to start hysteresis measurement",
            ["MAIN.HystStart"] ],
        'BeckhoffHystAbort':
            [PyTango.DevString,
            "Name of the Beckhoff variable to abort hysteresis",
            ["MAIN.HystAbort"] ],
        'BeckhoffHystRunning':
            [PyTango.DevString,
            "Variable name on Beckhoff used to indicate a running hysteresis measurement",
            ["MAIN.HystRunning"] ],
        'BeckhoffHystField':
            [PyTango.DevString,
            "Variable name on Beckhoff for maximum magnetic field for hysteresis measurement",
            ["MAIN.HystField"] ],
        'BeckhoffHystIntegrationTime':
            [PyTango.DevString,
            "Variable name on Beckhoff specifying the hysteresis measurement time",
            ["MAIN.HystIntegrationTime"] ],
        'BeckhoffHystArrayLength':
            [PyTango.DevString,
            "Variable name on Beckhoff specifying the number of points for hysteresis measurement",
            ["MAIN.HystArrayLength"] ],
        'BeckhoffHystOutputChannel':
            [PyTango.DevString,
            "Name of Beckhoff variable for output DAC",
            ["MAIN.HystChannel"] ],
        'BeckhoffHystChannelValue':
            [PyTango.DevUShort,
            "Output channel number for Beckhoff DAC (e.g. 1=long or 2=polar)",
            [] ],
        'AmperePerVolt':
            [PyTango.DevDouble,
            "Power Supply output current for 1 V programming voltage",
            [] ],
        'BeckhoffPollingTime':
            [PyTango.DevDouble,
            "Polling time for communication with Beckhoff system in s (0.02)",
            [0.02]],
        'HallSensitivity':
            [PyTango.DevDouble,
            "Sensitivity of the Hall probe in Volt/Tesla",
            [5.0]],
        }


    #    Command definitions
    cmd_list = {
        'Start':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Abort':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'IntegrationTime':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'NumberOfPoints':
            [[PyTango.DevULong,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'MagneticField':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'Cycles':
            [[PyTango.DevULong,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'CycleReadback':
            [[PyTango.DevULong,
            PyTango.SCALAR,
            PyTango.READ]],
        'Hc':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'Hshift':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'Ms':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'Mr':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ]],
        'fieldCorrectionFactor':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'result1':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000]],
        'result2':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000]],
        'result3':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000]],
        'result4':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000]],
        'result5':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000]],
        'result6':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000]],
        'field':
            [[PyTango.DevDouble,
            PyTango.SPECTRUM,
            PyTango.READ, 1000],
            {
                'unit': "mT",
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PyHysteresisClass,PyHysteresis,'PyHysteresis')
        #----- PROTECTED REGION ID(PyHysteresis.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyHysteresis.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed,e:
        print '-------> Received a DevFailed exception:',e
    except Exception,e:
        print '-------> An unforeseen exception occured....',e

if __name__ == '__main__':
    main()
