#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        ANM200.py
#
#  Project :     Attocube Piezomotors control
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      christoph.murer$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["ANM200", "ANM200Class", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(ANM200.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	ANM200.additionnal_import

# Device States Description
# ON : 
# STANDBY : 
# RUNNING : 
# OFF : 


class ANM200 (PyTango.Device_4Impl):
    """Moves the piezo motors by applying up to +/- 10V through the Beckhoff system to the three ANM200 DC inputs"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(ANM200.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ANM200.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        ANM200.init_device(self)
        #----- PROTECTED REGION ID(ANM200.__init__) ENABLED START -----#
        #print("__init__ was successful")
        #----- PROTECTED REGION END -----#	//	ANM200.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(ANM200.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ANM200.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_x_read = 0.0
        self.attr_y_read = 0.0
        self.attr_z_read = 0.0
        self.attr_scaling_read = 0.0
        #----- PROTECTED REGION ID(ANM200.init_device) ENABLED START -----#
        self.set_state(PyTango.DevState.ON)
        #print("device was initialized successfully")
        self.Sx = PyTango.DeviceProxy(self.Socketx)
        self.Sy = PyTango.DeviceProxy(self.Sockety)
        self.Sz = PyTango.DeviceProxy(self.Socketz)
        #print("device was initialized successfully (2)")
        #----- PROTECTED REGION END -----#	//	ANM200.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(ANM200.always_executed_hook) ENABLED START -----#
        #----- PROTECTED REGION END -----#	//	ANM200.always_executed_hook

    # -------------------------------------------------------------------------
    #    ANM200 read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_x(self, attr):
        self.debug_stream("In read_x()")
        #----- PROTECTED REGION ID(ANM200.x_read) ENABLED START -----#
        attr.set_value(self.attr_x_read/self.attr_scaling_read)
        
        #----- PROTECTED REGION END -----#	//	ANM200.x_read
        
    def write_x(self, attr):
        self.debug_stream("In write_x()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ANM200.x_write) ENABLED START -----#
        data *= self.attr_scaling_read
        self.Sx.write_attribute('Value',data)
        self.attr_x_read = data
        #----- PROTECTED REGION END -----#	//	ANM200.x_write
        
    def read_y(self, attr):
        self.debug_stream("In read_y()")
        #----- PROTECTED REGION ID(ANM200.y_read) ENABLED START -----#
        attr.set_value(self.attr_y_read/self.attr_scaling_read)
        
        #----- PROTECTED REGION END -----#	//	ANM200.y_read
        
    def write_y(self, attr):
        self.debug_stream("In write_y()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ANM200.y_write) ENABLED START -----#
        data *= self.attr_scaling_read
        self.Sy.write_attribute('Value',data)
        self.attr_y_read = data        
        #----- PROTECTED REGION END -----#	//	ANM200.y_write
        
    def read_z(self, attr):
        self.debug_stream("In read_z()")
        #----- PROTECTED REGION ID(ANM200.z_read) ENABLED START -----#
        attr.set_value(self.attr_z_read/self.attr_scaling_read)
        
        #----- PROTECTED REGION END -----#	//	ANM200.z_read
        
    def write_z(self, attr):
        self.debug_stream("In write_z()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ANM200.z_write) ENABLED START -----#
        data *= self.attr_scaling_read
        self.Sz.write_attribute('Value',data)
        self.attr_z_read = data        
        #----- PROTECTED REGION END -----#	//	ANM200.z_write
        
    def read_scaling(self, attr):
        self.debug_stream("In read_scaling()")
        #----- PROTECTED REGION ID(ANM200.scaling_read) ENABLED START -----#
        attr.set_value(self.attr_scaling_read)
        
        #----- PROTECTED REGION END -----#	//	ANM200.scaling_read
        
    def write_scaling(self, attr):
        self.debug_stream("In write_scaling()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(ANM200.scaling_write) ENABLED START -----#
        self.attr_scaling_read = data
        #----- PROTECTED REGION END -----#	//	ANM200.scaling_write
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(ANM200.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	ANM200.read_attr_hardware


    # -------------------------------------------------------------------------
    #    ANM200 command methods
    # -------------------------------------------------------------------------
    

    #----- PROTECTED REGION ID(ANM200.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ANM200.programmer_methods

class ANM200Class(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(ANM200.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	ANM200.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'Socketx':
            [PyTango.DevString, 
             '',
            ["hpp-n42/beckhoff/AOC1"] ],
        'Sockety':
            [PyTango.DevString, 
             '',
            ["hpp-n42/beckhoff/AOC2"] ],
        'Socketz':
            [PyTango.DevString, 
             '',
            ["hpp-n42/beckhoff/AOC3"] ],
        }


    #    Command definitions
    cmd_list = {
        }


    #    Attribute definitions
    attr_list = {
        'x':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        'y':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true_without_hard_applied"
            } ],
        'z':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'scaling':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'description': "scaling factor converting the output voltage [V] to distance [um]; given as distance/Voltage",
                'Memorized':"true"
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(ANM200Class, ANM200, 'ANM200')
        #----- PROTECTED REGION ID(ANM200.add_classes) ENABLED START -----#
        #print('class was added in main()')
        #----- PROTECTED REGION END -----#	//	ANM200.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
