#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        PyKeithley.py
#
#  Project :     PyKeithley - control a Keithley6221 current source
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      christoph.murer$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["PyKeithley", "PyKeithleyClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(PyKeithley.additionnal_import) ENABLED START -----#
import time
#----- PROTECTED REGION END -----#	//	PyKeithley.additionnal_import

# Device States Description
# No states for this device


class PyKeithley (PyTango.Device_4Impl):
    """Server controls Keithley 6221 current source, is able to set a range
    or autorange, set a current and apply it. Also controls the wave
    functionality for sine waves."""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(PyKeithley.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyKeithley.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        PyKeithley.init_device(self)
        #----- PROTECTED REGION ID(PyKeithley.__init__) ENABLED START -----#
        self.set_state(PyTango.DevState.ON)
        #----- PROTECTED REGION END -----#	//	PyKeithley.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(PyKeithley.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_current_read = 0.0
        self.attr_compliance_read = 0.0
        self.attr_autorange_read = False
        self.attr_amplitude_read = 0.0
        self.attr_frequency_read = 0.0
        self.attr_range_read = ""
        #----- PROTECTED REGION ID(PyKeithley.init_device) ENABLED START -----#
        self.PyKeithley = PyTango.DeviceProxy(self.SocketProxy)
        self.info_stream("opened AdsBridge Proxy at "+self.SocketProxy)
        print("PyRelais: opened adsBridge Proxy at "+self.SocketProxy)
        self.set_state(PyTango.DevState.ON)
        #----- PROTECTED REGION END -----#	//	PyKeithley.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(PyKeithley.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.always_executed_hook

    # -------------------------------------------------------------------------
    #    PyKeithley read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_current(self, attr):
        self.debug_stream("In read_current()")
        #----- PROTECTED REGION ID(PyKeithley.current_read) ENABLED START -----#
        attr.set_value(self.attr_current_read)
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.current_read
        
    def write_current(self, attr):
        self.debug_stream("In write_current()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(PyKeithley.current_write) ENABLED START -----#
        # Keithley expects the current in A; this allows us to write it in mA...
        # also should not be bigger than 105 mA:
        if abs(data) > 105.0:
            data = 105.0
        self.PyKeithley.Write('CURR '+str(data/1000.0))
        self.attr_current_read = data
        #----- PROTECTED REGION END -----#	//	PyKeithley.current_write
        
    def read_compliance(self, attr):
        self.debug_stream("In read_compliance()")
        #----- PROTECTED REGION ID(PyKeithley.compliance_read) ENABLED START -----#
        attr.set_value(self.attr_compliance_read)
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.compliance_read
        
    def write_compliance(self, attr):
        self.debug_stream("In write_compliance()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(PyKeithley.compliance_write) ENABLED START -----#
        # compliance volage has to be between 0.1 V and 105 V: change that accordingly
        if data < 0.1:
			data = 0.1
        if data > 105.0:
            data = 105.0
        self.PyKeithley.Write('CURR:COMP '+str(data))
        self.attr_compliance_read = data
        #----- PROTECTED REGION END -----#	//	PyKeithley.compliance_write
        
    def read_autorange(self, attr):
        self.debug_stream("In read_autorange()")
        #----- PROTECTED REGION ID(PyKeithley.autorange_read) ENABLED START -----#
        attr.set_value(self.attr_autorange_read)
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.autorange_read
        
    def write_autorange(self, attr):
        self.debug_stream("In write_autorange()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(PyKeithley.autorange_write) ENABLED START -----#
        if data == True:
			self.PyKeithley.Write('CURR:RANGE:AUTO ON')
        else:
			self.PyKeithley.Write('CURR:RANGE:AUTO OFF')
        self.attr_autorange_read = data
        #----- PROTECTED REGION END -----#	//	PyKeithley.autorange_write
        
    def read_amplitude(self, attr):
        self.debug_stream("In read_amplitude()")
        #----- PROTECTED REGION ID(PyKeithley.amplitude_read) ENABLED START -----#
        attr.set_value(self.attr_amplitude_read)
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.amplitude_read
        
    def write_amplitude(self, attr):
        self.debug_stream("In write_amplitude()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(PyKeithley.amplitude_write) ENABLED START -----#
        self.attr_amplitude_read = data
        self.WAVEOFF()
        self.SINEWAVE()
        #----- PROTECTED REGION END -----#	//	PyKeithley.amplitude_write
        
    def read_frequency(self, attr):
        self.debug_stream("In read_frequency()")
        #----- PROTECTED REGION ID(PyKeithley.frequency_read) ENABLED START -----#      
	attr.set_value(self.attr_frequency_read)
        #----- PROTECTED REGION END -----#	//	PyKeithley.frequency_read
        
    def write_frequency(self, attr):
        self.debug_stream("In write_frequency()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(PyKeithley.frequency_write) ENABLED START -----#
        self.attr_frequency_read = data
        #----- PROTECTED REGION END -----#	//	PyKeithley.frequency_write
        
    def read_range(self, attr):
        self.debug_stream("In read_range()")
        #----- PROTECTED REGION ID(PyKeithley.range_read) ENABLED START -----#
	#self.attr_range_read=str(self.PyKeithley.WriteReadZero('CURR:RANGE'))  
        attr.set_value(self.attr_range_read)
        #----- PROTECTED REGION END -----#	//	PyKeithley.range_read
        
    def write_range(self, attr):
        self.debug_stream("In write_range()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(PyKeithley.range_write) ENABLED START -----#
        if data == "0.0002mA":
			self.PyKeithley.Write('CURR:RANGE 1e-7')
        if data == "0.002mA":
			self.PyKeithley.Write('CURR:RANGE 1e-6')
        if data == "0.02mA":
			self.PyKeithley.Write('CURR:RANGE 1e-5')	        
	if data == "0.2mA":
			self.PyKeithley.Write('CURR:RANGE 1e-4')
        if data == "2mA":
			self.PyKeithley.Write('CURR:RANGE 1e-3')
        if data == "20mA":
			self.PyKeithley.Write('CURR:RANGE 12e-3')
	if data == "100mA":
			self.PyKeithley.Write('CURR:RANGE 25e-3')          
        #----- PROTECTED REGION END -----#	//	PyKeithley.range_write
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(PyKeithley.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.read_attr_hardware


    # -------------------------------------------------------------------------
    #    PyKeithley command methods
    # -------------------------------------------------------------------------
    
    def ON(self):
        """ Sets the output to on
        """
        self.debug_stream("In ON()")
        #----- PROTECTED REGION ID(PyKeithley.ON) ENABLED START -----#
        self.PyKeithley.Write('OUTP ON')
        #----- PROTECTED REGION END -----#	//	PyKeithley.ON
        
    def OFF(self):
        """ 
        """
        self.debug_stream("In OFF()")
        #----- PROTECTED REGION ID(PyKeithley.OFF) ENABLED START -----#
        self.PyKeithley.Write('OUTP OFF')
        #----- PROTECTED REGION END -----#	//	PyKeithley.OFF
        
    def SINEWAVE(self):
        """ 
        """
        self.debug_stream("In SINEWAVE()")
        #----- PROTECTED REGION ID(PyKeithley.SINEWAVE) ENABLED START -----#
        self.PyKeithley.Write('SOUR:WAVE:FUNC SIN')
        self.PyKeithley.Write('SOUR:WAVE:FREQ '+str(self.attr_frequency_read))
        self.PyKeithley.Write('SOUR:WAVE:AMPL '+str(self.attr_amplitude_read/1000.0))
	self.PyKeithley.Write('SOUR:WAVE:PMAR:STAT ON') # enables phase marker (for external triggering)
	self.PyKeithley.Write('SOUR:WAVE:PMAR 180') # sets marker phase
	self.PyKeithley.Write('SOUR:WAVE:PMAR:OLIN 5') # sets phase marker trigger line
        self.PyKeithley.Write('SOUR:WAVE:DUR:TIME INF') # infinite repetition of waveform
        self.PyKeithley.Write('SOUR:WAVE:RANG FIX') # sets best range for keithley
        time.sleep(0.1)
        self.PyKeithley.Write('SOUR:WAVE:ARM')
        self.PyKeithley.Write('SOUR:WAVE:INIT')
        #----- PROTECTED REGION END -----#	//	PyKeithley.SINEWAVE
        
    def WAVEOFF(self):
        """ 
        """
        self.debug_stream("In WAVEOFF()")
        #----- PROTECTED REGION ID(PyKeithley.WAVEOFF) ENABLED START -----#
        self.PyKeithley.Write('SOUR:WAVE:ABOR')
        #----- PROTECTED REGION END -----#	//	PyKeithley.WAVEOFF
        

    #----- PROTECTED REGION ID(PyKeithley.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyKeithley.programmer_methods

class PyKeithleyClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(PyKeithley.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	PyKeithley.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        'SocketProxy':
            [PyTango.DevString, 
            "Socket which generates the Ethernet connection.",
            ["hpp-n42/socket/keithley6221"] ],
        }


    #    Command definitions
    cmd_list = {
        'ON':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'OFF':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'SINEWAVE':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'WAVEOFF':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'current':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'compliance':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'autorange':
            [[PyTango.DevBoolean,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'amplitude':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        'frequency':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        'range':
            [[PyTango.DevString,
            PyTango.SCALAR,
            PyTango.READ_WRITE],
            {
                'Memorized':"true"
            } ],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(PyKeithleyClass, PyKeithley, 'PyKeithley')
        #----- PROTECTED REGION ID(PyKeithley.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	PyKeithley.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
