/*----- PROTECTED REGION ID(TTbeckhoffClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        TTbeckhoffClass.h
//
// description : Include for the TTbeckhoff root class.
//               This class is the singleton class for
//                the TTbeckhoff device class.
//               It contains all properties and methods which the 
//               TTbeckhoff requires only once e.g. the commands.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TTbeckhoffClass_H
#define TTbeckhoffClass_H

#include <tango.h>
#include <TTbeckhoff.h>


/*----- PROTECTED REGION END -----*/	//	TTbeckhoffClass.h


namespace TTbeckhoff_ns
{
/*----- PROTECTED REGION ID(TTbeckhoffClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	TTbeckhoffClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute ContinuousRun class definition
class ContinuousRunAttrib: public Tango::Attr
{
public:
	ContinuousRunAttrib():Attr("ContinuousRun",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~ContinuousRunAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TTbeckhoff *>(dev))->read_ContinuousRun(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<TTbeckhoff *>(dev))->write_ContinuousRun(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TTbeckhoff *>(dev))->is_ContinuousRun_allowed(ty);}
};

//	Attribute average class definition
class averageAttrib: public Tango::Attr
{
public:
	averageAttrib():Attr("average",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~averageAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TTbeckhoff *>(dev))->read_average(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TTbeckhoff *>(dev))->is_average_allowed(ty);}
};

//	Attribute min class definition
class minAttrib: public Tango::Attr
{
public:
	minAttrib():Attr("min",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~minAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TTbeckhoff *>(dev))->read_min(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TTbeckhoff *>(dev))->is_min_allowed(ty);}
};

//	Attribute max class definition
class maxAttrib: public Tango::Attr
{
public:
	maxAttrib():Attr("max",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~maxAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TTbeckhoff *>(dev))->read_max(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TTbeckhoff *>(dev))->is_max_allowed(ty);}
};

//	Attribute timetrace class definition
class timetraceAttrib: public Tango::SpectrumAttr
{
public:
	timetraceAttrib():SpectrumAttr("timetrace",
			Tango::DEV_DOUBLE, Tango::READ, 400) {};
	~timetraceAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TTbeckhoff *>(dev))->read_timetrace(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TTbeckhoff *>(dev))->is_timetrace_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command Start class definition
class StartClass : public Tango::Command
{
public:
	StartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TTbeckhoff *>(dev))->is_Start_allowed(any);}
};

//	Command Abort class definition
class AbortClass : public Tango::Command
{
public:
	AbortClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	AbortClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~AbortClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TTbeckhoff *>(dev))->is_Abort_allowed(any);}
};

//	Command StartContinuous class definition
class StartContinuousClass : public Tango::Command
{
public:
	StartContinuousClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartContinuousClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartContinuousClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TTbeckhoff *>(dev))->is_StartContinuous_allowed(any);}
};


/**
 *	The TTbeckhoffClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  TTbeckhoffClass : public Tango::DeviceClass
#else
class TTbeckhoffClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(TTbeckhoffClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoffClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static TTbeckhoffClass *init(const char *);
		static TTbeckhoffClass *instance();
		~TTbeckhoffClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		TTbeckhoffClass(string &);
		static TTbeckhoffClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	TTbeckhoff_H
