/*----- PROTECTED REGION ID(TTbeckhoff.h) ENABLED START -----*/
//=============================================================================
//
// file :        TTbeckhoff.h
//
// description : Include file for the TTbeckhoff class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TTbeckhoff_H
#define TTbeckhoff_H

#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	TTbeckhoff.h

/**
 *  TTbeckhoff class description:
 *    Tango server to measure time trace of Beckhoff ADC
 */

namespace TTbeckhoff_ns
{
/*----- PROTECTED REGION ID(TTbeckhoff::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::Additional Class Declarations

class TTbeckhoff : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TTbeckhoff::Data Members) ENABLED START -----*/

//	Add your own data members
Tango::DeviceProxy *adsPtr;

/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::Data Members

//	Device property data members
public:
	//	AdsBridge:	Tango path to the ads bridge,e.g. 
	//  hpp-n42/beckhoff/adsBridge
	string	adsBridge;
	//	BeckhoffVariable:	Variable name of the Beckhoff array that holds the time trace
	string	beckhoffVariable;
	//	BeckhoffTTrun:	Variable name on Beckhoff used to start time trace
	string	beckhoffTTrun;

//	Attribute data members
public:
	Tango::DevBoolean	*attr_ContinuousRun_read;
	Tango::DevDouble	*attr_average_read;
	Tango::DevDouble	*attr_min_read;
	Tango::DevDouble	*attr_max_read;
	Tango::DevDouble	*attr_timetrace_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TTbeckhoff(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TTbeckhoff(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TTbeckhoff(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~TTbeckhoff() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TTbeckhoff::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : TTbeckhoff::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute ContinuousRun related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_ContinuousRun(Tango::Attribute &attr);
	virtual void write_ContinuousRun(Tango::WAttribute &attr);
	virtual bool is_ContinuousRun_allowed(Tango::AttReqType type);
/**
 *	Attribute average related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_average(Tango::Attribute &attr);
	virtual bool is_average_allowed(Tango::AttReqType type);
/**
 *	Attribute min related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_min(Tango::Attribute &attr);
	virtual bool is_min_allowed(Tango::AttReqType type);
/**
 *	Attribute max related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_max(Tango::Attribute &attr);
	virtual bool is_max_allowed(Tango::AttReqType type);
/**
 *	Attribute timetrace related methods
 *	Description: time trace of ADC1
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Spectrum max = 400
 */
	virtual void read_timetrace(Tango::Attribute &attr);
	virtual bool is_timetrace_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : TTbeckhoff::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command Start related method
	 *	Description: Start time trace measurement
	 *
	 */
	virtual void start();
	virtual bool is_Start_allowed(const CORBA::Any &any);
	/**
	 *	Command Abort related method
	 *	Description: 
	 *
	 */
	virtual void abort();
	virtual bool is_Abort_allowed(const CORBA::Any &any);
	/**
	 *	Command StartContinuous related method
	 *	Description: 
	 *
	 */
	virtual void start_continuous();
	virtual bool is_StartContinuous_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : TTbeckhoff::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(TTbeckhoff::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TTbeckhoff::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::Additional Classes Definitions

}	//	End of namespace

#endif   //	TTbeckhoff_H
