/*----- PROTECTED REGION ID(TTbeckhoffStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        TTbeckhoffStateMachine.cpp
//
// description : State machine file for the TTbeckhoff class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <TTbeckhoff.h>

/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::TTbeckhoffStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  RUNNING  |  
//  ON       |  


namespace TTbeckhoff_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_ContinuousRun_allowed()
 *	Description : Execution allowed for ContinuousRun attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_ContinuousRun_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ContinuousRun attribute in Write access.
	/*----- PROTECTED REGION ID(TTbeckhoff::ContinuousRunStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::ContinuousRunStateAllowed_WRITE

	//	Not any excluded states for ContinuousRun attribute in read access.
	/*----- PROTECTED REGION ID(TTbeckhoff::ContinuousRunStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::ContinuousRunStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_average_allowed()
 *	Description : Execution allowed for average attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_average_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for average attribute in read access.
	/*----- PROTECTED REGION ID(TTbeckhoff::averageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::averageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_min_allowed()
 *	Description : Execution allowed for min attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_min_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for min attribute in read access.
	/*----- PROTECTED REGION ID(TTbeckhoff::minStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::minStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_max_allowed()
 *	Description : Execution allowed for max attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_max_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for max attribute in read access.
	/*----- PROTECTED REGION ID(TTbeckhoff::maxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::maxStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_timetrace_allowed()
 *	Description : Execution allowed for timetrace attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_timetrace_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for timetrace attribute in read access.
	/*----- PROTECTED REGION ID(TTbeckhoff::timetraceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::timetraceStateAllowed_READ
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(TTbeckhoff::StartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_Abort_allowed()
 *	Description : Execution allowed for Abort attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_Abort_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Abort command.
	/*----- PROTECTED REGION ID(TTbeckhoff::AbortStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::AbortStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : TTbeckhoff::is_StartContinuous_allowed()
 *	Description : Execution allowed for StartContinuous attribute
 */
//--------------------------------------------------------
bool TTbeckhoff::is_StartContinuous_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartContinuous command.
	/*----- PROTECTED REGION ID(TTbeckhoff::StartContinuousStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TTbeckhoff::StartContinuousStateAllowed
	return true;
}

}	//	End of namespace
