/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        DoubleInBeckhoffAverage.cpp
//
// description : C++ source for the DoubleInBeckhoffAverage class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               DoubleInBeckhoffAverage are implemented in this file.
//
// project :     DoubleInBeckhoffAverage (cpp version)
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <DoubleInBeckhoffAverage.h>
#include <DoubleInBeckhoffAverageClass.h>

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage.cpp

/**
 *  DoubleInBeckhoffAverage class description:
 *    Reads Double form Beckhoff with averaging
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  Start         |  start
//  Abort         |  abort
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  Value            |  Tango::DevDouble	Scalar
//  IntegrationTime  |  Tango::DevDouble	Scalar
//================================================================

namespace DoubleInBeckhoffAverage_ns
{
/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::namespace_starting

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::DoubleInBeckhoffAverage()
 *	Description: Constructors for a Tango device
 *                implementing the classDoubleInBeckhoffAverage
 */
//--------------------------------------------------------
DoubleInBeckhoffAverage::DoubleInBeckhoffAverage(Tango::DeviceClass *cl, std::string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::constructor_1
}
//--------------------------------------------------------
DoubleInBeckhoffAverage::DoubleInBeckhoffAverage(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::constructor_2
}
//--------------------------------------------------------
DoubleInBeckhoffAverage::DoubleInBeckhoffAverage(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::constructor_3
}
//--------------------------------------------------------
DoubleInBeckhoffAverage::~DoubleInBeckhoffAverage()
{
	delete_device();
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::delete_device()
 *	Description: will be called at device destruction or at init command
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::delete_device()
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::delete_device() " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	delete[] adsPtr;

	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::delete_device
	delete[] attr_Value_read;
	delete[] attr_IntegrationTime_read;
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::init_device()
 *	Description: will be called at device initialization.
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::init_device()
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::init_device() create device " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::init_device_before


	//	Get the device properties from database
	get_device_property();

	attr_Value_read = new Tango::DevDouble[1];
	attr_IntegrationTime_read = new Tango::DevDouble[1];
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	// see declaration in header file: 
	// Tango::DeviceProxy *adsPtr;	
	adsPtr = new Tango::DeviceProxy(adsBridge);
	
	INFO_STREAM << "DoubleInBeckhoffAverage::init_device() for " << beckhoffVariable << " using " << adsBridge << endl;
	
	set_state(Tango::ON);
	set_status("Ready to read average of "+beckhoffVariable+" using "+adsBridge);
	//cout << "Ready to read average of " << beckhoffVariable << " using " << adsBridge << endl;

	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::init_device
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::get_device_property()
 *	Description: Read database to initialize property data members.
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::get_device_property()
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::get_device_property_before


	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("AdsBridge"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffVariable"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffAveraging"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffAverageNum"));
	dev_prop.push_back(Tango::DbDatum("BeckhoffAverageAbort"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);

		//	get instance on DoubleInBeckhoffAverageClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		DoubleInBeckhoffAverageClass	*ds_class =
			(static_cast<DoubleInBeckhoffAverageClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize AdsBridge from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  adsBridge;
		else {
			//	Try to initialize AdsBridge from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  adsBridge;
		}
		//	And try to extract AdsBridge value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  adsBridge;

		//	Try to initialize BeckhoffVariable from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffVariable;
		else {
			//	Try to initialize BeckhoffVariable from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffVariable;
		}
		//	And try to extract BeckhoffVariable value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffVariable;

		//	Try to initialize BeckhoffAveraging from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffAveraging;
		else {
			//	Try to initialize BeckhoffAveraging from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffAveraging;
		}
		//	And try to extract BeckhoffAveraging value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffAveraging;

		//	Try to initialize BeckhoffAverageNum from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffAverageNum;
		else {
			//	Try to initialize BeckhoffAverageNum from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffAverageNum;
		}
		//	And try to extract BeckhoffAverageNum value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffAverageNum;

		//	Try to initialize BeckhoffAverageAbort from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  beckhoffAverageAbort;
		else {
			//	Try to initialize BeckhoffAverageAbort from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  beckhoffAverageAbort;
		}
		//	And try to extract BeckhoffAverageAbort value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  beckhoffAverageAbort;

	}

	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::get_device_property_after
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::always_executed_hook()
 *	Description: method always executed before any command is executed
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::always_executed_hook()
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::always_executed_hook()  " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::always_executed_hook) ENABLED START -----*/
	
	Tango::DeviceData dev_value, dev_result;
	string adsBridgeArgument;
	bool Averaging;
	
	// check if Beckhoff system has finished averaging
	adsBridgeArgument = beckhoffAveraging;
	dev_value << adsBridgeArgument;
	dev_result = adsPtr->command_inout("ReadBool", dev_value);
	dev_result >> Averaging;

	if (Averaging) set_state(Tango::RUNNING);  // should be anyway RUNNING
	else {
		set_state(Tango::ON);
		set_status("Ready to read average of " + beckhoffVariable);
	}
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::read_attr_hardware()
 *	Description: Hardware acquisition for attributes
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::read_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::read_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::write_attr_hardware()
 *	Description: Hardware writing for attributes
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::write_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::write_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute Value related method
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::read_Value(Tango::Attribute &attr)
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::read_Value(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::read_Value) ENABLED START -----*/
	//	Set the attribute value
	
	// general initializations
	Tango::DeviceData dev_value, dev_result;
	string adsBridgeArgument;
	Tango::DevDouble result=-10.0;  // default return value
	
	// read the new average value
	adsBridgeArgument = beckhoffVariable;
	dev_value << adsBridgeArgument;
	dev_result = adsPtr->command_inout("ReadReal", dev_value);
	dev_result >> result;

	// store new value
	attr_Value_read[0] = result;
	attr.set_value(attr_Value_read);
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::read_Value
}
//--------------------------------------------------------
/**
 *	Read attribute IntegrationTime related method
 *	Description: Integration time in s
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::read_IntegrationTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::read_IntegrationTime(Tango::Attribute &attr) entering... " << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::read_IntegrationTime) ENABLED START -----*/
	//	Set the attribute value
	
	// some common declarations
	Tango::DeviceData dev_value, dev_result;
	string adsBridgeArgument;
	const double cyclesPerSecond = 1000.0; // use same number in write_IntegrationTime!

	// read number of averages from Beckhoff system
	Tango::DevLong averagenum;
	adsBridgeArgument = beckhoffAverageNum;
	INFO_STREAM << "DoubleInBeckhoffAverage::read_AverageNumber()  - " << adsBridgeArgument << endl;;
	dev_value << adsBridgeArgument;		
	dev_result = adsPtr->command_inout("ReadShort", dev_value);
	dev_result >> averagenum;

	attr_IntegrationTime_read[0] = ((double)averagenum)/cyclesPerSecond;
	attr.set_value(attr_IntegrationTime_read);

	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::read_IntegrationTime
}
//--------------------------------------------------------
/**
 *	Write attribute IntegrationTime related method
 *	Description: Integration time in s
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::write_IntegrationTime(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::write_IntegrationTime(Tango::WAttribute &attr) entering... " << std::endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::write_IntegrationTime) ENABLED START -----*/
	
	// some common declarations
	Tango::DeviceData dev_value, dev_result;
	string adsBridgeArgument;
	const double cyclesPerSecond = 1000.0; 			// use same number in read_IntegrationTime!
	int numOfCycles = (int)(w_val * cyclesPerSecond);  	// integration time (w_val) always in seconds
	
	// set number of averages on Beckhoff system
	adsBridgeArgument = beckhoffAverageNum + "=" + to_string(numOfCycles);
	INFO_STREAM << "DoubleInBeckhoffAverage::write_AverageNumber()  - " << adsBridgeArgument << endl;;
	dev_value << adsBridgeArgument;		
	dev_result = adsPtr->command_inout("WriteShort", dev_value);

	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::write_IntegrationTime
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::add_dynamic_attributes()
 *	Description: Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command Start related method
 *
 *
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::start()
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::Start()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::start) ENABLED START -----*/
	
	set_state(Tango::RUNNING);
	set_status("Averaging");
		
	string adsBridgeArgument = beckhoffAveraging + "=true";
	Tango::DeviceData dev_value;
	dev_value << adsBridgeArgument;	
	adsPtr->command_inout("WriteBool", dev_value);
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::start
}
//--------------------------------------------------------
/**
 *	Command Abort related method
 *
 *
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::abort()
{
	DEBUG_STREAM << "DoubleInBeckhoffAverage::Abort()  - " << device_name << std::endl;
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::abort) ENABLED START -----*/
	
	string adsBridgeArgument = beckhoffAverageAbort + "=true";
	Tango::DeviceData dev_value;
	dev_value << adsBridgeArgument;	
	adsPtr->command_inout("WriteBool", dev_value);

	set_state(Tango::ON);
	set_status("Aborted last averaging process");

	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::abort
}
//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::add_dynamic_commands()
 *	Description: Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverage::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::add_dynamic_commands) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code to create and add dynamic commands if any
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::add_dynamic_commands
}

/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::namespace_ending) ENABLED START -----*/

//	Additional Methods




/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::namespace_ending
} //	namespace
