/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        DoubleInBeckhoffAverageClass.cpp
//
// description : C++ source for the DoubleInBeckhoffAverageClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the DoubleInBeckhoffAverage once per process.
//
// project :     DoubleInBeckhoff (cpp version)
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <DoubleInBeckhoffAverageClass.h>

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass.cpp

//-------------------------------------------------------------------
/**
 *	Create DoubleInBeckhoffAverageClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_DoubleInBeckhoffAverage_class(const char *name) {
		return DoubleInBeckhoffAverage_ns::DoubleInBeckhoffAverageClass::init(name);
	}
}

namespace DoubleInBeckhoffAverage_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
DoubleInBeckhoffAverageClass *DoubleInBeckhoffAverageClass::_instance = NULL;

//===================================================================
//	Class constants
//===================================================================
//--------------------------------------------------------
/**
 * method : 		DoubleInBeckhoffAverageClass::DoubleInBeckhoffAverageClass(std::string &s)
 * description : 	constructor for the DoubleInBeckhoffAverageClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
DoubleInBeckhoffAverageClass::DoubleInBeckhoffAverageClass(std::string &s):Tango::DeviceClass(s)
{
	TANGO_LOG_INFO << "Entering DoubleInBeckhoffAverageClass constructor" << std::endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::constructor

	TANGO_LOG_INFO << "Leaving DoubleInBeckhoffAverageClass constructor" << std::endl;
}

//--------------------------------------------------------
/**
 * method : 		DoubleInBeckhoffAverageClass::~DoubleInBeckhoffAverageClass()
 * description : 	destructor for the DoubleInBeckhoffAverageClass
 */
//--------------------------------------------------------
DoubleInBeckhoffAverageClass::~DoubleInBeckhoffAverageClass()
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		DoubleInBeckhoffAverageClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
DoubleInBeckhoffAverageClass *DoubleInBeckhoffAverageClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			std::string s(name);
			_instance = new DoubleInBeckhoffAverageClass(s);
		}
		catch (std::bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		DoubleInBeckhoffAverageClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
DoubleInBeckhoffAverageClass *DoubleInBeckhoffAverageClass::instance()
{
	if (_instance == NULL)
	{
		std::cerr << "Class is not initialized !!" << std::endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		StartClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "StartClass::execute(): arrived" << std::endl;
	((static_cast<DoubleInBeckhoffAverage *>(device))->start());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		AbortClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *AbortClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	TANGO_LOG_INFO << "AbortClass::execute(): arrived" << std::endl;
	((static_cast<DoubleInBeckhoffAverage *>(device))->abort());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::get_class_property()
 *	Description: Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum DoubleInBeckhoffAverageClass::get_class_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::get_default_device_property()
 *	Description: Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum DoubleInBeckhoffAverageClass::get_default_device_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::get_default_class_property()
 *	Description: Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum DoubleInBeckhoffAverageClass::get_default_class_property(std::string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::set_default_property()
 *	Description: Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::set_default_property()
{
	std::string	prop_name;
	std::string	prop_desc;
	std::string	prop_def;
	std::vector<std::string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "AdsBridge";
	prop_desc = "Tango path to the ads bridge,e.g. \nhpp-n42/beckhoff/adsBridge";
	prop_def  = "hpp-n42/beckhoff/adsBridge2";
	vect_data.clear();
	vect_data.push_back("hpp-n42/beckhoff/adsBridge2");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffVariable";
	prop_desc = "Variable name on the Beckhoff controller\nput MAIN. in front, e.g.\nMAIN.AverageIn1";
	prop_def  = "MAIN.AverageIn1";
	vect_data.clear();
	vect_data.push_back("MAIN.AverageIn1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffAveraging";
	prop_desc = "Name of the Beckhoff variable to start and inicate averaging process (BOOL)";
	prop_def  = "MAIN.Averaging";
	vect_data.clear();
	vect_data.push_back("MAIN.Averaging");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffAverageNum";
	prop_desc = "Name of the Beckhoff variable indicating the number of averaging processes (INT)";
	prop_def  = "MAIN.AverageNum";
	vect_data.clear();
	vect_data.push_back("MAIN.AverageNum");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "BeckhoffAverageAbort";
	prop_desc = "Name of the Beckhoff variable to abort averaging process (BOOL)";
	prop_def  = "MAIN.AverageAbort";
	vect_data.clear();
	vect_data.push_back("MAIN.AverageAbort");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::write_class_property()
 *	Description: Set class description fields as property in database
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	std::string	classname = get_name();
	std::string	header;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	std::string	str_title("DoubleInBeckhoffAverage");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	std::vector<std::string>	str_desc;
	str_desc.push_back("Reads Double form Beckhoff with averaging");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	std::vector<std::string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::device_factory()
 *	Description: Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		TANGO_LOG_DEBUG << "Device name : " << (*devlist_ptr)[i].in() << std::endl;
		device_list.push_back(new DoubleInBeckhoffAverage(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		DoubleInBeckhoffAverage *dev = static_cast<DoubleInBeckhoffAverage *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::attribute_factory()
 *	Description: Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::attribute_factory([[maybe_unused]] std::vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::attribute_factory_before
	//	Attribute : Value
	ValueAttrib	*value = new ValueAttrib();
	Tango::UserDefaultAttrProp	value_prop;
	//	description	not set for Value
	value_prop.set_label("analogIn");
	value_prop.set_unit("V");
	//	standard_unit	not set for Value
	//	display_unit	not set for Value
	//	format	not set for Value
	//	max_value	not set for Value
	//	min_value	not set for Value
	//	max_alarm	not set for Value
	//	min_alarm	not set for Value
	//	max_warning	not set for Value
	//	min_warning	not set for Value
	//	delta_t	not set for Value
	//	delta_val	not set for Value
	value->set_default_properties(value_prop);
	//	Not Polled
	value->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(value);

	//	Attribute : IntegrationTime
	IntegrationTimeAttrib	*integrationtime = new IntegrationTimeAttrib();
	Tango::UserDefaultAttrProp	integrationtime_prop;
	integrationtime_prop.set_description("Integration time in s");
	integrationtime_prop.set_label("Integration time");
	integrationtime_prop.set_unit("s");
	//	standard_unit	not set for IntegrationTime
	//	display_unit	not set for IntegrationTime
	//	format	not set for IntegrationTime
	integrationtime_prop.set_max_value("32000");
	integrationtime_prop.set_min_value("0");
	//	max_alarm	not set for IntegrationTime
	//	min_alarm	not set for IntegrationTime
	//	max_warning	not set for IntegrationTime
	//	min_warning	not set for IntegrationTime
	//	delta_t	not set for IntegrationTime
	//	delta_val	not set for IntegrationTime
	integrationtime->set_default_properties(integrationtime_prop);
	//	Not Polled
	integrationtime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(integrationtime);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::pipe_factory()
 *	Description: Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::pipe_factory_before) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::pipe_factory_before
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::pipe_factory_after) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::command_factory()
 *	Description: Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::command_factory()
{
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::command_factory_before


	//	Command Start
	StartClass	*pStartCmd =
		new StartClass("Start",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCmd);

	//	Command Abort
	AbortClass	*pAbortCmd =
		new AbortClass("Abort",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pAbortCmd);

	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		DoubleInBeckhoffAverageClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the created attribute list
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::create_static_attribute_list(std::vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		std::string att_name(att_list[i]->get_name());
		std::transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	TANGO_LOG_INFO << defaultAttList.size() << " attributes in default list" << std::endl;

	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		DoubleInBeckhoffAverageClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void DoubleInBeckhoffAverageClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, std::vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((std::string)(*devlist_ptr)[i]).c_str());
		DoubleInBeckhoffAverage *dev = static_cast<DoubleInBeckhoffAverage *> (dev_impl);

		std::vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		std::vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			std::string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			std::vector<std::string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				TANGO_LOG_INFO << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << std::endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverageClass::get_attr_object_by_name()
 *	Description: returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *DoubleInBeckhoffAverageClass::get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname)
{
	std::vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverageClass::Additional Methods
} //	namespace
