/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage.h) ENABLED START -----*/
//=============================================================================
//
// file :        DoubleInBeckhoffAverage.h
//
// description : Include file for the DoubleInBeckhoffAverage class
//
// project :     DoubleInBeckhoffAverage (cpp version)
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef DoubleInBeckhoffAverage_H
#define DoubleInBeckhoffAverage_H

#include <tango.h>

using namespace std;
/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage.h

#ifdef TANGO_LOG
	// cppTango after c934adea (Merge branch 'remove-cout-definition' into 'main', 2022-05-23)
	// nothing to do
#else
	// cppTango 9.3-backports and older
	#define TANGO_LOG       cout
	#define TANGO_LOG_INFO  cout2
	#define TANGO_LOG_DEBUG cout3
#endif // TANGO_LOG

/**
 *  DoubleInBeckhoffAverage class description:
 *    Reads Double form Beckhoff with averaging
 */


namespace DoubleInBeckhoffAverage_ns
{
/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::Additional Class Declarations

class DoubleInBeckhoffAverage : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::Data Members) ENABLED START -----*/

//	Add your own data members

Tango::DeviceProxy *adsPtr;

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::Data Members

//	Device property data members
public:
	//	AdsBridge:	Tango path to the ads bridge,e.g. 
	//  hpp-n42/beckhoff/adsBridge
	std::string	adsBridge;
	//	BeckhoffVariable:	Variable name on the Beckhoff controller
	//  put MAIN. in front, e.g.
	//  MAIN.AverageIn1
	std::string	beckhoffVariable;
	//	BeckhoffAveraging:	Name of the Beckhoff variable to start and inicate averaging process (BOOL)
	std::string	beckhoffAveraging;
	//	BeckhoffAverageNum:	Name of the Beckhoff variable indicating the number of averaging processes (INT)
	std::string	beckhoffAverageNum;
	//	BeckhoffAverageAbort:	Name of the Beckhoff variable to abort averaging process (BOOL)
	std::string	beckhoffAverageAbort;

//	Attribute data members
public:
	Tango::DevDouble	*attr_Value_read;
	Tango::DevDouble	*attr_IntegrationTime_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DoubleInBeckhoffAverage(Tango::DeviceClass *cl,std::string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	DoubleInBeckhoffAverage(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	DoubleInBeckhoffAverage(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~DoubleInBeckhoffAverage();


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method     : DoubleInBeckhoffAverage::read_attr_hardware()
	 *	Description: Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(std::vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method     : DoubleInBeckhoffAverage::write_attr_hardware()
	 *	Description: Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(std::vector<long> &attr_list);

/**
 *	Attribute Value related methods
 *
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Value(Tango::Attribute &attr);
	virtual bool is_Value_allowed(Tango::AttReqType type);
/**
 *	Attribute IntegrationTime related methods
 *	Description: Integration time in s
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_IntegrationTime(Tango::Attribute &attr);
	virtual void write_IntegrationTime(Tango::WAttribute &attr);
	virtual bool is_IntegrationTime_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method     : DoubleInBeckhoffAverage::add_dynamic_attributes()
	 *	Description: Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command Start related method
	 *
	 *
	 */
	virtual void start();
	virtual bool is_Start_allowed(const CORBA::Any &any);
	/**
	 *	Command Abort related method
	 *
	 *
	 */
	virtual void abort();
	virtual bool is_Abort_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method     : DoubleInBeckhoffAverage::add_dynamic_commands()
	 *	Description: Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::Additional Method prototypes
};

/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::Additional Classes Definitions

}	//	End of namespace

#endif   //	DoubleInBeckhoffAverage_H
