/*----- PROTECTED REGION ID(DoubleInBeckhoffAverageStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        DoubleInBeckhoffAverageStateMachine.cpp
//
// description : State machine file for the DoubleInBeckhoffAverage class
//
// project :     DoubleInBeckhoff (cpp version)
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <DoubleInBeckhoffAverage.h>

/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::DoubleInBeckhoffAverageStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  
//  RUNNING  |  


namespace DoubleInBeckhoffAverage_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::is_Value_allowed()
 *	Description: Execution allowed for Value attribute
 */
//--------------------------------------------------------
bool DoubleInBeckhoffAverage::is_Value_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Value attribute in read access.
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::ValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::ValueStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::is_IntegrationTime_allowed()
 *	Description: Execution allowed for IntegrationTime attribute
 */
//--------------------------------------------------------
bool DoubleInBeckhoffAverage::is_IntegrationTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for IntegrationTime attribute in Write access.
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::IntegrationTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::IntegrationTimeStateAllowed_WRITE

	//	Not any excluded states for IntegrationTime attribute in read access.
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::IntegrationTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::IntegrationTimeStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::is_Start_allowed()
 *	Description: Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool DoubleInBeckhoffAverage::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::StartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method     : DoubleInBeckhoffAverage::is_Abort_allowed()
 *	Description: Execution allowed for Abort attribute
 */
//--------------------------------------------------------
bool DoubleInBeckhoffAverage::is_Abort_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Abort command.
	/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::AbortStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::AbortStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(DoubleInBeckhoffAverage::DoubleInBeckhoffAverageStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	DoubleInBeckhoffAverage::DoubleInBeckhoffAverageStateAllowed.AdditionalMethods

}	//	End of namespace
