/*----- PROTECTED REGION ID(SmarActMCS2Motor.h) ENABLED START -----*/
//=============================================================================
//
// file :        SmarActMCS2Motor.h
//
// description : Include file for the SmarActMCS2Motor class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef SmarActMCS2Motor_H
#define SmarActMCS2Motor_H

#include <tango.h>
using namespace std;
#include <SmarActControl.h>
#ifdef _WITHPICO
    #include <SmarActSI.h>
    #include <SmarActSIConstants_PS.h>
#endif
class SmarActMCS2MotorHoldingThread;

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor.h

/**
 *  SmarActMCS2Motor class description:
 *    Motor class for smaract mcs controller.
 *    
 *    The server supports using a Picoscale interferometer as encoder.
 *    If you don`t want or need this call `make PICOSCALESUPPORT=no`.
 *    
 *    If your controller has an IO module added, you will see some additional
 *    attributes on the motor devices
 *    
 *    OutputTriggerMode: 
 *    This attribute specifies the output trigger mode of a motor channel.
 *    Valid values are:
 *    0: constant mode (output trigger does not change)
 *    1: position compare (output trigger will change when the position
 *       changes by a defines increment, cf. attribute PositionCompareIncrement)
 *    2: target reached (output trigger will change when the motor has reached it`s target position)
 *    3: active move (utput trigger will change when the motor starts/stops)
 *    
 *    PositionCompareDirection:
 *    This attribute specifies the position compare direction when having set OutputTriggerMode to 2.
 *    Valid values are:
 *    0: forward direction, the trigger pulse is output when the position value passes the threshold from below.
 *    1: backward direction, the trigger pulse is output when the position value passes the threshold from above.
 *    2: either direction, the trigger pulse is output when the position value passes the threshold from below or above.
 *    
 *    OutputTriggerPolarity:
 *    This attribute specifies the output trigger polarity.
 *    Valid values are:
 *    0: active low (the idle levelis high and a low pulse is generated when the trigger occurs)
 *    1: active high (he idle levelis low and a high pulse is generated when the trigger occurs)
 *    
 *    OutputTriggerPulseWidth:
 *    This attribute specifies the output trigger pulse width.
 *    Valid range is:
 *    
 *    100 ns ... 4 × 10^9 ns
 *    
 *    PositionCompareStartThreshold:
 *    This attribute specifies the position compare start threshold when having set OutputTriggerMode to 2.
 *    As soon as the position passes this threshold in the configured direction (cf. attribute PositionCompareDirection)
 *    an output pulse is generated. Additionally the threshold is incremented by
 *    the value of the atribute PositionCompareIncrement to define the next trigger threshold.
 *    
 *    PositionCompareIncrement:
 *    This attribute specifies the position compare output trigger increment.
 *    Valid range is 1 ... 1 × 10^12 pm or n° (watch out, attribute conversion is taken into account)
 *    
 *    PositionCompareLimitMin:
 *    This attribute specifies the lower limit for the position compare output trigger. The limits
 *    act as an additional gate for the generation of output pulses. Output pulses are only generated
 *    when the current position lies between the configured minimum and maximum limits. Note that
 *    the maximum limit must be configured to a higher value than the minimum limit for the limit
 *    checks to be active. If both limits are set to the same value the checks are disabled and output
 *    pulses are generated according to the configured start threshold, increment and direction.
 *    
 *    PositionCompareLimitMax:
 *    This attribute specifies the upper limit for the position compare output trigger in pm or n°. The
 *    limits act as an additional gate for the generation of output pulses. Output pulses are only gener-
 *    ated when the current position lies between the configured minimum and maximum limits. Note
 *    that the maximum limit must be configured to a higher value than the minimum limit for the limit
 *    checks to be active. If both limits are set to the same value the checks are disabled and output
 *    pulses are generated according to the configured start threshold, increment and direction.
 *    
 *    
 *    For more detailed information on the use of trajectory streaming and the IO modules check the smaract documentation.
 */

namespace SmarActMCS2Motor_ns
{
/*----- PROTECTED REGION ID(SmarActMCS2Motor::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

class EventCallback : public Tango::CallBack
{
    public:
        EventCallback(Tango::DevBoolean& ttydebug, Tango::DevULong& axisnumber) : Tango::CallBack(), _ttydebug(ttydebug), _axisnumber(axisnumber) {}
        ~EventCallback() {}
    private:
        Tango::DevBoolean& _ttydebug;
        Tango::DevULong& _axisnumber;
        virtual void push_event(Tango::EventData* eventData);
};



/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::Additional Class Declarations

class SmarActMCS2Motor : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(SmarActMCS2Motor::Data Members) ENABLED START -----*/

//	Add your own data members
private:
    Tango::DeviceProxy* smarctrl;
    SmarActMCS2MotorHoldingThread* holdingThread;
    Tango::DevULong refType;
    EventCallback* eventCallback;
    int eventID;
    Tango::DevBoolean ttydebug;

    // ---- Settings that must survive an Init command -------------------------
    // init_device() used to reset Conversion to 1 and UnitLimitMin/Max to 0/0
    // every time.  Conversion is the unit scale for every Position read and
    // write (native units are picometer), and min == max == 0 disables the
    // travel-limit check in write_Position -- so an Init silently changed what
    // a position number means AND removed the guard against a bad one.  These
    // attributes are declared memorized, but the memorized value is only
    // replayed at server start-up, not on the Init command.
    //
    // The Init command re-runs delete_device()/init_device() on the *same*
    // object, so plain members survive it.  They are seeded by the in-class
    // initializers below (which run before the constructor body calls
    // init_device()) and updated by the corresponding write_* methods.
    bool             settingsPersisted = false;
    Tango::DevDouble persistedConversion = 1.0;
    Tango::DevDouble persistedUnitLimitMin = 0.0;
    Tango::DevDouble persistedUnitLimitMax = 0.0;


/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::Data Members

//	Device property data members
public:
	//	SmarActMCS2CtrlDevice:	Name of SmarActMCS2Ctrl device
	string	smarActMCS2CtrlDevice;
	//	AxisNumber:	axis index number
	Tango::DevULong	axisNumber;
	//	PicoScaleEncoded:	Set to true, if this axis uses a picoscale interferometer
	//  as encoder (may need server code recompile
	//  with `make PICOSCALESUPPORT=yes`)
	Tango::DevBoolean	picoScaleEncoded;
	//	SensorType:	Normally the sensor type will be configured by Smaract for
	//  the positioners the controller was ordered/delivered with. If
	//  this property is 0 (the default value) we assume that this
	//  is still the case, no modification to the controller-stored
	//  sensor type will be done.
	//  
	//  
	//  If you ever change to a different type of positioner its sensor type
	//  code has to be given to the controller. Check out the type
	//  code from the smaract docs (MCS2PositionerTypes.pdf.gz)
	//  and enter it here. It will be written to the controller at server
	//  start.
	//  Do not forget to run CalibrateAxis once after the server was restarted.
	Tango::DevULong	sensorType;

	bool	mandatoryNotDefined;

//	Attribute data members
public:
	Tango::DevLong	*attr_MoveMode_read;
	Tango::DevLong	*attr_StepAmplitude_read;
	Tango::DevLong	*attr_StepFrequency_read;
	Tango::DevDouble	*attr_Position_read;
	Tango::DevDouble	*attr_Conversion_read;
	Tango::DevDouble	*attr_UnitLimitMin_read;
	Tango::DevDouble	*attr_UnitLimitMax_read;
	Tango::DevBoolean	*attr_AutoZero_read;
	Tango::DevULong	*attr_HoldTime_read;
	Tango::DevLong64	*attr_Speed_read;
	Tango::DevBoolean	*attr_PositionKnown_read;
	Tango::DevULong	*attr_AxisType_read;
	Tango::DevLong	*attr_MaxFrequency_read;
	Tango::DevULong	*attr_SensorType_read;
	Tango::DevLong64	*attr_StepLimitMin_read;
	Tango::DevLong64	*attr_StepLimitMax_read;
	Tango::DevLong	*attr_SensorMode_read;
	Tango::DevLong	*attr_ActuatorMode_read;
	Tango::DevLong64	*attr_Acceleration_read;
	Tango::DevLong64	*attr_FollowingErrorLimit_read;
	Tango::DevBoolean	*attr_SearchDirection_read;
	Tango::DevString	*attr_SensorName_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SmarActMCS2Motor(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SmarActMCS2Motor(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	SmarActMCS2Motor(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~SmarActMCS2Motor() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();

	/*
	 *	Check if mandatory property has been set
	 */
	 void check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop);

//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : SmarActMCS2Motor::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : SmarActMCS2Motor::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute MoveMode related methods
 *	Description: Get/Set move mode. This might mofify meaning and behaviour of Position attribute
 *               
 *               0 : closed loop absolute
 *               1 : closed loop relative
 *               2 : scan mode absolute
 *               3 : scan mode relative
 *               4 : step mode
 *               
 *               
 *               Smaract property: SA_CTL_PKEY_MOVE_MODE
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_MoveMode(Tango::Attribute &attr);
	virtual void write_MoveMode(Tango::WAttribute &attr);
	virtual bool is_MoveMode_allowed(Tango::AttReqType type);
/**
 *	Attribute StepAmplitude related methods
 *	Description: Gets/sets step amplitude for open-loop movements.
 *               Value range: 1 - 65535
 *               65535 corresponds to 100V
 *               
 *               Smaract property: SA_CTL_PKEY_STEP_AMPLITUDE
 *               
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_StepAmplitude(Tango::Attribute &attr);
	virtual void write_StepAmplitude(Tango::WAttribute &attr);
	virtual bool is_StepAmplitude_allowed(Tango::AttReqType type);
/**
 *	Attribute StepFrequency related methods
 *	Description: Gets/sets step frequency for open-loop movements.
 *               Value range: 1 - 20000 Hz
 *               
 *               Smaract property: SA_CTL_PKEY_STEP_FREQUENCY
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_StepFrequency(Tango::Attribute &attr);
	virtual void write_StepFrequency(Tango::WAttribute &attr);
	virtual bool is_StepFrequency_allowed(Tango::AttReqType type);
/**
 *	Attribute Position related methods
 *	Description: Native units are picometer for linear axes and nanodegrees for rotary axes.
 *               Can be changed by adjusting conversion attribute.
 *               
 *               Smaract property  (for reading): SA_CTL_PKEY_POSITION
 *               Smaract command (for writing):  SA_CTL_Move
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Position(Tango::Attribute &attr);
	virtual void write_Position(Tango::WAttribute &attr);
	virtual bool is_Position_allowed(Tango::AttReqType type);
/**
 *	Attribute Conversion related methods
 *	Description: Factor for converting encoder steps to units, defaults to 1
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Conversion(Tango::Attribute &attr);
	virtual void write_Conversion(Tango::WAttribute &attr);
	virtual bool is_Conversion_allowed(Tango::AttReqType type);
/**
 *	Attribute UnitLimitMin related methods
 *	Description: MInimum position in units we are allowed to go to.
 *               If both UnitLimitMin and UnitLimitMax are set to 0 limit settings are ignored.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_UnitLimitMin(Tango::Attribute &attr);
	virtual void write_UnitLimitMin(Tango::WAttribute &attr);
	virtual bool is_UnitLimitMin_allowed(Tango::AttReqType type);
/**
 *	Attribute UnitLimitMax related methods
 *	Description: Maximum position in units we are allowed to go to.
 *               If both UnitLimitMin and UnitLimitMax are set to 0 limit settings are ignored.
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_UnitLimitMax(Tango::Attribute &attr);
	virtual void write_UnitLimitMax(Tango::WAttribute &attr);
	virtual bool is_UnitLimitMax_allowed(Tango::AttReqType type);
/**
 *	Attribute AutoZero related methods
 *	Description: If set to true, the current position will be set to 0 when the reference mark is found
 *               on running the Home command.
 *               
 *               Smaract property: SA_CTL_PKEY_REFERENCING_OPTIONS/SA_CTL_REF_OPT_BIT_AUTO_ZERO
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_AutoZero(Tango::Attribute &attr);
	virtual void write_AutoZero(Tango::WAttribute &attr);
	virtual bool is_AutoZero_allowed(Tango::AttReqType type);
/**
 *	Attribute HoldTime related methods
 *	Description: Closed loop hold time (time in ms the position is actively held after reaching the target posi-
 *               tion)
 *               
 *               Range: 0 - 4294967295 (0 disables holding, max value is for infinite, i.e. hold until motor is stopped)
 *               
 *               Smaract property: SA_CTL_PKEY_HOLD_TIME
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void read_HoldTime(Tango::Attribute &attr);
	virtual void write_HoldTime(Tango::WAttribute &attr);
	virtual bool is_HoldTime_allowed(Tango::AttReqType type);
/**
 *	Attribute Speed related methods
 *	Description: Closed loop velocity, pm s^-1  for linear movements, nanodegree s^?1 for rotary movements
 *               
 *               Range: 0 - 100000000000
 *               
 *               Smaract property depends on MoveMode:
 *               
 *               for closed loop relative/absolute: SA_CTL_PKEY_MOVE_VELOCITY
 *               
 *               for scan mode relative/absolut: SA_CTL_PKEY_SCAN_VELOCITY
 *               
 *               for step mode: not applicable, throws exception
 *               use attributes StepFrequency/StepAmplitude to adjust
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_Speed(Tango::Attribute &attr);
	virtual void write_Speed(Tango::WAttribute &attr);
	virtual bool is_Speed_allowed(Tango::AttReqType type);
/**
 *	Attribute PositionKnown related methods
 *	Description: True, if physical position is known (i.e. Home command ran successfully).
 *               Not applicable in scan mode / step mode, throws exception.
 *               
 *               Smaract property: SA_CTL_PKEY_CHANNEL_STATE/SA_CTL_CH_STATE_BIT_IS_REFERENCED
 *               
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_PositionKnown(Tango::Attribute &attr);
	virtual bool is_PositionKnown_allowed(Tango::AttReqType type);
/**
 *	Attribute AxisType related methods
 *	Description: The axis type,
 *               
 *               0: linear movement
 *               1: rotary movement
 *               2: goniometer
 *               3: tilt movement
 *               
 *               Smaract property: SA_CTL_PKEY_POS_MOVEMENT_TYPE
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void read_AxisType(Tango::Attribute &attr);
	virtual bool is_AxisType_allowed(Tango::AttReqType type);
/**
 *	Attribute MaxFrequency related methods
 *	Description: The maximum closed loop frequency in hz (50 - 20000). If you experience
 *               sudden stops on one axis when starting a movement on another
 *               try setting this to a lower value.
 *               
 *               Smaract property: SA_CTL_PKEY_MAX_CL_FREQUENCY
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_MaxFrequency(Tango::Attribute &attr);
	virtual void write_MaxFrequency(Tango::WAttribute &attr);
	virtual bool is_MaxFrequency_allowed(Tango::AttReqType type);
/**
 *	Attribute SensorType related methods
 *	Description: Sensor type number, check with hardware doc (MCS2PositionerTypes.pdf)
 *               
 *               Smaract property: SA_CTL_PKEY_POSITIONER_TYPE
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void read_SensorType(Tango::Attribute &attr);
	virtual bool is_SensorType_allowed(Tango::AttReqType type);
/**
 *	Attribute StepLimitMin related methods
 *	Description: This attribute uses the controllers ability to store limit values. If this value is set a movement
 *               will stop if this limit is hit.
 *               The attribute does not take conversion into account, it treats values as encoder steps.
 *               
 *               To enable this feature set StepLimitMax to a value greater than StepLimitMin.
 *               
 *               Valid range: -100000000000000 - 100000000000000
 *               
 *               Smaract property: SA_CTL_PKEY_RANGE_LIMIT_MIN
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_StepLimitMin(Tango::Attribute &attr);
	virtual void write_StepLimitMin(Tango::WAttribute &attr);
	virtual bool is_StepLimitMin_allowed(Tango::AttReqType type);
/**
 *	Attribute StepLimitMax related methods
 *	Description: This attribute uses the controllers ability to store limit values. If this value is set a movement
 *               will stop if this limit is hit.
 *               The attribute does not take conversion into account, it treats values as encoder steps.
 *               
 *               To enable this feature set StepLimitMax to a value greater than StepLimitMin.
 *               
 *               Valid range: -100000000000000 - 100000000000000
 *               
 *               Smaract property: SA_CTL_PKEY_RANGE_LIMIT_MAX
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_StepLimitMax(Tango::Attribute &attr);
	virtual void write_StepLimitMax(Tango::WAttribute &attr);
	virtual bool is_StepLimitMax_allowed(Tango::AttReqType type);
/**
 *	Attribute SensorMode related methods
 *	Description: sensor mode
 *                   0: sensor disabled
 *                   1: sensor continuously supplied with power  
 *                   2: sensor power supply pulsed to keep the heat generation low
 *               
 *               Smaract property: SA_CTL_PKEY_SENSOR_POWER_MODE
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_SensorMode(Tango::Attribute &attr);
	virtual void write_SensorMode(Tango::WAttribute &attr);
	virtual bool is_SensorMode_allowed(Tango::AttReqType type);
/**
 *	Attribute ActuatorMode related methods
 *	Description: actuator mode
 *                   0: normal
 *                   1: quiet  
 *                   2: low vibration (needs feature permission activated and payed for)
 *               
 *               Smaract property: SA_CTL_PKEY_ACTUATOR_MODE
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_ActuatorMode(Tango::Attribute &attr);
	virtual void write_ActuatorMode(Tango::WAttribute &attr);
	virtual bool is_ActuatorMode_allowed(Tango::AttReqType type);
/**
 *	Attribute Acceleration related methods
 *	Description: Closed loop acceleration, pm s^?2 for linear positioners and nanodegree s^?2 for rotary positioners
 *               
 *               Range: 0 - 100000000000
 *               
 *               Smaract property:  SA_CTL_PKEY_MOVE_ACCELERATION
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_Acceleration(Tango::Attribute &attr);
	virtual void write_Acceleration(Tango::WAttribute &attr);
	virtual bool is_Acceleration_allowed(Tango::AttReqType type);
/**
 *	Attribute FollowingErrorLimit related methods
 *	Description: Following error limit, pm for linear movements and n° for rotary movements. A value of 0
 *               disables following error detection.
 *               
 *               Range: 0 - 100000000000
 *               
 *               Smaract property: SA_CTL_PKEY_FOLLOWING_ERROR_LIMIT
 *                
 *
 *	Data type:	Tango::DevLong64
 *	Attr type:	Scalar
 */
	virtual void read_FollowingErrorLimit(Tango::Attribute &attr);
	virtual void write_FollowingErrorLimit(Tango::WAttribute &attr);
	virtual bool is_FollowingErrorLimit_allowed(Tango::AttReqType type);
/**
 *	Attribute SearchDirection related methods
 *	Description: Toggling the value will reverse start direction on reference mark search.
 *               
 *               true: search in negative direction
 *               
 *               false: search in positive direction
 *               
 *               The search direction value does not take the sign of the conversion attribute into respect.
 *               
 *               Smaract property: SA_CTL_PKEY_REFERENCING_OPTIONS/SA_CTL_REF_OPT_BIT_START_DIR
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_SearchDirection(Tango::Attribute &attr);
	virtual void write_SearchDirection(Tango::WAttribute &attr);
	virtual bool is_SearchDirection_allowed(Tango::AttReqType type);
/**
 *	Attribute SensorName related methods
 *	Description: Sensor type description, check with hardware doc (MCS2PositionerTypes.pdf)
 *               
 *               Smaract property: SA_CTL_PKEY_POSITIONER_TYPE_NAME
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_SensorName(Tango::Attribute &attr);
	virtual bool is_SensorName_allowed(Tango::AttReqType type);

//	Dynamic attribute methods
public:

	/**
	 *	Attribute PicoDouble related methods
	 *	Description: For internal use only
	 *
	 *	Data type:	Tango::DevDouble
	 *	Attr type:	Scalar
	 */
	virtual void read_PicoDouble(Tango::Attribute &attr);
	virtual bool is_PicoDouble_allowed(Tango::AttReqType type);
	void add_PicoDouble_dynamic_attribute(string attname);
	void remove_PicoDouble_dynamic_attribute(string attname);
	Tango::DevDouble *get_PicoDouble_data_ptr(string &name);
	map<string,Tango::DevDouble>	   PicoDouble_data;

	/**
	 *	Attribute PicoUShort related methods
	 *	Description: For internal use only
	 *
	 *	Data type:	Tango::DevUShort
	 *	Attr type:	Scalar
	 */
	virtual void read_PicoUShort(Tango::Attribute &attr);
	virtual bool is_PicoUShort_allowed(Tango::AttReqType type);
	void add_PicoUShort_dynamic_attribute(string attname);
	void remove_PicoUShort_dynamic_attribute(string attname);
	Tango::DevUShort *get_PicoUShort_data_ptr(string &name);
	map<string,Tango::DevUShort>	   PicoUShort_data;

	/**
	 *	Attribute PicoBoolean related methods
	 *	Description: For internal use only
	 *
	 *	Data type:	Tango::DevBoolean
	 *	Attr type:	Scalar
	 */
	virtual void read_PicoBoolean(Tango::Attribute &attr);
	virtual bool is_PicoBoolean_allowed(Tango::AttReqType type);
	void add_PicoBoolean_dynamic_attribute(string attname);
	void remove_PicoBoolean_dynamic_attribute(string attname);
	Tango::DevBoolean *get_PicoBoolean_data_ptr(string &name);
	map<string,Tango::DevBoolean>	   PicoBoolean_data;

	/**
	 *	Attribute DevLongDynamicAttribute related methods
	 *	Description: 
	 *
	 *	Data type:	Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_DevLongDynamicAttribute(Tango::Attribute &attr);
	virtual void write_DevLongDynamicAttribute(Tango::WAttribute &attr);
	virtual bool is_DevLongDynamicAttribute_allowed(Tango::AttReqType type);
	void add_DevLongDynamicAttribute_dynamic_attribute(string attname);
	void remove_DevLongDynamicAttribute_dynamic_attribute(string attname);
	Tango::DevLong *get_DevLongDynamicAttribute_data_ptr(string &name);
	map<string,Tango::DevLong>	   DevLongDynamicAttribute_data;

	/**
	 *	Attribute DevDoubleDynamicAttribute related methods
	 *	Description: 
	 *
	 *	Data type:	Tango::DevDouble
	 *	Attr type:	Scalar
	 */
	virtual void read_DevDoubleDynamicAttribute(Tango::Attribute &attr);
	virtual void write_DevDoubleDynamicAttribute(Tango::WAttribute &attr);
	virtual bool is_DevDoubleDynamicAttribute_allowed(Tango::AttReqType type);
	void add_DevDoubleDynamicAttribute_dynamic_attribute(string attname);
	void remove_DevDoubleDynamicAttribute_dynamic_attribute(string attname);
	Tango::DevDouble *get_DevDoubleDynamicAttribute_data_ptr(string &name);
	map<string,Tango::DevDouble>	   DevDoubleDynamicAttribute_data;

	/**
	 *	Attribute CWLimit related methods
	 *	Description: 
	 *
	 *	Data type:	Tango::DevBoolean
	 *	Attr type:	Scalar
	 */
	virtual void read_CWLimit(Tango::Attribute &attr);
	virtual bool is_CWLimit_allowed(Tango::AttReqType type);
	void add_CWLimit_dynamic_attribute(string attname);
	void remove_CWLimit_dynamic_attribute(string attname);
	Tango::DevBoolean *get_CWLimit_data_ptr(string &name);
	map<string,Tango::DevBoolean>	   CWLimit_data;

	/**
	 *	Attribute CCWLimit related methods
	 *	Description: 
	 *
	 *	Data type:	Tango::DevBoolean
	 *	Attr type:	Scalar
	 */
	virtual void read_CCWLimit(Tango::Attribute &attr);
	virtual bool is_CCWLimit_allowed(Tango::AttReqType type);
	void add_CCWLimit_dynamic_attribute(string attname);
	void remove_CCWLimit_dynamic_attribute(string attname);
	Tango::DevBoolean *get_CCWLimit_data_ptr(string &name);
	map<string,Tango::DevBoolean>	   CCWLimit_data;

	//--------------------------------------------------------
	/**
	 *	Method      : SmarActMCS2Motor::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command State related method
	 *	Description: This command gets the device state (stored in its device_state data member) and returns it to the caller.
	 *
	 *	@returns Device state
	 */
	virtual Tango::DevState dev_state();
	/**
	 *	Command Home related method
	 *	Description: Drive to reference mark (and set position to 0 if AutoZero ist true)
	 *               
	 *               Smaract command: SA_CTL_Reference
	 *
	 */
	virtual void home();
	virtual bool is_Home_allowed(const CORBA::Any &any);
	/**
	 *	Command CalibrateAxis related method
	 *	Description: performs a calibration routine for a channel
	 *               
	 *               Smaract command: SA_CTL_Calibrate
	 *               
	 *               Mostly needed if you hooked up another positioner to this channel.
	 *
	 */
	virtual void calibrate_axis();
	virtual bool is_CalibrateAxis_allowed(const CORBA::Any &any);
	/**
	 *	Command Stop related method
	 *	Description: Stop movement on this axis (holding will be disabled if in closed loop mode).
	 *               
	 *               Smaract command: SA_CTL_Stop
	 *
	 */
	virtual void stop();
	virtual bool is_Stop_allowed(const CORBA::Any &any);
	/**
	 *	Command Calibrate related method
	 *	Description: Set logical motor position to input value.
	 *
	 *	@param argin Calibration value
	 *	@returns either one or an exception will be thrown
	 */
	virtual Tango::DevLong calibrate(Tango::DevDouble argin);
	virtual bool is_Calibrate_allowed(const CORBA::Any &any);

//	Dynamic commands methods
public:
	/**
	 *	Command CmdVoidVoid related method
	 *	Description: For internal use only
	 *
	 */
	virtual void cmd_void_void(Tango::Command &command);
	virtual bool is_CmdVoidVoid_allowed(const CORBA::Any &any);
	void add_CmdVoidVoid_dynamic_command(string cmdname, bool device);
	void remove_CmdVoidVoid_dynamic_command(string cmdname);

	//--------------------------------------------------------
	/**
	 *	Method      : SmarActMCS2Motor::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(SmarActMCS2Motor::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes
#ifdef _WITHPICO
SA_SI_PropertyKey epk(uint16_t key, uint8_t idxhigh = 0, uint8_t idxlow = 0) {return SA_SI_EPK(key, idxhigh, idxlow);}
#endif

Tango::DevState getEventState();
// protect from pogo
void add_DevLongDynamicAttribute_dynamic_attribute(string attname, string desc);
void add_DevDoubleDynamicAttribute_dynamic_attribute(string attname, string desc);


/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::Additional Method prototypes
};

/*----- PROTECTED REGION ID(SmarActMCS2Motor::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::Additional Classes Definitions

}	//	End of namespace

#endif   //	SmarActMCS2Motor_H
