/*----- PROTECTED REGION ID(SmarActMCS2MotorStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        SmarActMCS2MotorStateMachine.cpp
//
// description : State machine file for the SmarActMCS2Motor class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <SmarActMCS2Motor.h>

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SmarActMCS2MotorStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  MOVING   |  Axis is moving
//  FAULT    |  Something is wrong, check status.
//  ON       |  Everything ok, axis ready to move.
//  RUNNING  |  This will only appear if you use a Picoscale for encoding
//           |  after you called the HoldPosition command, meaning is: the axis
//           |  is holding its position


namespace SmarActMCS2Motor_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_MoveMode_allowed()
 *	Description : Execution allowed for MoveMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_MoveMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MoveMode attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::MoveModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::MoveModeStateAllowed_WRITE

	//	Not any excluded states for MoveMode attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::MoveModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::MoveModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_StepAmplitude_allowed()
 *	Description : Execution allowed for StepAmplitude attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_StepAmplitude_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for StepAmplitude attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepAmplitudeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepAmplitudeStateAllowed_WRITE

	//	Not any excluded states for StepAmplitude attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepAmplitudeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepAmplitudeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_StepFrequency_allowed()
 *	Description : Execution allowed for StepFrequency attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_StepFrequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for StepFrequency attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepFrequencyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepFrequencyStateAllowed_WRITE

	//	Not any excluded states for StepFrequency attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepFrequencyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepFrequencyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Position_allowed()
 *	Description : Execution allowed for Position attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Position_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Position attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::PositionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::PositionStateAllowed_WRITE

	//	Not any excluded states for Position attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::PositionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::PositionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Conversion_allowed()
 *	Description : Execution allowed for Conversion attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Conversion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Conversion attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::ConversionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::ConversionStateAllowed_WRITE

	//	Not any excluded states for Conversion attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::ConversionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::ConversionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_UnitLimitMin_allowed()
 *	Description : Execution allowed for UnitLimitMin attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_UnitLimitMin_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for UnitLimitMin attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::UnitLimitMinStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::UnitLimitMinStateAllowed_WRITE

	//	Not any excluded states for UnitLimitMin attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::UnitLimitMinStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::UnitLimitMinStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_UnitLimitMax_allowed()
 *	Description : Execution allowed for UnitLimitMax attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_UnitLimitMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for UnitLimitMax attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::UnitLimitMaxStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::UnitLimitMaxStateAllowed_WRITE

	//	Not any excluded states for UnitLimitMax attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::UnitLimitMaxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::UnitLimitMaxStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_AutoZero_allowed()
 *	Description : Execution allowed for AutoZero attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_AutoZero_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for AutoZero attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::AutoZeroStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::AutoZeroStateAllowed_WRITE

	//	Not any excluded states for AutoZero attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::AutoZeroStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::AutoZeroStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_HoldTime_allowed()
 *	Description : Execution allowed for HoldTime attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_HoldTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for HoldTime attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::HoldTimeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::HoldTimeStateAllowed_WRITE

	//	Not any excluded states for HoldTime attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::HoldTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::HoldTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Speed_allowed()
 *	Description : Execution allowed for Speed attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Speed_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Speed attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SpeedStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SpeedStateAllowed_WRITE

	//	Not any excluded states for Speed attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SpeedStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SpeedStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_PositionKnown_allowed()
 *	Description : Execution allowed for PositionKnown attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_PositionKnown_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PositionKnown attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::PositionKnownStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::PositionKnownStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_AxisType_allowed()
 *	Description : Execution allowed for AxisType attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_AxisType_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AxisType attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::AxisTypeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::AxisTypeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_MaxFrequency_allowed()
 *	Description : Execution allowed for MaxFrequency attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_MaxFrequency_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for MaxFrequency attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::MaxFrequencyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::MaxFrequencyStateAllowed_WRITE

	//	Not any excluded states for MaxFrequency attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::MaxFrequencyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::MaxFrequencyStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_SensorType_allowed()
 *	Description : Execution allowed for SensorType attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_SensorType_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SensorType attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SensorTypeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SensorTypeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_StepLimitMin_allowed()
 *	Description : Execution allowed for StepLimitMin attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_StepLimitMin_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for StepLimitMin attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepLimitMinStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepLimitMinStateAllowed_WRITE

	//	Not any excluded states for StepLimitMin attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepLimitMinStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepLimitMinStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_StepLimitMax_allowed()
 *	Description : Execution allowed for StepLimitMax attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_StepLimitMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for StepLimitMax attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepLimitMaxStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepLimitMaxStateAllowed_WRITE

	//	Not any excluded states for StepLimitMax attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StepLimitMaxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StepLimitMaxStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_SensorMode_allowed()
 *	Description : Execution allowed for SensorMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_SensorMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SensorMode attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SensorModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SensorModeStateAllowed_WRITE

	//	Not any excluded states for SensorMode attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SensorModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SensorModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_ActuatorMode_allowed()
 *	Description : Execution allowed for ActuatorMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_ActuatorMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for ActuatorMode attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::ActuatorModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::ActuatorModeStateAllowed_WRITE

	//	Not any excluded states for ActuatorMode attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::ActuatorModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::ActuatorModeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Acceleration_allowed()
 *	Description : Execution allowed for Acceleration attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Acceleration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Acceleration attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::AccelerationStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::AccelerationStateAllowed_WRITE

	//	Not any excluded states for Acceleration attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::AccelerationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::AccelerationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_FollowingErrorLimit_allowed()
 *	Description : Execution allowed for FollowingErrorLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_FollowingErrorLimit_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for FollowingErrorLimit attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::FollowingErrorLimitStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::FollowingErrorLimitStateAllowed_WRITE

	//	Not any excluded states for FollowingErrorLimit attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::FollowingErrorLimitStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::FollowingErrorLimitStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_SearchDirection_allowed()
 *	Description : Execution allowed for SearchDirection attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_SearchDirection_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SearchDirection attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SearchDirectionStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SearchDirectionStateAllowed_WRITE

	//	Not any excluded states for SearchDirection attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SearchDirectionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SearchDirectionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_SensorName_allowed()
 *	Description : Execution allowed for SensorName attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_SensorName_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SensorName attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::SensorNameStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SensorNameStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_PicoDouble_allowed()
 *	Description : Execution allowed for PicoDouble attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_PicoDouble_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PicoDouble attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::PicoDoubleStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::PicoDoubleStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_PicoUShort_allowed()
 *	Description : Execution allowed for PicoUShort attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_PicoUShort_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PicoUShort attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::PicoUShortStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::PicoUShortStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_PicoBoolean_allowed()
 *	Description : Execution allowed for PicoBoolean attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_PicoBoolean_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PicoBoolean attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::PicoBooleanStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::PicoBooleanStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_DevLongDynamicAttribute_allowed()
 *	Description : Execution allowed for DevLongDynamicAttribute attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_DevLongDynamicAttribute_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DevLongDynamicAttribute attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::DevLongDynamicAttributeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::DevLongDynamicAttributeStateAllowed_WRITE

	//	Not any excluded states for DevLongDynamicAttribute attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::DevLongDynamicAttributeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::DevLongDynamicAttributeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_DevDoubleDynamicAttribute_allowed()
 *	Description : Execution allowed for DevDoubleDynamicAttribute attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_DevDoubleDynamicAttribute_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for DevDoubleDynamicAttribute attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::DevDoubleDynamicAttributeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::DevDoubleDynamicAttributeStateAllowed_WRITE

	//	Not any excluded states for DevDoubleDynamicAttribute attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::DevDoubleDynamicAttributeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::DevDoubleDynamicAttributeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_CWLimit_allowed()
 *	Description : Execution allowed for CWLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_CWLimit_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CWLimit attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::CWLimitStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::CWLimitStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_CCWLimit_allowed()
 *	Description : Execution allowed for CCWLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_CCWLimit_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CCWLimit attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::CCWLimitStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::CCWLimitStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Home_allowed()
 *	Description : Execution allowed for Home attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Home_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::MOVING ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::HomeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::HomeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_CalibrateAxis_allowed()
 *	Description : Execution allowed for CalibrateAxis attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_CalibrateAxis_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::MOVING ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::CalibrateAxisStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::CalibrateAxisStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::ON)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::StopStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_Calibrate_allowed()
 *	Description : Execution allowed for Calibrate attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_Calibrate_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::MOVING ||
		get_state()==Tango::FAULT ||
		get_state()==Tango::RUNNING)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::CalibrateStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::CalibrateStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Motor::is_CmdVoidVoid_allowed()
 *	Description : Execution allowed for CmdVoidVoid attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Motor::is_CmdVoidVoid_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for CmdVoidVoid command.
	/*----- PROTECTED REGION ID(SmarActMCS2Motor::CmdVoidVoidStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::CmdVoidVoidStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(SmarActMCS2Motor::SmarActMCS2MotorStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Motor::SmarActMCS2MotorStateAllowed.AdditionalMethods

}	//	End of namespace
