/*----- PROTECTED REGION ID(AdsBridge.h) ENABLED START -----*/
//=============================================================================
//
// file :        AdsBridge.h
//
// description : Include for the AdsBridge class.
//
// project :     Ads Bridge.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef ADSBRIDGE_H
#define ADSBRIDGE_H


#include <tango.h>


/*----- PROTECTED REGION END -----*/	//	AdsBridge.h

/**
 *  AdsBridge class description:
 *    This device class implements a simple access point to access PLC variables
 *    of a Beckhoff PLC through ADS.
 */

namespace AdsBridge_ns
{
/*----- PROTECTED REGION ID(AdsBridge::Additional Class Declarations) ENABLED START -----*/

		//		Additional Class Declarations

	/*----- PROTECTED REGION END -----*/	//	AdsBridge::Additional Class Declarations

class AdsBridge : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(AdsBridge::Data Members) ENABLED START -----*/

	void* dcPtr; 
    int netFd;

	/*----- PROTECTED REGION END -----*/	//	AdsBridge::Data Members

//	Device property data members
public:
	//	LocalAmsAddress:	Local AMS address as string, dot separated.
	//  In general this is the local IP number plus .1.1
	//  Notice that this address needs to be told to the Beckhoff
	//  controller through TwinCAT as a ADS route!
	string	localAmsAddress;
	//	PlcAmsAddress:	AMS address of the PLC. It MUST be the IP number plus .1.1
	string	plcAmsAddress;
	//	PlcPort:	Port number of the PLC (typically 801)
	Tango::DevShort	plcPort;


//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	AdsBridge(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	AdsBridge(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	AdsBridge(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */	
	~AdsBridge() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : AdsBridge::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);


	//--------------------------------------------------------
	/**
	 *	Method      : AdsBridge::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();



//	Command related methods
public:
	/**
	 *	Command ReadReal related method
	 *	Description: Read a floating point value by variable name
	 *
	 *	@param argin Variable name
	 *	@returns value of variable
	 */
	virtual Tango::DevDouble read_real(Tango::DevString argin);
	virtual bool is_ReadReal_allowed(const CORBA::Any &any);
	/**
	 *	Command WriteReal related method
	 *	Description: Read a floating point value by variable name
	 *
	 *	@param argin Variable name as string, including setpoint separated by =
	 */
	virtual void write_real(Tango::DevString argin);
	virtual bool is_WriteReal_allowed(const CORBA::Any &any);
	/**
	 *	Command ReadBool related method
	 *	Description: Read a bool value to the PLC (identified by name).
	 *
	 *	@param argin The variable name
	 *	@returns 
	 */
	virtual Tango::DevBoolean read_bool(Tango::DevString argin);
	virtual bool is_ReadBool_allowed(const CORBA::Any &any);
	/**
	 *	Command WriteBool related method
	 *	Description: Write a bool value to the PLC (identified by name).
	 *
	 *	@param argin The variable name + `=` + new value (either true or false)
	 */
	virtual void write_bool(Tango::DevString argin);
	virtual bool is_WriteBool_allowed(const CORBA::Any &any);
	/**
	 *	Command ReadInt related method
	 *	Description: Read an int value by variable name
	 *
	 *	@param argin Variable name
	 *	@returns value of variable
	 */
	virtual Tango::DevLong read_int(Tango::DevString argin);
	virtual bool is_ReadInt_allowed(const CORBA::Any &any);
	/**
	 *	Command WriteInt related method
	 *	Description: Read a int value by variable name
	 *
	 *	@param argin Variable name as string, including setpoint separated by =
	 */
	virtual void write_int(Tango::DevString argin);
	virtual bool is_WriteInt_allowed(const CORBA::Any &any);
	/**
	 *	Command ReadRealArray related method
	 *	Description: Read a floating point array by variable name
	 *
	 *	@param argin Variable name, number of elements
	 *	@returns array values
	 */
	virtual Tango::DevVarDoubleArray *read_real_array(Tango::DevString argin);
	virtual bool is_ReadRealArray_allowed(const CORBA::Any &any);
	/**
	 *	Command ReadLongIntArray related method
	 *	Description: Read array of 32 bit int by variable name
	 *
	 *	@param argin Variable name, number of elements
	 *	@returns array values
	 */
	virtual Tango::DevVarLongArray *read_long_int_array(Tango::DevString argin);
	virtual bool is_ReadLongIntArray_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : AdsBridge::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(AdsBridge::Additional Method prototypes) ENABLED START -----*/

	//	Additional Method prototypes

	/*----- PROTECTED REGION END -----*/	//	AdsBridge::Additional Method prototypes
};

/*----- PROTECTED REGION ID(AdsBridge::Additional Classes Definitions) ENABLED START -----*/

	//	Additional Classes definitions

	/*----- PROTECTED REGION END -----*/	//	AdsBridge::Additional Classes Definitions

}	//	End of namespace

#endif   //	AdsBridge_H
