/*----- PROTECTED REGION ID(AdsBridgeClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        AdsBridgeClass.cpp
//
// description : C++ source for the AdsBridgeClass. A singleton
//               class derived from DeviceClass. It implements the
//               command list and all properties and methods required
//               by the «name» once per process.
//
// project :     Ads Bridge.
//
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// SVN only:
// $HeadURL:  $
//
// CVS only:
// $Source:  $
// $Log:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <AdsBridgeClass.h>

/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass.cpp

//-------------------------------------------------------------------
/**
 *	Create AdsBridgeClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_AdsBridge_class(const char *name) {
		return AdsBridge_ns::AdsBridgeClass::init(name);
	}
}

namespace AdsBridge_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
AdsBridgeClass *AdsBridgeClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		AdsBridgeClass::AdsBridgeClass(string &s)
 * description : 	constructor for the AdsBridgeClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
AdsBridgeClass::AdsBridgeClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering AdsBridgeClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(AdsBridgeClass::constructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::constructor

	cout2 << "Leaving AdsBridgeClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		AdsBridgeClass::~AdsBridgeClass()
 * description : 	destructor for the AdsBridgeClass
 */
//--------------------------------------------------------
AdsBridgeClass::~AdsBridgeClass()
{
	/*----- PROTECTED REGION ID(AdsBridgeClass::destructor) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		AdsBridgeClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
AdsBridgeClass *AdsBridgeClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new AdsBridgeClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}		
	}		
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		AdsBridgeClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
AdsBridgeClass *AdsBridgeClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		ReadRealClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadRealClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ReadRealClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<AdsBridge *>(device))->read_real(argin));
}

//--------------------------------------------------------
/**
 * method : 		WriteRealClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteRealClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "WriteRealClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<AdsBridge *>(device))->write_real(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ReadBoolClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadBoolClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ReadBoolClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<AdsBridge *>(device))->read_bool(argin));
}

//--------------------------------------------------------
/**
 * method : 		WriteBoolClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteBoolClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "WriteBoolClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<AdsBridge *>(device))->write_bool(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ReadIntClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadIntClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ReadIntClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<AdsBridge *>(device))->read_int(argin));
}

//--------------------------------------------------------
/**
 * method : 		WriteIntClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *WriteIntClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "WriteIntClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<AdsBridge *>(device))->write_int(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ReadRealArrayClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadRealArrayClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ReadRealArrayClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<AdsBridge *>(device))->read_real_array(argin));
}

//--------------------------------------------------------
/**
 * method : 		ReadLongIntArrayClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ReadLongIntArrayClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ReadLongIntArrayClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	return insert((static_cast<AdsBridge *>(device))->read_long_int_array(argin));
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum AdsBridgeClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum AdsBridgeClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum AdsBridgeClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void AdsBridgeClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "LocalAmsAddress";
	prop_desc = "Local AMS address as string, dot separated.\nIn general this is the local IP number plus .1.1\nNotice that this address needs to be told to the Beckhoff\ncontroller through TwinCAT as a ADS route!";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PlcAmsAddress";
	prop_desc = "AMS address of the PLC. It MUST be the IP number plus .1.1";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "PlcPort";
	prop_desc = "Port number of the PLC (typically 801)";
	prop_def  = "801";
	vect_data.clear();
	vect_data.push_back("801");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void AdsBridgeClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("Ads Bridge");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("This device class implements a simple access point to access PLC variables");
	str_desc.push_back("of a Beckhoff PLC through ADS.");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("AdsBridge");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void AdsBridgeClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(AdsBridgeClass::device_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new AdsBridge(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		AdsBridge *dev = static_cast<AdsBridge *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(AdsBridgeClass::device_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void AdsBridgeClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(AdsBridgeClass::attribute_factory_before) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::attribute_factory_before
	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(AdsBridgeClass::attribute_factory_after) ENABLED START -----*/

	//	Add your own code

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void AdsBridgeClass::command_factory()
{
	/*----- PROTECTED REGION ID(AdsBridgeClass::command_factory_before) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::command_factory_before


	//	Command ReadReal
	ReadRealClass	*pReadRealCmd =
		new ReadRealClass("ReadReal",
			Tango::DEV_STRING, Tango::DEV_DOUBLE,
			"Variable name",
			"value of variable",
			Tango::OPERATOR);
	command_list.push_back(pReadRealCmd);

	//	Command WriteReal
	WriteRealClass	*pWriteRealCmd =
		new WriteRealClass("WriteReal",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"Variable name as string, including setpoint separated by =",
			"",
			Tango::OPERATOR);
	command_list.push_back(pWriteRealCmd);

	//	Command ReadBool
	ReadBoolClass	*pReadBoolCmd =
		new ReadBoolClass("ReadBool",
			Tango::DEV_STRING, Tango::DEV_BOOLEAN,
			"The variable name",
			"",
			Tango::OPERATOR);
	command_list.push_back(pReadBoolCmd);

	//	Command WriteBool
	WriteBoolClass	*pWriteBoolCmd =
		new WriteBoolClass("WriteBool",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"The variable name + `=` + new value (either true or false)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pWriteBoolCmd);

	//	Command ReadInt
	ReadIntClass	*pReadIntCmd =
		new ReadIntClass("ReadInt",
			Tango::DEV_STRING, Tango::DEV_LONG,
			"Variable name",
			"value of variable",
			Tango::OPERATOR);
	command_list.push_back(pReadIntCmd);

	//	Command WriteInt
	WriteIntClass	*pWriteIntCmd =
		new WriteIntClass("WriteInt",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"Variable name as string, including setpoint separated by =",
			"",
			Tango::OPERATOR);
	command_list.push_back(pWriteIntCmd);

	//	Command ReadRealArray
	ReadRealArrayClass	*pReadRealArrayCmd =
		new ReadRealArrayClass("ReadRealArray",
			Tango::DEV_STRING, Tango::DEVVAR_DOUBLEARRAY,
			"Variable name, number of elements",
			"array values",
			Tango::OPERATOR);
	command_list.push_back(pReadRealArrayCmd);

	//	Command ReadLongIntArray
	ReadLongIntArrayClass	*pReadLongIntArrayCmd =
		new ReadLongIntArrayClass("ReadLongIntArray",
			Tango::DEV_STRING, Tango::DEVVAR_LONGARRAY,
			"Variable name, number of elements",
			"array values",
			Tango::OPERATOR);
	command_list.push_back(pReadLongIntArrayCmd);

	/*----- PROTECTED REGION ID(AdsBridgeClass::command_factory_after) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		AdsBridgeClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list 
 */
//--------------------------------------------------------
void AdsBridgeClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(AdsBridgeClass::create_static_att_list) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		AdsBridgeClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void AdsBridgeClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{	
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		AdsBridge *dev = static_cast<AdsBridge *> (dev_impl);
		
		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(AdsBridgeClass::erase_dynamic_attributes) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : AdsBridgeClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *AdsBridgeClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; it++)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(AdsBridgeClass::Additional Methods) ENABLED START -----*/

	/*----- PROTECTED REGION END -----*/	//	AdsBridgeClass::Additional Methods
} //	namespace
