#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        DoubleOutBeckhoff.py
#
#  Project :     DoubleOutBeckhoff
#
# This file is part of Tango device class.
#
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
#
#
#  $Author :      bla$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["DoubleOutBeckhoff", "DoubleOutBeckhoffClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(DoubleOutBeckhoff.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.additionnal_import

# Device States Description
# No states for this device


class DoubleOutBeckhoff (PyTango.LatestDeviceImpl):
    """"""

    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(DoubleOutBeckhoff.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.global_variables
    def __init__(self, cl, name):
        PyTango.LatestDeviceImpl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        DoubleOutBeckhoff.init_device(self)
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.__init__) ENABLED START -----#
        self.ads = PyTango.DeviceProxy(self.AdsBridge)
        self.set_state(PyTango.DevState.ON)
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.__init__

    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Value_read = 0.0
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.always_executed_hook

    # -------------------------------------------------------------------------
    #    DoubleOutBeckhoff read/write attribute methods
    # -------------------------------------------------------------------------

    def read_Value(self, attr):
        self.debug_stream("In read_Value()")
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.Value_read) ENABLED START -----#
	
        attr.set_value(self.ads.ReadReal(self.BeckhoffVariable))
        
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.Value_read

    def write_Value(self, attr):
        self.debug_stream("In write_Value()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.Value_write) ENABLED START -----#
        self.ads.WriteReal(self.BeckhoffVariable + "=" + str(data))
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.Value_write


    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.read_attr_hardware

    # -------------------------------------------------------------------------
    #    DoubleOutBeckhoff command methods
    # -------------------------------------------------------------------------

    #----- PROTECTED REGION ID(DoubleOutBeckhoff.programmer_methods) ENABLED START -----#
    #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.programmer_methods


class DoubleOutBeckhoffClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(DoubleOutBeckhoff.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.global_class_variables


    #    Class Properties
    class_property_list = {
        }

    #    Device Properties
    device_property_list = {
        'AdsBridge':
            [PyTango.DevString, 
            "Tango path to the ads bridge, e.g.\nhpp-n42/beckhoff/adsBridge",
            ["hpp-n42/beckhoff/adsBridge2"] ,
            ],
        'BeckhoffVariable':
            [PyTango.DevString, 
            "Variable name on the Beckhoff controller\nput MAIN. in front, e.g.\nMAIN.AnalogOut1",
             [],
            ],
        }

    #    Command definitions
    cmd_list = {
        }

    #    Attribute definitions
    attr_list = {
        'Value':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(DoubleOutBeckhoffClass, DoubleOutBeckhoff, 'DoubleOutBeckhoff')
        #----- PROTECTED REGION ID(DoubleOutBeckhoff.add_classes) ENABLED START -----#
        #----- PROTECTED REGION END -----#	//	DoubleOutBeckhoff.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print('-------> An unforeseen exception occurred....', e)


if __name__ == '__main__':
    main()
