/*----- PROTECTED REGION ID(SmarActMCS2Ctrl.h) ENABLED START -----*/
//=============================================================================
//
// file :        SmarActMCS2Ctrl.h
//
// description : Include file for the SmarActMCS2Ctrl class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef SmarActMCS2Ctrl_H
#define SmarActMCS2Ctrl_H

#include <tango.h>
#include <deque>
#include <map>
using namespace std;
#include <SmarActControl.h>
#ifdef _WITHPICO
    #include <SmarActSI.h>
    #include <SmarActSIConstants_PS.h>
#endif


class SmarActMCS2CtrlEventThread;
class SmarActMCS2CtrlTrajectoryThread;

#ifdef _WITHPICO
    class SmarActMCS2CtrlHoldingThread;
#endif

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl.h

/**
 *  SmarActMCS2Ctrl class description:
 *    Controller device server for MCS2 Smaract Control System.
 *    
 *    Commands / attributes of this class should never be called directly,
 *    they are meant to be called from the SmarActMCS2Motor devices.
 *    
 *    If your controller is equipped with an IO module, you will see
 *    an additional attribute:
 *    
 *    IoModuleOutputVoltage:
 *    This attribute specifies the IO module output voltage for the digital outputs.
 *    Valid value are:
 *    0: 3V
 *    1: 5V
 */

namespace SmarActMCS2Ctrl_ns
{
/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::Additional Class Declarations) ENABLED START -----*/


class StreamTarget
{
    public:
        StreamTarget(uint8_t idx, int64_t pos) : _channel(idx), _position(pos) {}
		~StreamTarget() {}
        void        channel(uint8_t idx)     {_channel = idx;}
        uint8_t     channel()               {return _channel;}
        void        position(int64_t pos)   {_position = pos;}
        int64_t     position()              {return _position;}
		uint8_t*    positionData()			{return (uint8_t*) &_position;}
		uint8_t*	channelData()			{return (uint8_t*) &_channel;}
    private:
        int8_t  _channel;
        int64_t _position;
};


typedef std::shared_ptr<StreamTarget> StreamTargetPtr;
typedef std::shared_ptr<vector<StreamTargetPtr>> StreamTargetPtrVector;




class Positioner
{
    public:
        Positioner() : is_enabled(0), p_type(0), p_unit(0) , p_eventType(SA_CTL_EVENT_NONE), p_eventState(SA_CTL_EVENT_NONE), p_conversion(1.0), p_trajectory(false) {}
        int32_t enabled()               {return is_enabled;}
        void    enabled(int32_t b)      {is_enabled = b;}
        int32_t type()                  {return p_type;}
        void    type(int32_t t)         {p_type = t;}
        int32_t unit()                  {return p_unit;}
        void    unit(int32_t u)         {p_unit = u;}
        uint32_t eventType()            {return p_eventType;}
        void    eventType(uint32_t et)  {p_eventType = et;}
        int32_t eventState()            {return p_eventState;}
        void    eventState(int32_t es)  {p_eventState = es;}
		void    conversion(double c)	{p_conversion = c;}
		double  conversion()			{return p_conversion;}
		void   trajectory(bool b)		{p_trajectory = b;}
		bool   trajectory()				{return p_trajectory;}
		int32_t channel()				{return p_channel;}
		void    channel(int32_t c)		{p_channel = c;}
		int64_t	position()				{return p_position;}
		void	position(int64_t p)		{p_position = p;}
		int32_t powerMode()				{return p_powermode;}
		void	powerMode(int32_t p)	{p_powermode = p;}


    private:
        int32_t  is_enabled;
        int32_t  p_type;
        int32_t  p_unit;
        uint32_t p_eventType;
        int32_t  p_eventState;
		double   p_conversion;
		bool	 p_trajectory;
		int32_t  p_channel;
		int64_t	 p_position;
		int32_t	 p_powermode;
};

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::Additional Class Declarations

class SmarActMCS2Ctrl : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::Data Members) ENABLED START -----*/

//	Add your own data members

private:
    Tango::DevBoolean               ttydebug;
    SA_CTL_DeviceHandle_t           handle;
	//SA_CTL_StreamHandle_t 			streamHandle;
    stringstream                    locator;
    SA_CTL_Result_t                 retval;
    int32_t                         nchannels;
    vector<Positioner*>             positioners;
	deque <StreamTargetPtrVector>   trajectoryTargetQueue;
    SmarActMCS2CtrlEventThread*     eventThread;
    omni_mutex                      eventMutex;
	omni_mutex						trajectoryStartMutex;
	omni_condition*					trajectoryStartCondition;
	bool							trajectoryStop;
	bool							trajectoryTerminate;
	bool							trajectory_active;
	SmarActMCS2CtrlTrajectoryThread* trajectoryThread;
	int32_t 						numAxesInTrajectory;
#ifdef _WITHPICO
    SmarActMCS2CtrlHoldingThread*   holdingThread;
    SA_SI_Handle                    pico_handle;
    Tango::DevBoolean               picoConnected;
#endif

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::Data Members

//	Device property data members
public:
	//	HostName:	Hostname / IP address of device
	string	hostName;
	//	PortNumber:	Port number of controller
	string	portNumber;
	//	ConnectType:	either `net` or `usb`
	string	connectType;
	//	USBID:	Usb id of the device
	string	uSBID;
	//	PicoScaleHostName:	If any axis use a Picoscale interferometer as encoder and
	//  the PicoScale is connected via network, put
	//  the Picoscales hostname/ip address here.
	string	picoScaleHostName;
	//	PicoScaleUSBID:	If any axis use a Picoscale interferometer as encoderan
	//  an the Picoscale is connected vi usb, put
	//  the Picoscales usb id here.
	string	picoScaleUSBID;
	//	PicoScaleConnectType:	either `net` or `usb`
	string	picoScaleConnectType;
	//	GlobalInputPresent:	Set this to true if your device sits in a MCS2 19``-rack-housing
	//  with a global input
	Tango::DevBoolean	globalInputPresent;

	bool	mandatoryNotDefined;

//	Attribute data members
public:
	Tango::DevLong	*attr_StreamBaseRate_read;
	Tango::DevLong	*attr_StreamTriggerMode_read;
	Tango::DevLong	*attr_ExternalSyncRate_read;
	Tango::DevLong	*attr_StreamLoadMax_read;
	Tango::DevBoolean	*attr_StreamReady_read;
	Tango::DevBoolean	*attr_StreamStarted_read;
	Tango::DevBoolean	*attr_IOModulePresent_read;
	Tango::DevBoolean	*attr_LinearInterpolation_read;
	Tango::DevULong	*attr_EventInfo_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SmarActMCS2Ctrl(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SmarActMCS2Ctrl(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	SmarActMCS2Ctrl(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~SmarActMCS2Ctrl() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();

	/*
	 *	Check if mandatory property has been set
	 */
	 void check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop);

//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : SmarActMCS2Ctrl::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : SmarActMCS2Ctrl::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute StreamBaseRate related methods
 *	Description: Stream base rate for trajectory streaming.
 *               Range: 10 - 1000 hz
 *               
 *               Smaract property: SA_CTL_PKEY_STREAM_BASE_RATE
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_StreamBaseRate(Tango::Attribute &attr);
	virtual void write_StreamBaseRate(Tango::WAttribute &attr);
	virtual bool is_StreamBaseRate_allowed(Tango::AttReqType type);
/**
 *	Attribute StreamTriggerMode related methods
 *	Description: Stream trigger mode for trajectory streaming:
 *               
 *               0: Direct Mode
 *               1: External Once Mode
 *               2: External Synchronization Mode
 *               3: External
 *               
 *               Check the Smaract docs on the specific meaning of these modes
 *               
 *               Smaract command: SA_CTL_OpenStream
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_StreamTriggerMode(Tango::Attribute &attr);
	virtual void write_StreamTriggerMode(Tango::WAttribute &attr);
	virtual bool is_StreamTriggerMode_allowed(Tango::AttReqType type);
/**
 *	Attribute ExternalSyncRate related methods
 *	Description: External stream synchronization rate in Hz for the trajectory streaming.
 *               May be used to synchronize the internal position streaming clock to an external clock signal.
 *               StreamBaseRate must be a whole-number multiple of the external sync rate.
 *               
 *               Value is ony used when trigger mode is set to external sync ( = 2).
 *               
 *               Smaract property: SA_CTL_PKEY_STREAM_EXT_SYNC_RATE
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_ExternalSyncRate(Tango::Attribute &attr);
	virtual void write_ExternalSyncRate(Tango::WAttribute &attr);
	virtual bool is_ExternalSyncRate_allowed(Tango::AttReqType type);
/**
 *	Attribute StreamLoadMax related methods
 *	Description: Shows the maximum load generated by the current stream in percent. It acts like a peak
 *               detector. The highest load level generated by the currently running stream is
 *               shown. When starting the trajectory streaming  the load value is reset to zero.
 *               
 *               Smaract property: SA_CTL_PKEY_STREAM_LOAD_MAX
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_StreamLoadMax(Tango::Attribute &attr);
	virtual bool is_StreamLoadMax_allowed(Tango::AttReqType type);
/**
 *	Attribute StreamReady related methods
 *	Description: Will change to true when sufficient trajectory stream data have been transmitted
 *               to the controller so streaming an be started.
 *               A change event with value true when the stream is ready and with value
 *               false when the stream is started will be emitted.
 *               
 *               Smaract event:  SA_CTL_EVENT_STREAM_READY
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_StreamReady(Tango::Attribute &attr);
	virtual bool is_StreamReady_allowed(Tango::AttReqType type);
/**
 *	Attribute StreamStarted related methods
 *	Description: Will change to true when the trajectory stream is started and to false
 *               when the stream is finished.
 *               A change event with value true when the stream is started and with value
 *               false when the stream is finished will be emitted.
 *               
 *               Smaract event: SA_CTL_EVENT_STREAM_FINISHED
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_StreamStarted(Tango::Attribute &attr);
	virtual bool is_StreamStarted_allowed(Tango::AttReqType type);
/**
 *	Attribute IOModulePresent related methods
 *	Description: True, if io module is installed in the controller.
 *               
 *               Checked by setting SA_CTL_PKEY_IO_MODULE_OPTIONS
 *               with SA_CTL_IO_MODULE_OPT_BIT_DIGITAL_OUTPUT_ENABLED and evaluating the return code.
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_IOModulePresent(Tango::Attribute &attr);
	virtual bool is_IOModulePresent_allowed(Tango::AttReqType type);
/**
 *	Attribute LinearInterpolation related methods
 *	Description: Enable / disable linear interpolation of path between consecutive stream target positions
 *               true: enabled
 *               false: disabled
 *               
 *               Smaract property: SA_CTL_PKEY_STREAM_OPTIONS/SA_CTL_STREAM_OPT_BIT_INTERPOLATION_DIS
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_LinearInterpolation(Tango::Attribute &attr);
	virtual void write_LinearInterpolation(Tango::WAttribute &attr);
	virtual bool is_LinearInterpolation_allowed(Tango::AttReqType type);
/**
 *	Attribute EventInfo related methods
 *	Description: Used to propagate events from hardware to axis devices:
 *               0: axis index
 *               1: event type
 *               2: further event description
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Spectrum max = 3
 */
	virtual void read_EventInfo(Tango::Attribute &attr);
	virtual bool is_EventInfo_allowed(Tango::AttReqType type);

//	Dynamic attribute methods
public:

	/**
	 *	Attribute I32Property related methods
	 *	Description: For internal use only
	 *
	 *	Data type:	Tango::DevLong
	 *	Attr type:	Scalar
	 */
	virtual void read_I32Property(Tango::Attribute &attr);
	virtual void write_I32Property(Tango::WAttribute &attr);
	virtual bool is_I32Property_allowed(Tango::AttReqType type);
	void add_I32Property_dynamic_attribute(string attname);
	void remove_I32Property_dynamic_attribute(string attname);
	Tango::DevLong *get_I32Property_data_ptr(string &name);
	map<string,Tango::DevLong>	   I32Property_data;

	/**
	 *	Attribute F64Property related methods
	 *	Description: 
	 *
	 *	Data type:	Tango::DevDouble
	 *	Attr type:	Scalar
	 */
	virtual void read_F64Property(Tango::Attribute &attr);
	virtual void write_F64Property(Tango::WAttribute &attr);
	virtual bool is_F64Property_allowed(Tango::AttReqType type);
	void add_F64Property_dynamic_attribute(string attname);
	void remove_F64Property_dynamic_attribute(string attname);
	Tango::DevDouble *get_F64Property_data_ptr(string &name);
	map<string,Tango::DevDouble>	   F64Property_data;

	/**
	 *	Attribute I32Event related methods
	 *	Description: Internal use only
	 *
	 *	Data type:	Tango::DevULong
	 *	Attr type:	Spectrum max = 2
	 */
	virtual void read_I32Event(Tango::Attribute &attr);
	virtual bool is_I32Event_allowed(Tango::AttReqType type);
	void add_I32Event_dynamic_attribute(string attname, Tango::DevULong *ptr=NULL);
	void remove_I32Event_dynamic_attribute(string attname, bool free_it=true);
	Tango::DevULong *get_I32Event_data_ptr(string &name);
	map<string,Tango::DevULong *>	   I32Event_data;

	/**
	 *	Attribute ImageWriteDynAttr related methods
	 *	Description: Data for trajectory movement, must be organized like this:
	 *               
	 *               axis_X position axis_Y position axis_Z position ...
	 *               axis_X position axis_Y position axis_Z position ...
	 *               axis_X position axis_Y position axis_Z position ...
	 *               axis_X position axis_Y position axis_Z position ...
	 *               ...
	 *
	 *	Data type:	Tango::DevDouble
	 *	Attr type:	Image max = 30 x 100000000
	 */
	virtual void write_ImageWriteDynAttr(Tango::WAttribute &attr);
	virtual bool is_ImageWriteDynAttr_allowed(Tango::AttReqType type);
	void add_ImageWriteDynAttr_dynamic_attribute(string attname, Tango::DevDouble *ptr=NULL);
	void remove_ImageWriteDynAttr_dynamic_attribute(string attname, bool free_it=true);
	Tango::DevDouble *get_ImageWriteDynAttr_data_ptr(string &name);
	map<string,Tango::DevDouble *>	   ImageWriteDynAttr_data;

	//--------------------------------------------------------
	/**
	 *	Method      : SmarActMCS2Ctrl::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command AxisState related method
	 *	Description: Returns 16-bit value describing channel state:
	 *               
	 *               0 SA_CTL_CH_STATE_BIT_ACTIVELY_MOVING 0x0001
	 *               1 SA_CTL_CH_STATE_BIT_CLOSED_LOOP_ACTIVE 0x0002
	 *               2 SA_CTL_CH_STATE_BIT_CALIBRATING 0x0004
	 *               3 SA_CTL_CH_STATE_BIT_REFERENCING 0x0008
	 *               4 SA_CTL_CH_STATE_BIT_MOVE_DELAYED 0x0010
	 *               5 SA_CTL_CH_STATE_BIT_SENSOR_PRESENT 0x0020
	 *               6 SA_CTL_CH_STATE_BIT_IS_CALIBRATED 0x0040
	 *               7 SA_CTL_CH_STATE_BIT_IS_REFERENCED 0x0080
	 *               8 SA_CTL_CH_STATE_BIT_END_STOP_REACHED 0x0100
	 *               9 SA_CTL_CH_STATE_BIT_RANGE_LIMIT_REACHED 0x0200
	 *               10 SA_CTL_CH_STATE_BIT_FOLLOWING_LIMIT_REACHED 0x0400
	 *               11 SA_CTL_CH_STATE_BIT_MOVEMENT_FAILED 0x0800
	 *               12 SA_CTL_CH_STATE_BIT_IS_STREAMING 0x1000
	 *               14 SA_CTL_CH_STATE_BIT_OVER_TEMPERATURE 0x4000
	 *               15 SA_CTL_CH_STATE_BIT_REFERENCE_MARK 0x8000
	 *
	 *	@param argin Axis number
	 *	@returns Axis status
	 */
	virtual Tango::DevUShort axis_state(Tango::DevULong argin);
	virtual bool is_AxisState_allowed(const CORBA::Any &any);
	/**
	 *	Command GetPosition related method
	 *	Description: returns current position in encoder steps
	 *
	 *	@param argin Axis number
	 *	@returns Current position
	 */
	virtual Tango::DevLong64 get_position(Tango::DevULong argin);
	virtual bool is_GetPosition_allowed(const CORBA::Any &any);
	/**
	 *	Command SetMoveMode related method
	 *	Description: set move mode
	 *               
	 *               0 : closed loop absolute
	 *               1 : closed loop relative
	 *               2 : scan mode absolute
	 *               3 : scan mode relative
	 *               4 : step mode
	 *
	 *	@param argin 0: axis number
	 *               1: move mode:
	 *               
	 *                - 0 : closed loop absolute
	 *                - 1 : closed loop relative
	 *                - 2 : scan mode absolute
	 *                - 3 : scan mode relative
	 *                - 4 : step mode
	 */
	virtual void set_move_mode(const Tango::DevVarLongArray *argin);
	virtual bool is_SetMoveMode_allowed(const CORBA::Any &any);
	/**
	 *	Command GetMoveMode related method
	 *	Description: get move mode
	 *               
	 *               0 : closed loop absolute
	 *               1 : closed loop relative
	 *               2 : scan mode absolute
	 *               3 : scan mode relative
	 *               4 : step mode
	 *
	 *	@param argin axis number
	 *	@returns move mode:
	 *           
	 *            0 : closed loop absolute
	 *            1 : closed loop relative
	 *            2 : scan mode absolute
	 *            3 : scan mode relative
	 *            4 : step mode
	 */
	virtual Tango::DevLong get_move_mode(Tango::DevULong argin);
	virtual bool is_GetMoveMode_allowed(const CORBA::Any &any);
	/**
	 *	Command GetStepAmplitude related method
	 *	Description: Gets step amplitude for open-loop movements.
	 *               Value range: 1 - 65535
	 *               65535 corresponds to 100V
	 *
	 *	@param argin axis number
	 *	@returns currently set step amplitude
	 */
	virtual Tango::DevLong get_step_amplitude(Tango::DevULong argin);
	virtual bool is_GetStepAmplitude_allowed(const CORBA::Any &any);
	/**
	 *	Command SetStepAmplitude related method
	 *	Description: Sets step amplitude for open-loop movements.
	 *               Value range: 1 - 65535
	 *               65535 corresponds to 100V
	 *
	 *	@param argin 0: axis number
	 *               1: step amplitude
	 */
	virtual void set_step_amplitude(const Tango::DevVarLongArray *argin);
	virtual bool is_SetStepAmplitude_allowed(const CORBA::Any &any);
	/**
	 *	Command GetStepFrequency related method
	 *	Description: Gets step frequency for open-loop movements.
	 *               
	 *               Value range: 1 - 20000 Hz
	 *
	 *	@param argin axis number
	 *	@returns currently set step frequency
	 */
	virtual Tango::DevLong get_step_frequency(Tango::DevULong argin);
	virtual bool is_GetStepFrequency_allowed(const CORBA::Any &any);
	/**
	 *	Command SetStepFrequency related method
	 *	Description: Sets step frequency for open-loop movements.
	 *               Value range: 1 - 20000 Hz
	 *
	 *	@param argin 0: axis number
	 *               1: step frequency
	 */
	virtual void set_step_frequency(const Tango::DevVarLongArray *argin);
	virtual bool is_SetStepFrequency_allowed(const CORBA::Any &any);
	/**
	 *	Command SetPosition related method
	 *	Description: moves axis
	 *               
	 *               the effect of writing a position value depends on the set move mode
	 *
	 *	@param argin 0: Axis number
	 *               1: target position
	 */
	virtual void set_position(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetPosition_allowed(const CORBA::Any &any);
	/**
	 *	Command SetAutoZero related method
	 *	Description: sets auto zero property
	 *
	 *	@param argin 0: axis number
	 *               1: true = set position counter to 0 after reference mark was found
	 *               2: false = do nothing after reference mark was found
	 */
	virtual void set_auto_zero(const Tango::DevVarULongArray *argin);
	virtual bool is_SetAutoZero_allowed(const CORBA::Any &any);
	/**
	 *	Command GetAutoZero related method
	 *	Description: gets auto zero property
	 *
	 *	@param argin 0: axis number
	 *	@returns true = position counter to will be set to 0 after reference mark was found
	 *           false = nothing happens to position counter after reference mark was found
	 */
	virtual Tango::DevBoolean get_auto_zero(Tango::DevULong argin);
	virtual bool is_GetAutoZero_allowed(const CORBA::Any &any);
	/**
	 *	Command GetVelocity related method
	 *	Description: Gets closed loop velocity.
	 *
	 *	@param argin axis number
	 *	@returns currently set closed loop velocity
	 */
	virtual Tango::DevLong64 get_velocity(Tango::DevULong argin);
	virtual bool is_GetVelocity_allowed(const CORBA::Any &any);
	/**
	 *	Command SetVelocity related method
	 *	Description: Sets closed loop velocity
	 *               Value range: 0 - 100000000000
	 *
	 *	@param argin 0: axis number
	 *               1: new closed loop velocity
	 */
	virtual void set_velocity(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetVelocity_allowed(const CORBA::Any &any);
	/**
	 *	Command GetHoldTime related method
	 *	Description: Gets hold time for closed -loop movements.
	 *
	 *	@param argin axis number
	 *	@returns currently set hold time
	 */
	virtual Tango::DevULong get_hold_time(Tango::DevULong argin);
	virtual bool is_GetHoldTime_allowed(const CORBA::Any &any);
	/**
	 *	Command SetHoldTime related method
	 *	Description: Sets hold time (time in ms the position is actively held after reaching the
	 *               target posi-tion) for closed-loop movements.
	 *               Value range: 0 - 4294967295 (0 disables holding,
	 *               max value is for infinite, i.e. hold until motor is stopped)
	 *
	 *	@param argin 0: axis number
	 *               1: hold time
	 */
	virtual void set_hold_time(const Tango::DevVarULongArray *argin);
	virtual bool is_SetHoldTime_allowed(const CORBA::Any &any);
	/**
	 *	Command GetPositionKnown related method
	 *	Description: Finds out whether the physical position of this axis is known.
	 *               If false and the motor has an encoder with reference mark,
	 *               run command `Home`.
	 *
	 *	@param argin axis number
	 *	@returns true: physical position is known
	 *           false: physical position is not known
	 */
	virtual Tango::DevBoolean get_position_known(Tango::DevULong argin);
	virtual bool is_GetPositionKnown_allowed(const CORBA::Any &any);
	/**
	 *	Command GetAxisType related method
	 *	Description: 
	 *
	 *	@param argin axis number
	 *	@returns axis type:
	 *           
	 *           0: linear movement
	 *           1: rotary movement
	 *           2: goniometer
	 *           3: tilt movement
	 */
	virtual Tango::DevULong get_axis_type(Tango::DevULong argin);
	virtual bool is_GetAxisType_allowed(const CORBA::Any &any);
	/**
	 *	Command GetMaxFrequency related method
	 *	Description: Gets maximumfrequency for closed-loop movements.
	 *
	 *	@param argin axis number
	 *	@returns currently set maximum closed loop frequency
	 */
	virtual Tango::DevLong get_max_frequency(Tango::DevULong argin);
	virtual bool is_GetMaxFrequency_allowed(const CORBA::Any &any);
	/**
	 *	Command SetMaxFrequency related method
	 *	Description: Sets maximum frequency for closed-loop movements.
	 *               Value range: 50 - 20000 Hz
	 *
	 *	@param argin 0: axis number
	 *               1: maximum closed loop  frequency
	 */
	virtual void set_max_frequency(const Tango::DevVarLongArray *argin);
	virtual bool is_SetMaxFrequency_allowed(const CORBA::Any &any);
	/**
	 *	Command GetSensorType related method
	 *	Description: Get sensor type number, check with hardware doc
	 *
	 *	@param argin axis number
	 *	@returns Sensor type number
	 */
	virtual Tango::DevULong get_sensor_type(Tango::DevULong argin);
	virtual bool is_GetSensorType_allowed(const CORBA::Any &any);
	/**
	 *	Command GetMaxStepLimit related method
	 *	Description: 
	 *
	 *	@param argin axis number
	 *	@returns currently set range limit maximum
	 */
	virtual Tango::DevLong64 get_max_step_limit(Tango::DevULong argin);
	virtual bool is_GetMaxStepLimit_allowed(const CORBA::Any &any);
	/**
	 *	Command GetMinStepLimit related method
	 *	Description: 
	 *
	 *	@param argin axis number
	 *	@returns currently set range limit minimum
	 */
	virtual Tango::DevLong64 get_min_step_limit(Tango::DevULong argin);
	virtual bool is_GetMinStepLimit_allowed(const CORBA::Any &any);
	/**
	 *	Command SetMaxStepLimit related method
	 *	Description: 
	 *
	 *	@param argin 0: axis number
	 *               1: maximum range limit
	 */
	virtual void set_max_step_limit(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetMaxStepLimit_allowed(const CORBA::Any &any);
	/**
	 *	Command SetMinStepLimit related method
	 *	Description: 
	 *
	 *	@param argin 0: axis number
	 *               1: minimum range limit
	 */
	virtual void set_min_step_limit(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetMinStepLimit_allowed(const CORBA::Any &any);
	/**
	 *	Command Calibrate related method
	 *	Description: Perform calibration for channnel <axis number>. Should only be necessary
	 *               if setup was changed (e.g. new / different positioner connected).
	 *               Requires encoded positioner, encoder has to be enabled.
	 *
	 *	@param argin axis number
	 */
	virtual void calibrate(Tango::DevULong argin);
	virtual bool is_Calibrate_allowed(const CORBA::Any &any);
	/**
	 *	Command SetCalibrationOptions related method
	 *	Description: Set calibration option (used with Calibrate command)
	 *               
	 *               bit 0: Direction
	 *               bit 1: Detect Distance Code Inversion
	 *               bit 2: Advanced Sensor Correction
	 *               bit 8: Limited Travel Range
	 *               
	 *               all other bits are reserved
	 *
	 *	@param argin 0: axis number
	 *               1: calibration options bit field
	 */
	virtual void set_calibration_options(const Tango::DevVarULongArray *argin);
	virtual bool is_SetCalibrationOptions_allowed(const CORBA::Any &any);
	/**
	 *	Command GetCalibrationOptions related method
	 *	Description: Get calibration option (used with Calibrate command)
	 *               
	 *               bit 0: Direction
	 *               bit 1: Detect Distance Code Inversion
	 *               bit 2: Advanced Sensor Correction
	 *               bit 8: Limited Travel Range
	 *               
	 *               all other bits are reserved
	 *
	 *	@param argin axis number
	 *	@returns currently set calibration options
	 */
	virtual Tango::DevULong get_calibration_options(Tango::DevULong argin);
	virtual bool is_GetCalibrationOptions_allowed(const CORBA::Any &any);
	/**
	 *	Command HoldPosition related method
	 *	Description: Enables holding the current position by setting the move mode to
	 *               closed loop relative movement and then driving by 0 encoder steps.
	 *               (c.f. programmer manual, 2.6.4)
	 *
	 *	@param argin axis number
	 */
	virtual void hold_position(Tango::DevULong argin);
	virtual bool is_HoldPosition_allowed(const CORBA::Any &any);
	/**
	 *	Command Stop related method
	 *	Description: Stop movement on axis <axis number>
	 *
	 *	@param argin axis number
	 */
	virtual void stop(Tango::DevULong argin);
	virtual bool is_Stop_allowed(const CORBA::Any &any);
	/**
	 *	Command SetSensorMode related method
	 *	Description: 
	 *
	 *	@param argin 0: axis number
	 *               1: sensor mode
	 *                   0: sensor disabled
	 *                   1: sensor continuously supplied with power  
	 *                   2: sensor power supply pulsed to keep the heat generation low
	 */
	virtual void set_sensor_mode(const Tango::DevVarLongArray *argin);
	virtual bool is_SetSensorMode_allowed(const CORBA::Any &any);
	/**
	 *	Command GetSensorMode related method
	 *	Description: 
	 *
	 *	@param argin axis number
	 *	@returns sensor mode
	 *               0: sensor disabled
	 *               1: sensor continuously supplied with power  
	 *               2: sensor power supply pulsed to keep the heat generation low
	 */
	virtual Tango::DevLong get_sensor_mode(Tango::DevULong argin);
	virtual bool is_GetSensorMode_allowed(const CORBA::Any &any);
	/**
	 *	Command GetAcceleration related method
	 *	Description: Gets closed loop acceleration
	 *
	 *	@param argin axis number
	 *	@returns currently set closed loop acceleration
	 */
	virtual Tango::DevLong64 get_acceleration(Tango::DevULong argin);
	virtual bool is_GetAcceleration_allowed(const CORBA::Any &any);
	/**
	 *	Command SetAcceleration related method
	 *	Description: Sets closed loop acceleration
	 *
	 *	@param argin 0: axis number
	 *               1: new closed loop acceleration
	 */
	virtual void set_acceleration(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetAcceleration_allowed(const CORBA::Any &any);
	/**
	 *	Command GetActuatorMode related method
	 *	Description: Gets currently set actuator mode
	 *
	 *	@param argin axis number
	 *	@returns currently set actuator mode
	 */
	virtual Tango::DevLong get_actuator_mode(Tango::DevULong argin);
	virtual bool is_GetActuatorMode_allowed(const CORBA::Any &any);
	/**
	 *	Command SetActuatorMode related method
	 *	Description: 
	 *
	 *	@param argin 0: axis number
	 *               1: actuator mode
	 */
	virtual void set_actuator_mode(const Tango::DevVarLongArray *argin);
	virtual bool is_SetActuatorMode_allowed(const CORBA::Any &any);
	/**
	 *	Command Home related method
	 *	Description: 
	 *
	 *	@param argin axis number
	 */
	virtual void home(Tango::DevULong argin);
	virtual bool is_Home_allowed(const CORBA::Any &any);
	/**
	 *	Command GetFollowingErrorLimit related method
	 *	Description: Gets currently set following error limit
	 *
	 *	@param argin axis number
	 *	@returns currently set following error limit
	 */
	virtual Tango::DevLong64 get_following_error_limit(Tango::DevULong argin);
	virtual bool is_GetFollowingErrorLimit_allowed(const CORBA::Any &any);
	/**
	 *	Command SetFollowingErrorLimit related method
	 *	Description: Sets following error limit
	 *               Value range: 0 - 100000000000000
	 *
	 *	@param argin 0: axis number
	 *               1: new following error limit
	 */
	virtual void set_following_error_limit(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetFollowingErrorLimit_allowed(const CORBA::Any &any);
	/**
	 *	Command StartStreaming related method
	 *	Description: Start trajectory streaming.
	 *               
	 *               Make sure attribute TrajectoryData has been written before calling this.
	 *               
	 *               Smaract commands: SA_CTL_OpenStream/SA_CTL_StreamFrame/SA_CTL_CloseStream
	 *
	 */
	virtual void start_streaming();
	virtual bool is_StartStreaming_allowed(const CORBA::Any &any);
	/**
	 *	Command SetSearchDirection related method
	 *	Description: sets search direction property
	 *
	 *	@param argin 0: axis number
	 *               1: toggling true / false will reverse search direction on reference mark search
	 */
	virtual void set_search_direction(const Tango::DevVarULongArray *argin);
	virtual bool is_SetSearchDirection_allowed(const CORBA::Any &any);
	/**
	 *	Command GetSearchDirection related method
	 *	Description: gets search direction property
	 *
	 *	@param argin 0: axis number
	 *	@returns 
	 */
	virtual Tango::DevBoolean get_search_direction(Tango::DevULong argin);
	virtual bool is_GetSearchDirection_allowed(const CORBA::Any &any);
	/**
	 *	Command GetSensorName related method
	 *	Description: Get description of sensor type number, check with hardware doc
	 *
	 *	@param argin axis number
	 *	@returns Sensor type name
	 */
	virtual Tango::DevString get_sensor_name(Tango::DevULong argin);
	virtual bool is_GetSensorName_allowed(const CORBA::Any &any);
	/**
	 *	Command GetSensorReferenceType related method
	 *	Description: Get sensor reference mark type:
	 *               
	 *               no reference mark: 0
	 *               end stop:                1
	 *               single mark:            2
	 *               distance coded:      3
	 *
	 *	@param argin axis number
	 *	@returns Sensor reference mark type
	 */
	virtual Tango::DevULong get_sensor_reference_type(Tango::DevULong argin);
	virtual bool is_GetSensorReferenceType_allowed(const CORBA::Any &any);
	/**
	 *	Command SetConversion related method
	 *	Description: Internal use only
	 *
	 *	@param argin 0: axis number
	 *               1: conversion factor if this axis
	 */
	virtual void set_conversion(const Tango::DevVarDoubleArray *argin);
	virtual bool is_SetConversion_allowed(const CORBA::Any &any);
	/**
	 *	Command AbortStreaming related method
	 *	Description: Immediately abort trajectory streaming.
	 *               
	 *               Smaract command: SA_CTL_AbortStream
	 *
	 */
	virtual void abort_streaming();
	virtual bool is_AbortStreaming_allowed(const CORBA::Any &any);
	/**
	 *	Command SetSensorType related method
	 *	Description: Sets sensort type code (use with care!)
	 *
	 *	@param argin 0: axis number
	 *               1: sensor type code (cf. Smaract docs). Use with care, setting a wrong sensortype
	 *               may damagage hardware
	 */
	virtual void set_sensor_type(const Tango::DevVarULongArray *argin);
	virtual bool is_SetSensorType_allowed(const CORBA::Any &any);
	/**
	 *	Command SetOffset related method
	 *	Description: Set logical scale offset in encoder steps (Property SASA_CTL_PKEY_LOGICAL_SCALE_OFFSET)
	 *
	 *	@param argin 0: Axis number
	 *               1: offset value
	 */
	virtual void set_offset(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetOffset_allowed(const CORBA::Any &any);
	/**
	 *	Command GetOffset related method
	 *	Description: returns current logical scale offset  (Property SASA_CTL_PKEY_LOGICAL_SCALE_OFFSET)
	 *
	 *	@param argin Axis number
	 *	@returns Currently set offset
	 */
	virtual Tango::DevLong64 get_offset(Tango::DevULong argin);
	virtual bool is_GetOffset_allowed(const CORBA::Any &any);
	/**
	 *	Command SetOffsetAbsolute related method
	 *	Description: Since it`s almost impossible to set the offset to a precise value using
	 *               the axis devices Calibrate command (because the positioner will
	 *               constantly waggle a bit and the current position is used to 
	 *               calculate the offset) you can use this to set the offset to an absolute value.
	 *
	 *	@param argin 0: Axis number
	 *               1: offset value
	 */
	virtual void set_offset_absolute(const Tango::DevVarLong64Array *argin);
	virtual bool is_SetOffsetAbsolute_allowed(const CORBA::Any &any);

//	Dynamic commands methods
public:
	/**
	 *	Command CmdGetDouble related method
	 *	Description: For internal use only
	 *
	 *	@param argin 0: channel idx
	 *               1: source idx
	 *	@returns value
	 */
	virtual Tango::DevDouble cmd_get_double(const Tango::DevVarLongArray *argin,Tango::Command &command);
	virtual bool is_CmdGetDouble_allowed(const CORBA::Any &any);
	void add_CmdGetDouble_dynamic_command(string cmdname, bool device);
	void remove_CmdGetDouble_dynamic_command(string cmdname);
	/**
	 *	Command CmdGetUShort related method
	 *	Description: For internal use only
	 *
	 *	@param argin 0: channel idx
	 *               1: source idx
	 *	@returns value
	 */
	virtual Tango::DevUShort cmd_get_ushort(const Tango::DevVarLongArray *argin,Tango::Command &command);
	virtual bool is_CmdGetUShort_allowed(const CORBA::Any &any);
	void add_CmdGetUShort_dynamic_command(string cmdname, bool device);
	void remove_CmdGetUShort_dynamic_command(string cmdname);
	/**
	 *	Command CmdGetI32Property related method
	 *	Description: For internal use only
	 *
	 *	@param argin property key
	 *	@returns value
	 */
	virtual Tango::DevLong cmd_get_i32_property(Tango::DevLong argin,Tango::Command &command);
	virtual bool is_CmdGetI32Property_allowed(const CORBA::Any &any);
	void add_CmdGetI32Property_dynamic_command(string cmdname, bool device);
	void remove_CmdGetI32Property_dynamic_command(string cmdname);
	/**
	 *	Command CmdLongLong related method
	 *	Description: 
	 *
	 *	@param argin 
	 *	@returns 
	 */
	virtual Tango::DevLong cmd_long_long(Tango::DevLong argin,Tango::Command &command);
	virtual bool is_CmdLongLong_allowed(const CORBA::Any &any);
	void add_CmdLongLong_dynamic_command(string cmdname, bool device);
	void remove_CmdLongLong_dynamic_command(string cmdname);
	/**
	 *	Command CmdLongArrayVoid related method
	 *	Description: Internal use only
	 *
	 *	@param argin 0: axis number
	 *               1: property key
	 *               2: value
	 */
	virtual void cmd_long_array_void(const Tango::DevVarLongArray *argin,Tango::Command &command);
	virtual bool is_CmdLongArrayVoid_allowed(const CORBA::Any &any);
	void add_CmdLongArrayVoid_dynamic_command(string cmdname, bool device);
	void remove_CmdLongArrayVoid_dynamic_command(string cmdname);
	/**
	 *	Command CmdLongLong64 related method
	 *	Description: 
	 *
	 *	@param argin 
	 *	@returns 
	 */
	virtual Tango::DevLong64 cmd_long_long64(Tango::DevLong argin,Tango::Command &command);
	virtual bool is_CmdLongLong64_allowed(const CORBA::Any &any);
	void add_CmdLongLong64_dynamic_command(string cmdname, bool device);
	void remove_CmdLongLong64_dynamic_command(string cmdname);
	/**
	 *	Command CmdLong64ArrayVoid related method
	 *	Description: 
	 *
	 *	@param argin 
	 */
	virtual void cmd_long64_array_void(const Tango::DevVarLong64Array *argin,Tango::Command &command);
	virtual bool is_CmdLong64ArrayVoid_allowed(const CORBA::Any &any);
	void add_CmdLong64ArrayVoid_dynamic_command(string cmdname, bool device);
	void remove_CmdLong64ArrayVoid_dynamic_command(string cmdname);
	/**
	 *	Command CmdLongArrayLong related method
	 *	Description: Internal use only
	 *
	 *	@param argin 0: axis number
	 *               1: property key
	 *	@returns property value
	 */
	virtual Tango::DevLong cmd_long_array_long(const Tango::DevVarLongArray *argin,Tango::Command &command);
	virtual bool is_CmdLongArrayLong_allowed(const CORBA::Any &any);
	void add_CmdLongArrayLong_dynamic_command(string cmdname, bool device);
	void remove_CmdLongArrayLong_dynamic_command(string cmdname);

	//--------------------------------------------------------
	/**
	 *	Method      : SmarActMCS2Ctrl::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes
private:
    void 				makeLocator(string& _hostname, string& _usbid, string& _connecttype, stringstream& _locator, Tango::DevLong portNumber = 0);
    void                getPositionerInfo();
#ifdef _WITHPICO
    SA_SI_PropertyKey epk(uint16_t key, uint8_t idxhigh = 0, uint8_t idxlow = 0) {return SA_SI_EPK(key, idxhigh, idxlow);}
#endif
public:
    void getProperty(int8_t idx, SA_CTL_PropertyKey_t pkey, int32_t *value, size_t *ioArraySize = NULL);
    void setProperty(int8_t idx, SA_CTL_PropertyKey_t pkey, int32_t value);
    void getProperty(int8_t idx, SA_CTL_PropertyKey_t pkey, int64_t *value, size_t *ioArraySize = NULL);
    void setProperty(int8_t idx, SA_CTL_PropertyKey_t pkey, int64_t value);
    void getProperty(int8_t idx, SA_CTL_PropertyKey_t pkey, char *value, size_t ioArraySize);
    void setProperty(int8_t idx, SA_CTL_PropertyKey_t pkey, const char *value);
    void updateEventState(int8_t idx, uint32_t evType, int32_t evState);
	void streamReady(bool b);
	bool streamReady()		{return *attr_StreamReady_read;}
	void streamStarted(bool b);
	bool streamStarted()	{return *attr_StreamStarted_read;}
	void positionersReset();
	void checkBaseRate();
	void trajectoryActive(bool b)	{trajectory_active = b;}
	bool trajectoryActive()			{return trajectory_active;}
	// protect from pogo
	void add_I32Property_dynamic_attribute(string attname, const char* desc = NULL);
	void add_ImageWriteDynAttr_dynamic_attribute(string attname, string desc, Tango::DevDouble *ptr=NULL);

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::Additional Method prototypes
};

/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::Additional Classes Definitions

}	//	End of namespace

#endif   //	SmarActMCS2Ctrl_H
