/*----- PROTECTED REGION ID(SmarActMCS2CtrlStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        SmarActMCS2CtrlStateMachine.cpp
//
// description : State machine file for the SmarActMCS2Ctrl class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <SmarActMCS2Ctrl.h>

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SmarActMCS2CtrlStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  Everything ok.
//  FAULT   |  Something is wrong, check status.
//  OFF     |  Device is turned off or disconnected.


namespace SmarActMCS2Ctrl_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_StreamBaseRate_allowed()
 *	Description : Execution allowed for StreamBaseRate attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_StreamBaseRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamBaseRateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamBaseRateStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamBaseRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamBaseRateStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_StreamTriggerMode_allowed()
 *	Description : Execution allowed for StreamTriggerMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_StreamTriggerMode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamTriggerModeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamTriggerModeStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamTriggerModeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamTriggerModeStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_ExternalSyncRate_allowed()
 *	Description : Execution allowed for ExternalSyncRate attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_ExternalSyncRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::ExternalSyncRateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::ExternalSyncRateStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::ExternalSyncRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::ExternalSyncRateStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_StreamLoadMax_allowed()
 *	Description : Execution allowed for StreamLoadMax attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_StreamLoadMax_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamLoadMaxStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamLoadMaxStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_StreamReady_allowed()
 *	Description : Execution allowed for StreamReady attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_StreamReady_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamReadyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamReadyStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_StreamStarted_allowed()
 *	Description : Execution allowed for StreamStarted attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_StreamStarted_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StreamStartedStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StreamStartedStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_IOModulePresent_allowed()
 *	Description : Execution allowed for IOModulePresent attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_IOModulePresent_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::IOModulePresentStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::IOModulePresentStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_LinearInterpolation_allowed()
 *	Description : Execution allowed for LinearInterpolation attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_LinearInterpolation_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for LinearInterpolation attribute in Write access.
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::LinearInterpolationStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::LinearInterpolationStateAllowed_WRITE

	//	Not any excluded states for LinearInterpolation attribute in read access.
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::LinearInterpolationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::LinearInterpolationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_EventInfo_allowed()
 *	Description : Execution allowed for EventInfo attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_EventInfo_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::EventInfoStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::EventInfoStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_I32Property_allowed()
 *	Description : Execution allowed for I32Property attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_I32Property_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::I32PropertyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::I32PropertyStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::I32PropertyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::I32PropertyStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_F64Property_allowed()
 *	Description : Execution allowed for F64Property attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_F64Property_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::F64PropertyStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::F64PropertyStateAllowed_WRITE
			return false;
		}
		return true;
	}
	else

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::F64PropertyStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::F64PropertyStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_I32Event_allowed()
 *	Description : Execution allowed for I32Event attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_I32Event_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Check access type.
	if ( type==Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for READ 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::I32EventStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::I32EventStateAllowed_READ
			return false;
		}
		return true;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_ImageWriteDynAttr_allowed()
 *	Description : Execution allowed for ImageWriteDynAttr attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_ImageWriteDynAttr_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Check access type.
	if ( type!=Tango::READ_REQ )
	{
		//	Compare device state with not allowed states for WRITE 
		if (get_state()==Tango::FAULT ||
			get_state()==Tango::OFF)
		{
		/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::ImageWriteDynAttrStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::ImageWriteDynAttrStateAllowed_WRITE
			return false;
		}
		return true;
	}

	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_AxisState_allowed()
 *	Description : Execution allowed for AxisState attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_AxisState_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::AxisStateStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::AxisStateStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetPosition_allowed()
 *	Description : Execution allowed for GetPosition attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetPosition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetPositionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetPositionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetMoveMode_allowed()
 *	Description : Execution allowed for SetMoveMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetMoveMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetMoveModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetMoveModeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetMoveMode_allowed()
 *	Description : Execution allowed for GetMoveMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetMoveMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetMoveModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetMoveModeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetStepAmplitude_allowed()
 *	Description : Execution allowed for GetStepAmplitude attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetStepAmplitude_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetStepAmplitudeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetStepAmplitudeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetStepAmplitude_allowed()
 *	Description : Execution allowed for SetStepAmplitude attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetStepAmplitude_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetStepAmplitudeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetStepAmplitudeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetStepFrequency_allowed()
 *	Description : Execution allowed for GetStepFrequency attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetStepFrequency_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetStepFrequencyStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetStepFrequencyStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetStepFrequency_allowed()
 *	Description : Execution allowed for SetStepFrequency attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetStepFrequency_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetStepFrequencyStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetStepFrequencyStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetPosition_allowed()
 *	Description : Execution allowed for SetPosition attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetPosition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetPositionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetPositionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetAutoZero_allowed()
 *	Description : Execution allowed for SetAutoZero attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetAutoZero_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetAutoZeroStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetAutoZeroStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetAutoZero_allowed()
 *	Description : Execution allowed for GetAutoZero attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetAutoZero_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetAutoZeroStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetAutoZeroStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetVelocity_allowed()
 *	Description : Execution allowed for GetVelocity attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetVelocity_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetVelocityStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetVelocityStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetVelocity_allowed()
 *	Description : Execution allowed for SetVelocity attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetVelocity_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetVelocityStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetVelocityStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetHoldTime_allowed()
 *	Description : Execution allowed for GetHoldTime attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetHoldTime_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetHoldTimeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetHoldTimeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetHoldTime_allowed()
 *	Description : Execution allowed for SetHoldTime attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetHoldTime_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetHoldTimeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetHoldTimeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetPositionKnown_allowed()
 *	Description : Execution allowed for GetPositionKnown attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetPositionKnown_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetPositionKnownStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetPositionKnownStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetAxisType_allowed()
 *	Description : Execution allowed for GetAxisType attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetAxisType_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetAxisTypeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetAxisTypeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetMaxFrequency_allowed()
 *	Description : Execution allowed for GetMaxFrequency attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetMaxFrequency_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetMaxFrequencyStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetMaxFrequencyStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetMaxFrequency_allowed()
 *	Description : Execution allowed for SetMaxFrequency attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetMaxFrequency_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetMaxFrequencyStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetMaxFrequencyStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetSensorType_allowed()
 *	Description : Execution allowed for GetSensorType attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetSensorType_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetSensorTypeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetSensorTypeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetMaxStepLimit_allowed()
 *	Description : Execution allowed for GetMaxStepLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetMaxStepLimit_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetMaxStepLimitStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetMaxStepLimitStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetMinStepLimit_allowed()
 *	Description : Execution allowed for GetMinStepLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetMinStepLimit_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetMinStepLimitStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetMinStepLimitStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetMaxStepLimit_allowed()
 *	Description : Execution allowed for SetMaxStepLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetMaxStepLimit_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetMaxStepLimitStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetMaxStepLimitStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetMinStepLimit_allowed()
 *	Description : Execution allowed for SetMinStepLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetMinStepLimit_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetMinStepLimitStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetMinStepLimitStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_Calibrate_allowed()
 *	Description : Execution allowed for Calibrate attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_Calibrate_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CalibrateStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CalibrateStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetCalibrationOptions_allowed()
 *	Description : Execution allowed for SetCalibrationOptions attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetCalibrationOptions_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetCalibrationOptionsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetCalibrationOptionsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetCalibrationOptions_allowed()
 *	Description : Execution allowed for GetCalibrationOptions attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetCalibrationOptions_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetCalibrationOptionsStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetCalibrationOptionsStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_HoldPosition_allowed()
 *	Description : Execution allowed for HoldPosition attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_HoldPosition_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::HoldPositionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::HoldPositionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StopStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetSensorMode_allowed()
 *	Description : Execution allowed for SetSensorMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetSensorMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetSensorModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetSensorModeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetSensorMode_allowed()
 *	Description : Execution allowed for GetSensorMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetSensorMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetSensorModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetSensorModeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetAcceleration_allowed()
 *	Description : Execution allowed for GetAcceleration attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetAcceleration_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetAccelerationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetAccelerationStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetAcceleration_allowed()
 *	Description : Execution allowed for SetAcceleration attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetAcceleration_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetAccelerationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetAccelerationStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetActuatorMode_allowed()
 *	Description : Execution allowed for GetActuatorMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetActuatorMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetActuatorModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetActuatorModeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetActuatorMode_allowed()
 *	Description : Execution allowed for SetActuatorMode attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetActuatorMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetActuatorModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetActuatorModeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_Home_allowed()
 *	Description : Execution allowed for Home attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_Home_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::HomeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::HomeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetFollowingErrorLimit_allowed()
 *	Description : Execution allowed for GetFollowingErrorLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetFollowingErrorLimit_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetFollowingErrorLimitStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetFollowingErrorLimitStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetFollowingErrorLimit_allowed()
 *	Description : Execution allowed for SetFollowingErrorLimit attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetFollowingErrorLimit_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetFollowingErrorLimitStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetFollowingErrorLimitStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_StartStreaming_allowed()
 *	Description : Execution allowed for StartStreaming attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_StartStreaming_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::StartStreamingStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::StartStreamingStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetSearchDirection_allowed()
 *	Description : Execution allowed for SetSearchDirection attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetSearchDirection_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetSearchDirectionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetSearchDirectionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetSearchDirection_allowed()
 *	Description : Execution allowed for GetSearchDirection attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetSearchDirection_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetSearchDirectionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetSearchDirectionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetSensorName_allowed()
 *	Description : Execution allowed for GetSensorName attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetSensorName_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetSensorNameStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetSensorNameStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetSensorReferenceType_allowed()
 *	Description : Execution allowed for GetSensorReferenceType attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetSensorReferenceType_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetSensorReferenceTypeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetSensorReferenceTypeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetConversion_allowed()
 *	Description : Execution allowed for SetConversion attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetConversion_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetConversionStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetConversionStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_AbortStreaming_allowed()
 *	Description : Execution allowed for AbortStreaming attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_AbortStreaming_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::AbortStreamingStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::AbortStreamingStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetSensorType_allowed()
 *	Description : Execution allowed for SetSensorType attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetSensorType_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetSensorTypeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetSensorTypeStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetOffset_allowed()
 *	Description : Execution allowed for SetOffset attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetOffset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetOffsetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetOffsetStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_GetOffset_allowed()
 *	Description : Execution allowed for GetOffset attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_GetOffset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::GetOffsetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::GetOffsetStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_SetOffsetAbsolute_allowed()
 *	Description : Execution allowed for SetOffsetAbsolute attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_SetOffsetAbsolute_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SetOffsetAbsoluteStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SetOffsetAbsoluteStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdGetDouble_allowed()
 *	Description : Execution allowed for CmdGetDouble attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdGetDouble_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdGetDoubleStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdGetDoubleStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdGetUShort_allowed()
 *	Description : Execution allowed for CmdGetUShort attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdGetUShort_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdGetUShortStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdGetUShortStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdGetI32Property_allowed()
 *	Description : Execution allowed for CmdGetI32Property attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdGetI32Property_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdGetI32PropertyStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdGetI32PropertyStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdLongLong_allowed()
 *	Description : Execution allowed for CmdLongLong attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdLongLong_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdLongLongStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdLongLongStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdLongArrayVoid_allowed()
 *	Description : Execution allowed for CmdLongArrayVoid attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdLongArrayVoid_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdLongArrayVoidStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdLongArrayVoidStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdLongLong64_allowed()
 *	Description : Execution allowed for CmdLongLong64 attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdLongLong64_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdLongLong64StateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdLongLong64StateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdLong64ArrayVoid_allowed()
 *	Description : Execution allowed for CmdLong64ArrayVoid attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdLong64ArrayVoid_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdLong64ArrayVoidStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdLong64ArrayVoidStateAllowed
		return false;
	}
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SmarActMCS2Ctrl::is_CmdLongArrayLong_allowed()
 *	Description : Execution allowed for CmdLongArrayLong attribute
 */
//--------------------------------------------------------
bool SmarActMCS2Ctrl::is_CmdLongArrayLong_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Compare device state with not allowed states.
	if (get_state()==Tango::FAULT ||
		get_state()==Tango::OFF)
	{
	/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::CmdLongArrayLongStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::CmdLongArrayLongStateAllowed
		return false;
	}
	return true;
}


/*----- PROTECTED REGION ID(SmarActMCS2Ctrl::SmarActMCS2CtrlStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	SmarActMCS2Ctrl::SmarActMCS2CtrlStateAllowed.AdditionalMethods

}	//	End of namespace
